{
  "hash": "abfccc89cbc05fad3a31842a80aaddd6",
  "result": {
    "engine": "knitr",
    "markdown": "# Variable Aleatoria Discreta {#cap-distribuciones}\n\n::: {.callout-tip icon=false}\n## Objetivos de aprendizaje\n\nAl finalizar este capítulo, el estudiante será capaz de:\n\n- Definir variable aleatoria discreta y construir su función de probabilidad (pmf) y función de distribución acumulada (cdf) a partir de un experimento aleatorio.\n- Calcular el valor esperado $E[X]$ y la varianza $\\text{Var}(X)$ de una variable aleatoria discreta mediante sus definiciones y propiedades.\n- Reconocer y aplicar las distribuciones discretas más importantes (Bernoulli, Binomial, Hipergeométrica, Poisson, Geométrica y Binomial Negativa), identificando en qué situación usar cada una.\n- Distinguir entre muestreo con y sin reemplazo, y elegir el modelo probabilístico adecuado (Binomial vs Hipergeométrica) según el contexto.\n- Calcular probabilidades de eventos complejos usando las distribuciones discretas vistas, tanto manualmente como con R.\n\n:::\n\nEn este capítulo estudiaremos las variables aleatorias discretas: qué son, cómo se describen mediante su función de probabilidad y su función de probabilidad acumulada, y cómo resumir su comportamiento mediante la esperanza y la varianza. Después revisaremos las distribuciones discretas más utilizadas en la práctica (Uniforme, Bernoulli, Binomial, Hipergeométrica y Poisson), discutiremos las diferencias entre el muestreo con y sin reemplazo, y cerraremos con material complementario sobre las distribuciones Geométrica, Binomial Negativa y las distribuciones discretas conjuntas. A lo largo del capítulo se incluyen ejemplos resueltos y ejercicios propuestos para practicar los conceptos.\n\n## Variable aleatoria\n\nSe denominan ___variables___ a las características particulares de cualquier elemento de alguna población o muestra que se tenga, dicha variable puede tomar distintos valores y, en general, hay dos tipos de variables (Cualitativa [Edad] y Cuantitativa [Género]). Se dice que son ___aleatorias___ porque el valor observado no se conoce hasta la realización del experimento, aunque sí se sabe cuáles son los posibles resultados\n\n\n**Nota.**\nUna variable aleatoria (v.a) es aquella cuyos valores son números reales asignados a los resultados de un experimento aleatorio.\n\n:::: {.content-visible when-format=\"html\"}\n[📖 Magín Zúñiga Estrada]{.fuente-badge .fuente-magin}\n\n::::\n\n### Definición formal\n\n::: {.callout-tip icon=false}\n## Definición — Variable aleatoria\nSea $\\Omega$ un espacio muestral. Se define $X$ como una **variable aleatoria** si es una función:\n$$X : \\Omega \\longrightarrow \\mathbb{R}$$\nque asigna un número real a cada resultado del experimento aleatorio. Se clasifica en:\n\n- **Discreta**: si toma un conjunto discreto (finito o infinito numerable) de valores.\n- **Continua**: si toma valores en un intervalo de la recta real.\n\n:::\n\n**¿Por qué se llama \"aleatoria\"?** Porque su valor depende del resultado aleatorio del experimento; no se conoce hasta que éste se realiza.\n\n**Ejemplo motivador (Magín).** Se lanzan dos dados; el resultado se denota $(i,j)$, con $P(i,j)=1/36$. Se define la apuesta:\n$$X(i,j) = \\begin{cases} 1000, & \\text{si } i+j=7 \\\\ -200, & \\text{en otro caso} \\end{cases}$$\n$X$ es una variable aleatoria que asigna una ganancia o pérdida monetaria a cada resultado del espacio muestral.\n\n### Relación entre evento y variable aleatoria\n\nPara cualquier valor $a$, la expresión $\\{X = a\\}$ denota el **evento** formado por todos los resultados $\\omega \\in \\Omega$ tales que $X(\\omega) = a$. Por ejemplo, en el juego de dados anterior, $\\{X = 1000\\}$ es el conjunto $\\{(1,6),(2,5),(3,4),(4,3),(5,2),(6,1)\\}$, de modo que $P(X=1000) = 6/36$.\n\nDe igual forma, las desigualdades también describen eventos: $\\{X \\leq a\\}$ es el conjunto de todos los $\\omega$ tales que $X(\\omega) \\leq a$.\n\n:::: {.callout-note icon=false}\n## Ejemplo 1\nSe lanza una moneda tres veces. Denotamos cada resultado como **á** (águila) o **s** (sol). El espacio muestral es:\n$$S = \\{(á,á,á),\\,(á,s,á),\\,(á,á,s),\\,(s,á,á),\\,(s,s,á),\\,(s,á,s),\\,(á,s,s),\\,(s,s,s)\\}$$\n\nSe define la variable aleatoria $X$ como el **número de águilas** observadas en el lanzamiento de las tres monedas. Los posibles valores de $X$ son $\\{0, 1, 2, 3\\}$ y los eventos correspondientes son:\n\n| $X$ | Resultados | Descripción |\n|-----|-----------|-------------|\n| $0$ | $(s,s,s)$ | Ninguna águila |\n| $1$ | $(á,s,s),\\,(s,á,s),\\,(s,s,á)$ | Exactamente una águila |\n| $2$ | $(á,á,s),\\,(á,s,á),\\,(s,á,á)$ | Exactamente dos águilas |\n| $3$ | $(á,á,á)$ | Tres águilas |\n\n\n::::\nEs importante mencionar que en este ejemplo se supone que es posible distinguir cuál es la moneda 1, la moneda 2 y la moneda 3.\n\nLa variable aleatoria traslada los eventos del espacio muestral al conjunto de los números reales, lo que permite aplicar herramientas matemáticas —cálculo, álgebra— y asignar a cada valor una probabilidad bien definida.\n\n\n## Variable aleatoria discreta\nEl común de los fenómenos aleatorios discretos tiende a comportarse bajo determinadas características generales, por lo que se han desarrollado algunas distribuciones discretas de probabilidad.\n\n**Nota.** En el ejemplo anterior la v.a. proviene de un experimento con espacio muestral discreto, es decir, tiene _espacio muestral finito_ o _infinito numerable_\n\nA continuación explicamos a lo que se refieren los anteriores conceptos.\n\n**Experimentos aleatorios con espacio muestral finito:**\n\nAlgunos ejemplos de este tipo son: lanzamiento de un dado y ver la cara que aparece resultante, el resultado de un partido de futbol, el género de un individuo, números de pacientes curados al aplicar un medicamente en n pacientes seleccionados, etcétera.\n\n__Experimentos aleatorios con espacio muestral infinito contable__\n\nUn ejemplo de este tipo es el número de errores ortográficos que pueden existir en un libro, los errores ortográficos pueden ser\n0, 1, 2, … ; por supuesto que, en la vida real, no hay infinitos números de errores en un libro, pero si el libro es grande (su tamaño tiende a infinito) el número de errores posibles sería muy grande y considerarse infinito.\n\n:::: {.callout-note icon=false}\n## Ejemplo 1\nEl número de terremotos que pueden ocurrir en un periodo de tiempo de 15 años se puede denotar con una variable aleatoria discreta con un espacio muestral infinito contable. Si denotamos con X la \nvariable aleatoria el número de terremotos la variable aleatoria puede considerar los siguientes \nvalores \n\nX=1, 2, 3, 4, …\n\n::::\n\n### Función de probabilidad y función de probabilidad acumulada\nLa asignación de valores reales a cada evento del espacio completo de eventos lo hemos llamado _variable aleatoria_; como vimos, a cada evento del espacio completo de eventos le corresponde una probabilidad determinada, a este conjunto de probabilidades le llamaremos la ___distribución de probabilidad___, esto quiere decir que existe un rango de valores que puede tomar, por lo tanto, cualquier fenómeno aleatorio puede tomar valores en el intervalo (0,1).\n\n**Ejemplo 1**:\nConsiderando el ejemplo anterior de las monedas y que cada resultado tiene la misma probabilidad de ocurrir, definimos la v.a X: Número de águilas en los lanzamientos. Tenemos la siguiente tabla:\n\n\n__Tabla 1:__\n\n\n| x |         Resultado         | Probabilidad P(X=x) |\n|:-:|:-------------------------:|:-------------------:|\n| 0 |          (c,c,c)          |   P(X=0)=1/8=0.125  |\n| 1 | (a,c,c), (c,a,c), (c,c,a) |   P(X=1)=3/8=0.375  |\n| 2 | (a,a,c), (a,c,a), (c,a,a) |   P(X=2)=3/8=0.375  |\n| 3 |          (a,a,a)          |   P(X=3)=1/8=0.125  |\n\n\nGráficamente podemos hacer lo siguiente:\n\n**Gráfica de Probabilidad: Lanzamiento de Monedas**\n\nPara representar gráficamente una variable aleatoria discreta (como el número de águilas obtenidas al lanzar 3 monedas), lo más adecuado es utilizar un diagrama de barras o un gráfico de bastones (lollipop chart) que muestre la función de masa de probabilidad $P(X=x)$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/grafica_monedas-1.png){fig-align='center'}\n:::\n:::\n\n\n*(Nota didáctica: Observa cómo la gráfica es perfectamente simétrica. Esto ocurre porque la probabilidad de obtener \"águila\" o \"sello\" en una moneda justa es la misma ($p=0.5$), y al ser 3 lanzamientos, la distribución Binomial resultante alcanza su punto máximo en los valores centrales 1 y 2).*\n\n\n\nNótese que la última columna de la tabla 1 proporciona la probabilidad de ocurrencia para cada valor de la variable aleatoria, a dicha columna se le denomina __Función de masa de probabilidad (pmf)__ o __función de densidad de probabilidad  (pdf)__. La función masa de probabilidad es aquella que surge al asignar probabilidades a cada uno de los valores de una variable aleatoria y se denota como $P(X)$.\n\nDe la tabla 1 es fácil percibir que la suma de las probabilidades correspondientes a todos los valores posibles que toma la variable aleatoria es igual a $1$, esto siempre ocurrirá para cualquier variable aleatoria, y se debe a que la probabilidad en el espacio muestral es $1$, es decir, $P(S)=1$.\nTambién se puede acumular la probabilidad del valor mínimo de la variable aleatoria X hasta un determinado valor de esta misma. Esto se ilustra en la tabla 2 considerando nuevamente el ejemplo 2.1.1.\n\n__Tabla 2:__\n\n| x |         P(X=x)         | Función de probabilidad acumulada F(X) |\n|:-:|:-------------------------:|:-------------------:|\n| 0 | P(X=0)=1/8=0.125 |  0.125   |\n| 1 | P(X=1)=3/8=0.375 |  0.5   |\n| 2 | P(X=2)=3/8=0.375 |  0.875   |\n| 3 | P(X=3)=1/8=0.125 |  1.00   |\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/grafica_acumulada_monedas-1.png){fig-align='center'}\n:::\n:::\n\n\nLa última columna de la __Tabla 2__ proporciona la probabilidad de ocurrencia acumulada para cada valor de la variable aleatoria, a dicha columna se le denomina función de probabilidad acumulada y se denota como $F(X)$.\n\nRecordemos que una distribución de probabilidad siempre está dada en el intervalo $(0,1)$\n\n### Propiedades formales de la pmf y la cdf\n\n::: {.callout-tip icon=false}\n## Propiedades de la función masa de probabilidad (pmf)\nSea $p(a) = P(X = a)$ la pmf de una v.a. discreta $X$. Entonces:\n\n1. $0 \\leq p(a) \\leq 1$ para todo $a$.\n2. Si $a$ es un valor que $X$ nunca toma, entonces $p(a) = 0$.\n3. $\\displaystyle\\sum_{\\text{todos los } a} p(a) = 1$.\n\n:::\n\n::: {.callout-tip icon=false}\n## Propiedades de la función de distribución acumulada (cdf)\nLa **cdf** de una v.a. discreta $X$ se define como $F(a) = P(X \\leq a)$. Satisface:\n\n1. $F$ es **no decreciente**: si $a \\leq b$ entonces $F(a) \\leq F(b)$.\n2. $0 \\leq F(a) \\leq 1$ para todo $a$.\n3. $\\displaystyle\\lim_{a \\to \\infty} F(a) = 1$ y $\\displaystyle\\lim_{a \\to -\\infty} F(a) = 0$.\n\n:::\n\n> **Nota:** La cdf incluye el \"igual a\", por lo que $F(a) = P(X \\leq a)$. Esto importa al calcular probabilidades del tipo $P(X > a) = 1 - F(a)$ o $P(a < X \\leq b) = F(b) - F(a)$.\n\n::: {.callout-caution icon=false}\n## Errores comunes: pmf y cdf\n\n**Error 1 — Usar la pmf cuando se necesita la cdf (o viceversa).**  \nLa pmf da $P(X = k)$; la cdf da $P(X \\leq k)$. Para preguntas como \"¿cuál es la probabilidad de obtener *a lo más* 3 éxitos?\", siempre se usa la cdf: $F(3) = \\sum_{k=0}^{3} P(X=k)$.\n\n**Error 2 — Creer que la pmf puede tomar cualquier valor entre 0 y 1.**  \nCada valor individual de la pmf sí está en $[0,1]$, pero la condición que realmente la define es que la *suma* sobre todos los valores sea 1: $\\sum_k P(X=k) = 1$. Una pmf con tres valores iguales a 0.4, por ejemplo, sería inválida.\n\n:::\n\n\n\n### Valor esperado de una variable aleatoria discreta\n\nLa esperanza matemática, valor esperado o media de una variable aleatoria discreta ($E[X]$) corresponde al valor esperado de que un cierto evento ocurra. Se calcula como la suma de los productos de cada valor que toma la variable aleatoria por su respectivo valor de probabilidad:\n\n\n $\\mu = E[X] = \\sum_{i=1}^{k}x_i \\cdot P(x_i)$\n\nLa varianza de una variable aleatoria discreta se define como la suma de los desvíos de cada valor que toma la variable aleatoria con respecto a su media, elevados al cuadrado y multiplicado por su respectiva probabilidad. Esto nos indica qué tan dispersos llegan a estar nuestros datos con respecto de nuestro promedio o media.\n\n $\\text{Var}(X) = \\sum_{i=0}^{k}(x_i-E[X]) \\cdot P(x_i)$\n\n\n**Ejemplo 2**:\n\nSi el número de accidentes en una jornada laboral, en cierta zona industrial sigue el comportamiento:\n\n|      x= Número de accidentes      |  0  |  1  |  2  |  3  |\n|:---------------------------------:|:---:|:---:|:---:|:---:|\n| P(X=x: Probabilidad de accidentes | 1/6 | 1/3 | 1/3 | 1/6 |\n\n\n¿Cuál es el número esperado de accidentes por jornada? ¿Cuál es la varianza?\n\n**Solución:**\n\nEl número esperado de accidentes está dado por:\n\n$E[X] = \\sum_{i=0}^{3}x_i \\cdot P(x_i) =$ \n$0 \\cdot \\dfrac{1}{6} + 1 \\cdot \\dfrac{1}{3}+ 2 \\cdot \\dfrac{1}{3} + 3 \\cdot \\dfrac{1}{6} = \\dfrac{1}{3} + \\dfrac{2}{3} + \\dfrac{1}{2} = \\dfrac{3}{2} = 1.5$\n\nPor lo tanto, se esperan alrededor de 2 accidentes por jornada laboral. Veamos la varianza:\n\n$\\text{Var}(X) = \\sum_{i=0}^{k}(x_i-E[X]) \\cdot P(x_i) = (0-1.5)^2 \\cdot \\dfrac{1}{6} + (1-1.5)^2 \\cdot \\dfrac{1}{3} + (2-1.5)^2 \\cdot \\dfrac{1}{3} + (3-1.5)^2 \\cdot \\dfrac{1}{6} = 0.375 + 0.83 + 0.083 + 0.375 = 0.916$\n\nEntonces la variación es de 1 accidente por jornada laboral.\n\n__Nota:__ \n\nLa raíz cuadrada de la varianza:$\\sqrt{\\text{Var}(X)}$, se le conoce como desviación estándar.\n\n**Ejemplo 3**\n\nLos estudiantes de psicología en general manifiestan que tienen mayor dificultad en los cursos que involucren conceptos matemáticos. Experimentos anteriores han consistido en exponer 5 palabras y 5 números ante los estudiantes durante 10 segundos al comienzo de la clase y luego preguntar por ellos al final de la clase, los resultados se muestran a continuación.\n\n$X$: Denota la variable aleatoria que recoge información respecto a la cantidad de palabras que recuerda.\n\n$Y$: Denota la variable aleatoria que recoge información respecto a la cantidad de números que recuerda.\n\nAcomodándolo en una tabla:\n\n__Tabla de distribución de la variable aleatoria X__\n\n|        | x=0  | x=1 | x=2 | x=3  | x=4  | x=5  |\n|--------|------|-----|-----|------|------|------|\n| P(X=x) | 0.15 | 0.2 | 0.3 | 0.05 | 0.05 | 0.2 |\n\n\n__Tabla de distribución de la variable aleatoria Y__\n\n|        | y=0 | y=1  | y=2 | y=3 | y=4 | y=5  |\n|--------|-----|------|-----|-----|-----|------|\n| P(Y=y) | 0.1 | 0.35 | 0.2 | 0.2 | 0.1 | 0.05 |\n\nAhora nos hacemos la pregunta, _¿qué es más probable que recuerden? ¿Al menos tres palabras o al menos 3 números?_\n\nLa probabilidad de que un estudiante de psicología recuerde al menos tres palabras es:\n\n $P(X \\geq x)$ = $P(X=3) + P(X=4) + P(X=5)$ = $0.05 + 0.05 + 0.2$ = $0.3$\n \n Este proceso puede hacerse de manera similar aplicando lo siguiente: $P(X\\geq x) =  1-P(X<x)$, similarmente, $P(X\\leq x) =  1-P(X>x)$\n\nComo ejemplo podemos considerar lo siguiente:\n\n$P(X \\geq 3) = 0.35$\n\nLo invitamos a hacer las cuentas del resultado.\n\nEl valor de la media de palabras es:\n\n$E[X]$=$0 \\cdot 0.15+1 \\cdot 0.2+2 \\cdot 0.3+3 \\cdot 0.05+4 \\cdot 0.05+5 \\cdot 0.2$=$2$\n\nPor lo tanto, los estudiantes recuerdan, en promedio, alrededor de 2 palabras.\n\nLo invitamos a calcular $E[X]$, así como las correspondientes varianzas de cada variable.\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. Una variable aleatoria $X$ tiene la siguiente función de probabilidad: $P(X=0)=0.1$, $P(X=1)=0.3$, $P(X=2)=0.4$, $P(X=3)=0.2$. Verifique que es una función de probabilidad válida y calcule $E[X]$ y $\\text{Var}(X)$.\n2. El número de llamadas que recibe una central telefónica en un minuto tiene la distribución $P(X=0)=0.2$, $P(X=1)=0.3$, $P(X=2)=0.3$, $P(X=3)=0.2$. Calcule $P(X \\ge 2)$ y la desviación estándar de $X$.\n3. Explique, con sus propias palabras, la diferencia entre la función de probabilidad $P(X=x)$ y la función de probabilidad acumulada $F(x)$, y dé un ejemplo donde se use cada una.\n\n:::\n\n## Familia de distribuciones de probabilidad discretas\n\nDada la naturaleza de ciertos eventos, como lanzar una moneda, arrojar un dado, seleccionar de manera indistinta a una persona de un grupo, se desarrollaron ciertos procedimientos para analizar esos casos, pues en cada ejemplo cada uno de los valores de las posibles variables aleatorias tiene la misma probabilidad de ocurrir\n\n### Distribución aleatoria discreta Uniforme {#sec-uniforme-discreta}\n\nSea el experimento que consiste en lanzar un dado. El resultado de interés es el número de la cara del dado, la cual se denota con la variable aleatoria X. En un dado existen 6 caras, por lo que la variable aleatoria puede tomar valores de 1 a 6 y si se asume que cada cara tiene la misma probabilidad de aparecer, entonces la función masa de probabilidad de la variable aleatoria X es la mostrada en la tabla 7.\n\n\n__Tabla de función masa de probabilidad de la variable aleatoria de las caras de un dado:__\n\n| x | P(X=x) |\n|:-:|:------:|\n| 1 |   1/6  |\n| 2 |   1/6  |\n| 3 |   1/6  |\n| 4 |   1/6  |\n| 5 |   1/6  |\n| 6 |   1/6  |\n\nLa función masa de probabilidad presentada en la tabla se puede expresar mediante la siguiente forma:\n\n$P(X=x)=\\dfrac{1}{6}$ ; $x=1,2,3,..., 6$\n\nComo todos los eventos son equiprobables, se puede generalizar de la siguiente manera:\n\n$P(X=x)=\\dfrac{1}{n}$ ; Si $X=x_1,x_2,x_3,..., x_n$\n\nDonde $n$ indica el número de eventos que se pueden considerar.\n\n¿Cuál es la probabilidad de que aparezcan caras menores o igual a la cara 3?\n\n$F(3) = P(X \\leq 3) = P(X=1)+P(X=2)+P(X=3) = \\dfrac{1}{6} + \\dfrac{1}{6} + \\dfrac{1}{6}$ \n\nDonde $F(X≤3)$ en este caso calcula la probabilidad acumulada a partir de la cara 1 hasta la cara 3. La función de distribución acumulada de la variable discreta X es:\n\n__Tabla de probabilidad acumulada:__\n\n| x | $F(X\\leq x)$ |\n|:-:|:---------:|\n| 1 |    1/6    |\n| 2 |    2/6    |\n| 3 |    3/6    |\n| 4 |    4/6    |\n| 5 |    5/6    |\n| 6 |    6/6=1   |\n\nDe manera general, la función de probabilidad acumulada de una variable aleatoria discreta uniforme queda:\n\n$$F(X \\le x) = \\sum_{i=1}^{n}P(X=x_i)$$\nsi $X=x_1, x_2, \\dots, x_n$\n\nLa esperanza matemática o media (EX) de una variable aleatoria discreta uniforme X se define como las sumas de productos de los valores que puede tomar dicha variable aleatoria y su correspondiente probabilidad de ocurrencia. En símbolos matemáticos:\n\n $$\\mu = E[X] = \\sum_{i=1}^{n}x_i \\cdot P(X=x_i)$$\n\nComo se ha estado trabajando en los ejemplos anteriores. Usando el ejemplo de los dados:\n\n| x | P(X=x) | $F(X \\leq x)$ |\n|:-:|--------|:---------:|\n| 1 | 1/6    |    1/6    |\n| 2 | 1/6    |    2/6    |\n| 3 | 1/6    |    3/6    |\n| 4 | 1/6    |    4/6    |\n| 5 | 1/6    |    5/6    |\n| 6 | 1/6    |    6/6    |\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/grafica_pmf_dado-1.png){fig-align='center'}\n:::\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/grafica_cdf_dado-1.png){fig-align='center'}\n:::\n:::\n\n\nPor lo tanto: $E[X] = (1+2+3+4+5+6) \\cdot \\dfrac{1}{6}$ = $3.5$\n\nSimilarmente, la varianza para una distribución uniforme está dada por:\n\n $\\text{Var}(X) = \\sum_{i=1}^{n}(x_i-E[X])^2 \\cdot P(X=x_i)$\n \n En estos casos, es factible tener una tabla como la siguiente para no perder de vista nuestros datos:\n \n | x | P(X=x) | $F(X \\leq x)$ | $(x_i-E[X])^2$ | $(x_i-E[X])^2 \\cdot P(X=x_i)$ |\n|:-:|:------:|:---------:|:------------:|:---------------------:|\n| 1 |   1/6  |    1/6    |     6.25     |         1.041         |\n| 2 |   1/6  |    2/6    |     2.25     |         0.375         |\n| 3 |   1/6  |    3/6    |     0.25     |          0.41         |\n| 4 |   1/6  |    4/6    |     0.25     |          0.41         |\n| 5 |   1/6  |    5/6    |     2.25     |         0.375         |\n| 6 |   1/6  |    6/6    |     6.25     |         1.041         |\n\nEntonces, $\\text{Var}(X)= (1-3.5)^2 +(2-3.5)^2+(3-3.5)^2+(4-3.5)^2+(5-3.5)^2+(6-3.5)^2 \\cdot \\dfrac{1}{6}$\n=$2.91$\n \n \n### Distribución aleatoria discreta Bernoulli {#sec-bernoulli}\n\nEs la distribución más sencilla que podemos construir, y es aquella cuyo espacio de eventos está compuesto por dos eventos complementarios, donde a uno de ellos lo designamos por el evento de éxito y el otro por el de fracaso; lo cual implica que en la realización de un solo experimento se podrá presentar uno u otro, pero no ambos. \n\nEn pocas palabras, representaremos como $p$ a la probabilidad de éxito y a $1-p$ la probabilidad de fracaso.\n\nSu función de probabilidad (de que un solo experimento ocurra x éxito), está dada por:\n\n$P(X=x) = p^x(1-p)^{1-x}$\n\nCabe destacar que $x$ solo toma los valores de 0 o 1, también se puede interpretar como verdadero o falso.\n\n\nLa esperanza de ésta distribución es:\n\n$E[X] = p$\n\nY su varianza:\n\n$\\text{Var}(X) = p(1-p)$\n\n:::: {.content-visible when-format=\"html\"}\n[📖 Magín Zúñiga Estrada]{.fuente-badge .fuente-magin}\n\n::::\n\n::: {.callout-tip icon=false}\n## Definición formal: distribución Bernoulli\n\nUna variable aleatoria $X$ tiene distribución **Bernoulli** con parámetro $p$ cuando su espacio muestral es $\\Omega = \\{0, 1\\}$ y:\n\n$$p(X=1) = p, \\qquad p(X=0) = 1-p$$\n\ndonde $p \\in (0,1)$ es la probabilidad de éxito. Se escribe $X \\sim \\text{Ber}(p)$, y se lee *\"X sigue una distribución Bernoulli con parámetro p\"*.\n\n**Ejemplo:** los votantes a favor o en contra de una propuesta. Si $p$ es la proporción de la población votante a favor, entonces el voto de un individuo elegido al azar se puede modelar con $\\text{Ber}(p)$.\n\n:::\n\n\n**Ejemplo 1**\n\nEn una empresa se tiene el área de llenado. Las botellas defectuosas en el área de llenado son aquellas cuyas botellas no se llenan completamente (menor a 248 mL) y no defectuosas aquellas que son llenadas completamente (en un intervalo de 250 y 248 mL). \n\nSi se sabe que en el área de llenado 95% de las botellas son no defectuosas y el restante 5% son defectuosas. Proporcionar la función masa de probabilidad del resultado del llenado para una botella.\nSi X denota la variable aleatoria del resultado de llenado de una botella. Entonces:\n\n- $X=0$ denota botella no defectuosa\n- $X=1$ denota botella defectuosa. \n\nSea p la probabilidad de que la botella sea defectuosa. De modo que la función masa de probabilidad es:\n\n- $$P(X)=0=1-p=0.95$$    \n- $$P(X)=1=p=0.05$$\n\n**Ejemplo 2**\n\nSe observa un insecto en el lugar donde se aplicó un insecticida, y se registra si está vivo o muerto. Por ejemplo, si se piensa que el insecticida es eficaz en 90% y no eficaz en 10%. Indique la función masa de probabilidad para un espécimen seleccionado.\n\nSi X denota la variable aleatoria de la situación de un individuo.\nX=0 el individuo está muerto y X=1 el individuo está vivo. Se define a p como la probabilidad de que el individuo esté vivo, el insecticida no fue eficaz. De modo que la función masa de probabilidad es:\n\n- $$PX=0=1-p=1-0.10=0.90 $$\n- $$PX=1=p=0.10 $$\n\n\n## Muestreo\n\nEn la mayoría de los problemas en lugar de observar una sola unidad se observan un número n de unidades experimentales, posteriormente se clasifican en una de dos categorías. En esta parte se hace una reflexión sobre la manera de seleccionar unidades experimentales en cada repetición del experimento aleatorio.\n\n\n**Ejemplo 1**\n\nSupongamos que se cuenta con una bolsa que tiene en su interior 10 bolas negras y 20 bolas blancas. Un experimento aleatorio consiste en extraer sucesivamente bolas de esta bolsa.\nEn cada repetición del experimento se extrae una bola, se registra y se devuelve a la bolsa.\n\nLa probabilidad de extraer una bola negra en la primera extracción será de\n$\\dfrac{10}{30} = \\dfrac{1}{3}$\n\n\nEn la segunda extracción, la probabilidad de extraer una bola negra también será de $\\dfrac{10}{30} = \\dfrac{1}{3}$ ya que luego de realizar la primera extracción se devolvió la bola seleccionada a la bolsa.\nEn síntesis, devolviendo la bola extraída a la bolsa después de cada extracción, la probabilidad de extraer bolas negras o blancas permanece inalterada de prueba a prueba. Entonces, si nuestro éxito es la extracción de una bola negra, la probabilidad de éxito p = 1/3 y se mantiene constante a través de las n repeticiones del experimento. Ante situaciones como la planteada, se dice que el muestreo se hace con reemplazo.\n\n### Muestreo aleatorio con reemplazo\n\nEl concepto de muestreo con reemplazo implica que las extracciones son independientes porque la ocurrencia de un evento en particular en una prueba del experimento no modifica la probabilidad de ocurrencia del evento en la prueba siguiente.\nConsideremos ahora el caso en que se extraen unidades experimentales de un conjunto y que ellas también pueden asignarse a solo dos categorías diferentes, como en el ejemplo anterior: bola blanca y bola negra, pero con la diferencia de que la bola extraída no se devuelve a la bolsa que las contiene.\n\nLa probabilidad de extraer una bola negra en la primera extracción seguirá siendo $p = \\dfrac{1}{3}$, pero si la bola no se vuelve a integrar al conjunto original la probabilidad de extraer otra bola negra en la segunda extracción se habrá modificado, y será ahora de $\\dfrac{9}{29}$ ya que en la bolsa quedan solo 9 bolas negras y 29 bolas en total. En este caso se dice que el muestreo se realiza sin reemplazo.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/grafica_muestreo-1.png){fig-align='center'}\n:::\n:::\n\n\n### Muestreo aleatorio sin reemplazo\n\nEl **muestreo con reemplazo** es un procedimiento en el que cada unidad experimental extraída del conjunto original **se devuelve antes de realizar la siguiente extracción**.  \nEsto implica que **todas las extracciones son independientes**, ya que la ocurrencia de un evento en una prueba del experimento **no modifica** la probabilidad de ocurrencia del mismo evento en la prueba siguiente.\n\nEn términos probabilísticos, la independencia significa que la **distribución de probabilidad se mantiene constante** en cada repetición del experimento aleatorio.\n\n\n\nAhora consideremos el caso en que se extraen unidades experimentales de un conjunto y que dichas unidades pueden clasificarse en **dos categorías**, como en el ejemplo clásico de una urna que contiene **bolas blancas y bolas negras**, pero con una diferencia fundamental:  \n**la bola extraída no se devuelve a la bolsa**.\n\nSupongamos que la urna contiene inicialmente:\n\n- 10 bolas negras  \n- 20 bolas blancas  \n\npor lo que el total es de 30 bolas.\n\n\n\n**Primera extracción**\n\nLa probabilidad de extraer una bola negra en la **primera extracción** es\n\n$$\nP(\\text{Negra}_1) = \\frac{10}{30}\n$$\n\nya que todas las bolas están aún en la urna.\n\n\n\n**Segunda extracción (sin reemplazo)**\n\nSi la bola extraída **no se devuelve a la bolsa**, la composición del conjunto cambia.  \nEn particular, si en la primera extracción se obtuvo una bola negra, entonces:\n\n- quedan 9 bolas negras  \n- quedan 29 bolas en total  \n\nPor lo tanto, la probabilidad de extraer una bola negra en la **segunda extracción**, condicionada a que la primera fue negra, es\n\n$$\nP(\\text{Negra}_2 \\mid \\text{Negra}_1) = \\frac{9}{29}\n$$\n\n\n\nEn este caso se dice que el **muestreo se realiza sin reemplazo**.\n\n> **Observación:**  \n> El muestreo sin reemplazo implica que las extracciones **no son independientes**, ya que la ocurrencia de un evento en una prueba del experimento **modifica la probabilidad** de ocurrencia del evento en la prueba siguiente.\n\nEn el lenguaje estadístico, afirmar que los ensayos o repeticiones de un experimento aleatorio son **independientes** equivale a decir que la **distribución de probabilidad es la misma en cada ensayo**.  \nCuando esta condición no se cumple, como en el muestreo sin reemplazo, las repeticiones son **dependientes**.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/unnamed-chunk-1-1.png)\n:::\n:::\n\n\n**Extracciones con y sin reemplazo**\n\nConsideremos una urna que contiene **30 bolas**, de las cuales **10 son negras** y **20 son de otro color**. Se realizan **tres extracciones sucesivas**, y definimos el siguiente evento:\n\n**Evento $E$:**  \n> *El resultado de la extracción $i$ es una bola negra.*\n\nNuestro objetivo es calcular la **probabilidad de obtener tres bolas negras consecutivas** bajo dos esquemas de muestreo distintos: **con reemplazo** y **sin reemplazo**.\n\n\n\n**Muestreo con reemplazo**\n\nCuando el muestreo es **con reemplazo**, cada bola extraída se devuelve a la urna antes de la siguiente extracción.  \nEsto implica que:\n\n- La composición de la urna **no cambia**.\n- Las extracciones son **independientes** entre sí.\n\nLa probabilidad de extraer una bola negra en cualquier extracción es:\n\n$$\nP(E) = \\frac{10}{30} = \\frac{1}{3}\n$$\n\nPor lo tanto, la probabilidad de obtener **tres bolas negras en tres extracciones** es:\n\n$$\nP(E)\\,P(E \\mid E)\\,P(E \\mid EE)\n$$\n\nDado que hay independencia entre las extracciones, esta expresión se simplifica a:\n\n$$\nP(E)\\,P(E)\\,P(E)\n= \\frac{1}{3} \\times \\frac{1}{3} \\times \\frac{1}{3}\n$$\n\n\n\n::: {.callout-note icon=false}\n## Observación\nEl muestreo con reemplazo genera **ensayos independientes**, lo que permite aplicar directamente el **Principio Básico de Conteo** y multiplicar probabilidades iguales en cada repetición.\n\n:::\n\n\n\n**Muestreo sin reemplazo**\n\nAhora supongamos que el muestreo es **sin reemplazo**, es decir, cada bola extraída **no se devuelve** a la urna.\n\nEn este caso:\n\n- La composición de la urna **cambia** después de cada extracción.\n- Las extracciones **no son independientes**.\n\nLa probabilidad de obtener tres bolas negras consecutivas se expresa como:\n\n$$\nP(E)\\,P(E \\mid E)\\,P(E \\mid EE)\n$$\n\npero ahora cada probabilidad condicional es distinta:\n\n$$\nP(E)\\,P(E \\mid E)\\,P(E \\mid EE)\n=\n\\frac{10}{30} \\times \\frac{9}{29} \\times \\frac{8}{28}\n$$\n\n\n\n**Anotación:**  \nObsérvese que, al no haber reemplazo, la probabilidad de éxito **disminuye en cada extracción**, ya que el número de bolas negras disponibles se reduce.\n\n\n\n**Modelos probabilísticos asociados**\n\n- Cuando las extracciones se realizan **con reemplazo en poblaciones finitas**, o **sin reemplazo en poblaciones infinitas** (como se verá más adelante), los ensayos son independientes y el experimento se modela mediante una **variable aleatoria binomial**, al tratarse de repeticiones de un ensayo tipo Bernoulli.\n\n- En cambio, cuando las extracciones se realizan **sin reemplazo en poblaciones finitas**, las probabilidades cambian en cada repetición, por lo que el experimento se modela mediante una **variable aleatoria hipergeométrica**.\n\n::: {.callout-caution icon=false}\n## Errores comunes: Binomial vs Hipergeométrica\n\n**Error — Usar Binomial cuando el muestreo es sin reemplazo en población finita.**  \nLa Binomial supone ensayos *independientes* con probabilidad de éxito constante. Cuando se extrae sin reemplazo de una población pequeña, la probabilidad cambia en cada extracción y el modelo correcto es la **Hipergeométrica**. La Binomial solo es una buena aproximación cuando $n < 5\\%$ del total $N$.\n\n:::\n\n\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. Una urna contiene 8 bolas rojas y 12 bolas azules. Se extraen 2 bolas sin reemplazo. Calcule la probabilidad de que ambas sean rojas.\n2. Repita el ejercicio anterior suponiendo que el muestreo se realiza con reemplazo. Compare ambos resultados y explique a qué se debe la diferencia.\n3. ¿Bajo qué condición el muestreo sin reemplazo puede aproximarse razonablemente por un muestreo con reemplazo? Justifique su respuesta usando los conceptos de esta sección.\n\n:::\n\n## Distribución Binomial {#sec-binomial}\n\n:::: {.content-visible when-format=\"html\"}\n[📖 Magín Zúñiga Estrada]{.fuente-badge .fuente-magin}\n\n::::\n\n::: {.callout-tip icon=false}\n## Definición formal: distribución Binomial\n\nSuponga $n$ ensayos Bernoulli independientes, cada uno con probabilidad de éxito $p$. La variable aleatoria $X$ = número de éxitos tiene distribución **binomial** con parámetros $(n, p)$, denotada $X \\sim \\text{Bin}(n, p)$. Su función masa de probabilidad es:\n\n$$P(X = k) = \\binom{n}{k} p^{k}(1-p)^{n-k}, \\quad k = 0, 1, 2, \\ldots, n$$\n\n| $k$ | $0$ | $1$ | $2$ | $\\cdots$ | $n-1$ | $n$ |\n|-----|-----|-----|-----|-----------|--------|-----|\n| $p(k)$ | $(1-p)^n$ | $\\binom{n}{1}p(1-p)^{n-1}$ | $\\binom{n}{2}p^2(1-p)^{n-2}$ | $\\cdots$ | $\\binom{n}{n-1}p^{n-1}(1-p)$ | $p^n$ |\n\n**Relación con Bernoulli:** $\\text{Bin}(1,p) = \\text{Ber}(p)$.\n\n:::\n\nUn **experimento de tipo Bernoulli** surge cuando se selecciona al azar una unidad experimental y, con base en una característica de interés, dicha unidad se clasifica en **una de dos categorías mutuamente excluyentes**, comúnmente denominadas **éxito** o **fracaso**.\n\nUn ejemplo típico de una variable aleatoria Bernoulli es el caso de un **biólogo** que toma una planta y la clasifica de acuerdo con si **presenta floración o no**.\n\n- **Éxito (F):** la planta tiene flores  \n- **Fracaso (Fᶜ):** la planta no tiene flores  \n\nCada observación individual constituye un **experimento Bernoulli**.\n\n\n\n**Repetición del experimento**\n\nSupongamos que este biólogo toma una **muestra de 3 plantas** y procede de la siguiente manera:\n\na) Toma al azar una primera planta y la clasifica de acuerdo con si tiene floración o no.  \nb) Repone la planta previamente seleccionada, selecciona una segunda planta de manera aleatoria y la clasifica de acuerdo con si presenta floración o no.  \nc) Procede de la misma manera que en el inciso b) con la tercera selección.\n\nCada vez que el biólogo observa una planta seleccionada, está realizando un **experimento de tipo Bernoulli**.\n\n\n\n**Condiciones del experimento**\n\nReplanteando los incisos anteriores:\n\n- Se realiza un experimento tipo Bernoulli.  \n- El resultado se clasifica en una de dos categorías mutuamente excluyentes: éxito o fracaso.  \n- La probabilidad de éxito, denotada por $p$, **permanece constante** de prueba a prueba.  \n- El experimento se realiza un número fijo de veces $n = 3$, bajo las mismas condiciones.\n\n\n\n**Variable aleatoria binomial**\n\nCuando un experimento cumple las condiciones anteriores y la variable aleatoria de interés se define como:\n\n> la **cantidad de veces que se presenta uno de los dos resultados posibles**, generalmente denominado *éxito*,\n\nse obtiene una **variable aleatoria discreta con distribución binomial**.\n\nUna variable aleatoria binomial se define como el número de éxitos observados en una serie finita de repeticiones independientes de un experimento Bernoulli.\n\n\n\n**Definición formal del ejemplo**\n\nVolviendo al ejemplo del biólogo:\n\n- $F$: la planta tiene flores  \n- $F^c$: la planta no tiene flores  \n\nDefinimos la variable aleatoria:\n\n$$\nX = \\text{Número de plantas con flores (éxitos) en } n = 3 \\text{ repeticiones}\n$$\n\n\n\n**Resultados posibles**\n\nEn la tabla siguiente se muestran los resultados posibles tras realizar **tres extracciones con reemplazo**.\n\n**Tabla 12. Extracciones con reemplazo**\n\n| X   | F | Fᶜ |\n|-----|-----|------|\n| 3   | 3 | 0 |\n| 2 | 2 | 1 |\n| 1 | 1 | 2 |\n| 0 | 0 | 3 |\n\nEn la columna $F$ (con flores), el primer renglón indica que se obtuvieron **3 plantas con flores** y, por tanto, **0 plantas sin flores**.\n\nPor ejemplo, cuando $X = 3$, el resultado observado es:\n\n$$\nFFF\n$$\n\n\n\n**Cálculo de probabilidades**\n\nDado que los ensayos son independientes, se tiene:\n\n$$\nP(FFF) = P(F \\cap F \\cap F) = P(F)P(F)P(F)\n$$\n\nDenotemos:\n\n- $p = P(F)$: probabilidad de éxito  \n- $q = 1 - p$: probabilidad de fracaso  \n\nEntonces:\n\n$$\nP(X = 3) = p^3\n$$\n\n\n\n**Caso $X = 2$**\n\nObtener dos plantas con flores puede ocurrir de las siguientes maneras:\n\n$$\nFF F^c,\\quad F F^c F,\\quad F^c FF\n$$\n\nEstas posibilidades son **mutuamente excluyentes**, por lo que:\n\n$$\n\\begin{aligned}\nP(X = 2) &= P(FF F^c \\cup F F^c F \\cup F^c FF) \\\\\n&= p p q + p q p + q p p \\\\\n&= 3p^2 q\n\\end{aligned}\n$$\n\n\n**Caso $X = 1$**\n\nDe manera análoga:\n\n$$\n\\begin{aligned}\nP(X = 1) &= P(F^c F^c F \\cup F^c F F^c \\cup F F^c F^c) \\\\\n&= q q p + q p q + p q q \\\\\n&= 3p q^2\n\\end{aligned}\n$$\n\n\n**Caso $X = 0$**\n\n$$\nP(X = 0) = P(F^c F^c F^c) = q^3\n$$\n\n\n\n*Síntesis de probabilidades*\n\n**Tabla 13. Probabilidades para los valores de $X$**\n\n| $x$ | $P(X = x)$ |\n|-----:|-------------:|\n| 3 | $p^3$ |\n| 2 | $3p^2q$ |\n| 1 | $3pq^2$ |\n| 0 | $q^3$ |\n| **Suma** | **1** |\n\nLa suma de las probabilidades es igual a 1, lo cual confirma que $P(X)$ es una **función masa de probabilidad**.\n\n\n\n**Función masa de probabilidad binomial**\n\nPara el ejemplo considerado, la función masa de probabilidad es:\n\n$$\nP(X = x) = \\binom{3}{x} p^x q^{3-x}, \\quad x = 0,1,2,3\n$$\n\nPor ejemplo:\n\n$$\nP(X = 2) = \\binom{3}{2} p^2 q\n$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/unnamed-chunk-2-1.png)\n:::\n:::\n\n\nLa **distribución binomial** modela el número de éxitos que ocurren al repetir un experimento de Bernoulli un número fijo de veces, bajo las siguientes condiciones:\n\n- Cada ensayo tiene solo dos posibles resultados: éxito o fracaso.\n- La probabilidad de éxito es constante e igual a $p$.\n- Los ensayos son independientes entre sí.\n\n\n\n**Estructura de la función masa de probabilidad**\n\nLa función masa de probabilidad de una variable aleatoria binomial se compone de dos partes fundamentales.\n\n**Término probabilístico $p^x q^{n-x}$**\n\nEste término representa la probabilidad de una **secuencia específica** de resultados que contiene:\n\n- $x$ éxitos, cada uno con probabilidad $p$\n- $n-x$ fracasos, cada uno con probabilidad $q = 1-p$\n\nPor ejemplo, para el evento $P(X = 2)$ con $n = 3$, se consideran secuencias con dos éxitos y un fracaso, lo que se expresa como:\n\n$$\np^2 q\n$$\n\n**Coeficiente binomial**\n\nEl coeficiente binomial\n\n$$\n\\binom{n}{x} = \\frac{n!}{x!(n-x)!}\n$$\n\nindica el número de formas mutuamente excluyentes en que pueden ordenarse los éxitos y fracasos.\n\nPara $n = 3$ y $x = 2$:\n\n$$\n\\binom{3}{2} = 3\n$$\n\nLas secuencias posibles son:\n\n- $EFF$\n- $FEF$\n- $FFE$\n\nPor tanto:\n\n$$\nP(X = 2) = \\binom{3}{2} p^2 q = 3p^2 q\n$$\n\nEsto coincide con:\n\n$$\n\\begin{aligned}\nP(X=2) &= P(EFF \\cup FEF \\cup FFE) \\\\\n&= P(EFF)+P(FEF)+P(FFE) \\\\\n&= pqp + qpp + ppq \\\\\n&= 3p^2 q\n\\end{aligned}\n$$\n\n\n**Ejemplo 1**\n\nSupóngase que la probabilidad de encontrar una planta con flores es:\n\n$$\np = \\frac{2}{3}, \\qquad q = \\frac{1}{3}\n$$\n\nLa variable aleatoria $X$ representa el número de plantas con flores en $n = 3$ observaciones.\n\n**Tabla 14. Función masa de probabilidad**\n\n| $x$ | $P(X=x)$ | Aproximación |\n|---|---|---|\n| 0 | $(1/3)^3 = 1/27$ | 0.037 |\n| 1 | $3(2/3)(1/3)^2 = 2/9$ | 0.222 |\n| 2 | $3(2/3)^2(1/3) = 4/9$ | 0.444 |\n| 3 | $(2/3)^3 = 8/27$ | 0.296 |\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/unnamed-chunk-3-1.png)\n:::\n\n```\n#>   x    P_X    F_X\n#> 1 0 0.2725 0.2725\n#> 2 1 0.3847 0.6572\n#> 3 2 0.2376 0.8948\n#> 4 3 0.0839 0.9786\n#> 5 4 0.0185 0.9971\n#> 6 5 0.0026 0.9998\n#> 7 6 0.0002 1.0000\n#> 8 7 0.0000 1.0000\n#> 9 8 0.0000 1.0000\n```\n\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/unnamed-chunk-3-2.png)\n:::\n\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/unnamed-chunk-3-3.png)\n:::\n:::\n\n\n### Ejemplos adicionales: Distribución Binomial\n\n::: {.callout-tip icon=false}\n## Ejemplo: Ventas por teléfono\n\nUna compañía de ventas por teléfono indica que de cada 11 llamadas realizadas, 3 resultan en ventas. Con base en esto, defina $p = 3/11 \\approx 0.2727$. Se realiza una campaña con $n = 10$ llamadas.\n\n**Preguntas:**\n\n1. ¿Cuál es la probabilidad de que exactamente 6 resulten en ventas?\n2. ¿Cuál es la probabilidad de que ninguna llamada resulte en venta?\n3. ¿Qué probabilidad hay de realizar a lo más 5 ventas?\n\n**Solución en R:**\n\n\n::: {.cell}\n\n```\n#> P(X = 6) = 0.02418\n#> P(X = 0) = 0.0414\n#> P(X <= 5) = 0.96985\n```\n\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/binom-ventas-1.png)\n:::\n:::\n\n\nLos resultados muestran que la probabilidad de exactamente 6 ventas es baja dado que $p < 0.3$, mientras que obtener cero ventas, aunque posible, también es poco probable con $n=10$ llamadas.\n\n:::\n\n## Distribución Hipergeométrica {#sec-hipergeometrica}\n\nLa **distribución hipergeométrica** surge en situaciones experimentales donde se extraen elementos de una **población finita**, sin reemplazo, y cada elemento puede clasificarse en una de **dos categorías mutuamente excluyentes**, denominadas **éxito** y **fracaso**.\n\nEn la práctica, la mayoría de los muestreos reales se realizan sin reemplazo, ya que seleccionar un mismo individuo varias veces carece de sentido. Sin embargo, cuando el tamaño de la muestra es **muy pequeño en relación con el tamaño de la población**, el efecto de no reemplazar resulta despreciable y el experimento puede aproximarse mediante un **modelo binomial**.\n\n\n\n**Aproximación binomial en poblaciones grandes**\n\nSupóngase que se extrae una muestra de tamaño\n\n$$\nn = 100\n$$\n\nde una población de\n\n$$\nN = 1\\,000\\,000\n$$\n\nhabitantes, de los cuales 600 000 son varones.\n\nLa probabilidad de que el primer individuo extraído sea varón es:\n\n$$\n\\frac{600\\,000}{1\\,000\\,000} = 0.60\n$$\n\nLa probabilidad de que el segundo individuo sea varón es:\n\n$$\n\\frac{599\\,999}{999\\,999} \\approx 0.5999\n$$\n\nLa probabilidad de que el tercero sea varón es:\n\n$$\n\\frac{599\\,998}{999\\,998} \\approx 0.5999\n$$\n\n::: {.callout-note icon=false}\n## Observación\nLas probabilidades prácticamente no varían en cada extracción. En este caso es razonable adoptar un modelo de muestreo con reemplazo, es decir, una **variable aleatoria binomial**.\n\n:::\n\n\n\n**Muestreo sin reemplazo: necesidad del modelo hipergeométrico**\n\nConsidérese ahora una cooperativa escolar con 20 personas, de las cuales 14 son mujeres. Se desea seleccionar un grupo de 5 personas.\n\nDefinimos la variable aleatoria:\n\n$$\nX = \\text{número de mujeres seleccionadas}\n$$\n\nLas probabilidades condicionadas son:\n\n- Primera mujer: $14/20 = 0.70$\n- Segunda mujer: $13/19 \\approx 0.684$\n- Tercera mujer: $12/18 = 0.67$\n\n::: {.callout-note icon=false}\n## Observación\nLa probabilidad de éxito cambia significativamente en cada extracción. Por tanto, **no es adecuado utilizar un modelo binomial** y se debe emplear la **distribución hipergeométrica**.\n\n:::\n\n\n\n**Notación**\n\n- $N$: tamaño de la población  \n- $K$: número de éxitos en la población  \n- $N-K$: número de fracasos en la población  \n- $n$: tamaño de la muestra  \n- $X$: número de éxitos en la muestra  \n- $n-X$: número de fracasos en la muestra  \n\n\n\n**Función masa de probabilidad**\n\nLa función masa de probabilidad de una variable aleatoria hipergeométrica es:\n\n$$\nP(X=x)=\\frac{\\binom{K}{x}\\binom{N-K}{n-x}}{\\binom{N}{n}},\n\\quad x = 0,1,\\dots,n\n$$\n\nLa función de distribución acumulada es:\n\n$$\nF(X \\le a) = \\sum_{x=0}^{a} P(X=x)\n$$\n\n\n\n**Esperanza y varianza**\n\nLa esperanza matemática es:\n\n$$\nE[X] = n\\frac{K}{N}\n$$\n\nLa varianza está dada por:\n\n$$\n\\text{Var}(X) = n\\frac{K}{N}\\frac{N-K}{N}\\frac{N-n}{N-1}\n= npq\\frac{N-n}{N-1}\n$$\n\n**Anotación:**  \nEl factor $\\frac{N-n}{N-1}$ se denomina **factor de corrección para poblaciones finitas**.\n\n\n\n**Ejemplo 1**\n\nUn estudio contable cuenta con 18 secretarias:\n\n- 10 con menos de 6 años de antigüedad  \n- 8 con más de 6 años de antigüedad  \n\nSe seleccionan 4 secretarias al azar.\n\nDatos:\n\n- $N = 18$\n- $K = 10$\n- $n = 4$\n\nSe desea calcular:\n\n$$\nP(X = 2)\n$$\n\n$$\nP(X=2) = \\frac{\\binom{10}{2}\\binom{8}{2}}{\\binom{18}{4}} \\approx 0.412\n$$\n\nLa probabilidad de que haya **a lo más dos** secretarias con menos de 6 años es:\n\n$$\nP(X \\le 2) = 0.023 + 0.183 + 0.412 \\approx 0.618\n$$\n\nEl valor esperado es:\n\n$$\nE[X] = 4\\frac{10}{18} \\approx 2.22 \\approx 2\n$$\n\n\n\n**Ejemplo 2**\n\nUn viajero transporta:\n\n- 6 tabletas de narcóticos  \n- 9 píldoras de vitamina  \n\nUn oficial selecciona 3 tabletas al azar.\n\nDatos\n\n- $N = 15$\n- $K = 6$\n- $n = 3$\n\nLa probabilidad de arresto es:\n\n$$\nP(X \\ge 1) = 0.816\n$$\n\nLa probabilidad de no arresto es:\n\n$$\nP(X = 0) = 0.185\n$$\n\nEl valor esperado es:\n\n$$\nE[X] = 3\\frac{6}{15} = 1.2 \\approx 1\n$$\n\n\n\n:::\n\n\n::: {.callout-tip icon=false}\n## Ejemplo 3 (resuelto paso a paso)\n\nUna caja contiene **20 componentes electrónicos**: 12 en buen estado y 8 defectuosos. Se seleccionan **5 componentes al azar sin reemplazo**. Sea $X$ = número de defectuosos en la muestra.\n\n**Identificación del modelo:** $X \\sim \\text{Hipergeom}(N=20,\\; K=8,\\; n=5)$\n\n**a) Calcule $P(X = 2)$**\n\n$$\nP(X=2) = \\frac{\\binom{8}{2}\\binom{12}{3}}{\\binom{20}{5}}\n$$\n\nCalculamos cada combinatoria:\n\n$$\n\\binom{8}{2} = \\frac{8!}{2!\\,6!} = \\frac{8 \\cdot 7}{2} = 28\n$$\n\n$$\n\\binom{12}{3} = \\frac{12!}{3!\\,9!} = \\frac{12 \\cdot 11 \\cdot 10}{6} = 220\n$$\n\n$$\n\\binom{20}{5} = \\frac{20!}{5!\\,15!} = \\frac{20 \\cdot 19 \\cdot 18 \\cdot 17 \\cdot 16}{120} = 15{,}504\n$$\n\nPor lo tanto:\n\n$$\nP(X=2) = \\frac{28 \\cdot 220}{15{,}504} = \\frac{6{,}160}{15{,}504} \\approx 0.3973\n$$\n\n**b) $P(X \\leq 1)$ — obtener a lo más 1 defectuoso**\n\n$$\nP(X=0) = \\frac{\\binom{8}{0}\\binom{12}{5}}{\\binom{20}{5}} = \\frac{1 \\cdot 792}{15{,}504} \\approx 0.0511\n$$\n\n$$\nP(X=1) = \\frac{\\binom{8}{1}\\binom{12}{4}}{\\binom{20}{5}} = \\frac{8 \\cdot 495}{15{,}504} = \\frac{3{,}960}{15{,}504} \\approx 0.2554\n$$\n\n$$\nP(X \\leq 1) = P(X=0) + P(X=1) = 0.0511 + 0.2554 = 0.3065\n$$\n\n**c) Esperanza y varianza**\n\n$$\nE[X] = n\\frac{K}{N} = 5 \\cdot \\frac{8}{20} = 2\n$$\n\n$$\n\\text{Var}(X) = n\\frac{K}{N}\\frac{N-K}{N}\\frac{N-n}{N-1}\n= 5 \\cdot \\frac{8}{20} \\cdot \\frac{12}{20} \\cdot \\frac{15}{19}\n\\approx 0.947\n$$\n\n**Interpretación:** En promedio esperamos 2 defectuosos en la muestra, con una desviación estándar de $\\sqrt{0.947} \\approx 0.97$.\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/unnamed-chunk-4-1.png)\n:::\n:::\n\n\n### Ejemplos adicionales: Distribución Hipergeométrica\n\n::: {.callout-tip icon=false}\n## Ejemplo: Inspección de focos (Magín Zúñiga)\n\nUna fábrica de focos tiene información histórica de que en cada lote de $N = 380$ focos, $K = 15$ son defectuosos. Un inspector toma una muestra sin reemplazo de $n = 18$ focos.\n\nSea $X$ = número de focos defectuosos en la muestra. Entonces $X \\sim \\text{Hipergeom}(380, 15, 18)$.\n\n\n::: {.cell}\n\n```\n#> FMP de X ~ Hipergeom(380, 15, 18):\n#> x = 0: P(X = 0) = 0.000000\n#>  x = 1: P(X = 1) = 0.000000\n#>  x = 2: P(X = 2) = 0.000000\n#>  x = 3: P(X = 3) = 0.000000\n#>  x = 4: P(X = 4) = 0.000000\n#>  x = 5: P(X = 5) = 0.000000\n#>  x = 6: P(X = 6) = 0.000000\n#>  x = 7: P(X = 7) = 0.000000\n#>  x = 8: P(X = 8) = 0.000000\n#>  x = 9: P(X = 9) = 0.000000\n#>  x = 10: P(X = 10) = 0.000000\n#>  x = 11: P(X = 11) = 0.000001\n#>  x = 12: P(X = 12) = 0.000017\n#>  x = 13: P(X = 13) = 0.000280\n#>  x = 14: P(X = 14) = 0.003199\n#>  x = 15: P(X = 15) = 0.024953\n#> \n#> E[X] = n*K/N = 18 * 15 / 380 = 0.7105 focos defectuosos esperados\n```\n\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/hiper-focos-1.png)\n:::\n:::\n\n\nSe espera encontrar menos de 1 foco defectuoso en promedio ($E[X] \\approx 0.71$), lo que refleja la baja tasa de defectos del proceso (15/380 ≈ 3.9%).\n\n:::\n\n::: {.callout-tip icon=false}\n## Ejemplo: Representantes políticos\n\nEn una convención política nacional, un estado tiene 20 representantes, de los cuales 15 apoyan al candidato A y 5 apoyan al candidato B. Se seleccionan aleatoriamente 4 representantes sin reemplazo.\n\nSea $X$ = número de representantes que apoyan al candidato A. Entonces $N=20$, $K=15$, $n=4$.\n\n**Preguntas:**\n\n1. ¿Cuál es la probabilidad de que por lo menos 2 apoyen al candidato A?\n2. ¿Cuál es la probabilidad de que ninguno apoye al candidato A?\n3. ¿Cuál es la probabilidad de que ninguno apoye al candidato B?\n\n**Solución en R:**\n\n\n::: {.cell}\n\n```\n#> P(X >= 2) = 0.2487\n#> P(X = 0) = 0.2817\n#> P(X = 4) = 0.001\n```\n\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/hiper-politicos-1.png)\n:::\n:::\n\n\nCon $K/N = 0.75$ (75% apoyan A), la probabilidad de que ninguno de los 4 seleccionados apoye a A es prácticamente cero.\n\n:::\n\n## Distribución Poisson {#sec-poisson}\n\n\nLa **variable aleatoria Poisson** puede estudiarse desde dos enfoques fundamentales:\n\n1. **Como el límite de la distribución binomial**, cuando el tamaño de la muestra es grande y la probabilidad de éxito es pequeña.\n2. **Como un modelo para el conteo de eventos** que ocurren en un intervalo fijo de tiempo o en una región determinada del espacio.\n\nAmbos enfoques serán analizados de manera progresiva y mediante ejemplos ilustrativos.\n\n\n\n**Caso 1: La distribución Poisson como límite de la binomial**\n\nEn los ejemplos clásicos de la distribución binomial se suelen considerar tamaños muestrales pequeños, como 10 insectos o 12 pacientes, donde cada unidad experimental puede clasificarse en una de dos categorías mutuamente excluyentes (éxito o fracaso).\n\nSin embargo, en muchos contextos reales:\n- el tamaño de la muestra es grande,\n- la probabilidad de éxito es pequeña,\n\npor lo que el uso directo de la distribución binomial se vuelve computacionalmente poco práctico. En estos casos, la **distribución Poisson** ofrece una excelente aproximación.\n\n**Función masa de probabilidad**\n\nSea $X$ una variable aleatoria Poisson con parámetro $\\lambda > 0$. Su función masa de probabilidad está dada por:\n\n$$\nP(X = x) = \\frac{e^{-\\lambda}\\lambda^x}{x!}, \\quad x = 0,1,2,\\ldots\n$$\n\ndonde $e \\approx 2.71828$ es la base del logaritmo natural.\n\nLa función de distribución acumulada es:\n\n$$\nF(a) = P(X \\le a) = \\sum_{x=0}^{a} P(X=x)\n$$\n\n**Relación con la distribución binomial**\n\nLa distribución binomial $\\text{Bin}(n,p)$ puede aproximarse por una distribución Poisson cuando:\n\n- $n \\to \\infty$,\n- $p \\to 0$,\n- $\\lambda = np$ permanece constante.\n\nEn la práctica, esta aproximación es adecuada cuando $np < 5$.\n\n::: {.callout-note icon=false}\n## Observación\nEn la distribución Poisson, el parámetro $\\lambda$ representa simultáneamente:\n\n- la **esperanza matemática**,\n- la **varianza** de la variable aleatoria.\n\n:::\n\n$$\nE[X] = \\text{Var}(X) = \\lambda\n$$\n\n\n\n**Ejemplo 1**\n\nUn agrónomo sabe que el **2% de las semillas** de cierta especie no germina. Se venden **100 semillas** a un agricultor. El comprador solicitará reembolso si **al menos 6 semillas no germinan**.\n\n**Definición del modelo**\n\nSea $X$ el número de semillas no germinadas.\n\n$$\n\\lambda = np = 100(0.02) = 2\n$$\n\nPor tanto, $X \\sim \\text{Poisson}(2)$.\n\nLa probabilidad de interés es:\n\n$$\nP(X \\ge 6) = 1 - P(X \\le 5)\n$$\n\nUsando tablas de Poisson:\n\n$$\nP(X \\le 5) = 0.9834\n$$\n\n$$\nP(X \\ge 6) = 1 - 0.9834 = 0.0166\n$$\n\n**Conclusión:**  \nLa probabilidad de que el agricultor solicite el reembolso es **1.66%**, lo que indica una baja probabilidad de reclamación.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/unnamed-chunk-5-1.png)\n:::\n:::\n\n\n**Caso 2: La distribución Poisson como modelo de conteo**\n\nEn este enfoque, la variable aleatoria Poisson representa el número de eventos que ocurren por unidad de tiempo o espacio.\n\nCondiciones del modelo Poisson\n\nUna variable aleatoria Poisson es adecuada cuando:\n\na) Los eventos que ocurren en intervalos disjuntos son independientes.\nb) La probabilidad de ocurrencia en un intervalo muy pequeño es proporcional a su longitud (o área).\nc) La probabilidad de que ocurran dos o más eventos en un intervalo muy pequeño es despreciable.\n\nEjemplo espacial: Distribución de células de levadura\n\nSe estudia la distribución de células de levadura en 400 cuadrículas de un hemacitómetro. Los datos observados se resumen en la siguiente tabla:\n\n**Tabla de distribución de las células de levadura**\n\nSe estudia la distribución del número de células de levadura observadas en 400 cuadrículas de un hemacitómetro.  \nLa siguiente tabla resume las frecuencias observadas.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Distribución de frecuencias de células de levadura por cuadrícula\n\n| Células.por.cuadrícula| Frecuencia.observada| Frecuencia.relativa|\n|----------------------:|--------------------:|-------------------:|\n|                      0|                   75|              0.1875|\n|                      1|                  103|              0.2575|\n|                      2|                  121|              0.3025|\n|                      3|                   54|              0.1350|\n|                      4|                   30|              0.0750|\n|                      5|                   13|              0.0325|\n|                      6|                    2|              0.0050|\n|                      7|                    1|              0.0025|\n|                      8|                    0|              0.0000|\n|                      9|                    1|              0.0025|\n\n\n:::\n\n```\n#> [1] 1.8\n```\n\n::: {.cell-output-display}\n\n\nTable: Distribución Poisson teórica con λ = 1.8\n\n| Células.por.cuadrícula| Probabilidad.Poisson|\n|----------------------:|--------------------:|\n|                      0|               0.1653|\n|                      1|               0.2975|\n|                      2|               0.2678|\n|                      3|               0.1607|\n|                      4|               0.0723|\n|                      5|               0.0260|\n|                      6|               0.0078|\n|                      7|               0.0020|\n|                      8|               0.0005|\n|                      9|               0.0001|\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/unnamed-chunk-7-1.png)\n:::\n:::\n\n\n### Ejemplos adicionales: Distribución Poisson\n\n::: {.callout-tip icon=false}\n## Ejemplo: Infracciones de parquímetro\n\nEl número de infracciones expedidas por el lector de un parquímetro, por violaciones de estacionamiento, puede modelarse mediante un proceso Poisson con una tasa de $\\lambda = 5$ infracciones por hora.\n\n**Preguntas:**\n\n1. ¿Cuál es la probabilidad de que exactamente 5 infracciones se expidan durante una hora?\n2. ¿Cuál es la probabilidad de que se expidan al menos 3 infracciones en una hora?\n3. ¿Cuántas infracciones se esperan en un periodo de 45 minutos?\n\n**Solución en R:**\n\n\n::: {.cell}\n\n```\n#> P(X = 5) = 0.17547\n#> P(X >= 3) = 0.87535\n#> E[X en 45 min] = lambda' = 3.75 infracciones\n```\n\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/poisson-infracciones-1.png)\n:::\n:::\n\n\n:::\n\n::: {.callout-tip icon=false}\n## Ejemplo: Fuente radiactiva\n\nUna fuente radiactiva emite partículas según una distribución Poisson con media $\\lambda = 10$ partículas por minuto.\n\n**Preguntas:**\n\n1. Probabilidad de 5 partículas en un minuto.\n2. Probabilidad de 0 partículas en un minuto.\n3. Probabilidad de más de 5 partículas en un minuto.\n4. Probabilidad de a lo más 30 partículas en 5 minutos.\n\n**Solución en R:**\n\n\n::: {.cell}\n\n```\n#> P(X = 5)  = 0.03783\n#> P(X = 0)  = 4.5400e-05\n#> P(X > 5)  = 0.93291\n#> P(Y <= 30) en 5 min = 0.001594\n```\n:::\n\n\nLos valores confirman que con $\\lambda = 10$, obtener 0 partículas es un evento extremadamente improbable ($\\approx 4.5 \\times 10^{-5}$), mientras que más de 5 partículas ocurre con probabilidad 0.933.\n\n:::\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. Una máquina produce piezas defectuosas con probabilidad $p=0.04$. Si se inspeccionan 10 piezas, calcule la probabilidad de encontrar exactamente 2 defectuosas usando la distribución Binomial.\n2. De un lote de 25 artículos, 5 son defectuosos. Si se seleccionan 4 artículos sin reemplazo, calcule la probabilidad de obtener al menos un defectuoso usando la distribución Hipergeométrica.\n3. El número de accidentes en una intersección sigue una distribución Poisson con una media de 1.5 accidentes por semana. Calcule la probabilidad de que ocurran más de 2 accidentes en una semana dada.\n4. Una ruleta de casino tiene números del 0 al 36. Se considera éxito que caiga el número elegido. Si se juega 15 veces: (a) determine $p$; (b) calcule $P(X < 3)$; (c) obtenga $E[X]$ y $\\text{Var}(X)$.\n\n:::\n\n## Material complementario: distribuciones adicionales\n\nEsta sección presenta, a partir de los apuntes del Prof. Magín Zúñiga Estrada, dos familias discretas adicionales (Geométrica y Binomial Negativa), así como las distribuciones conjuntas para variables discretas.\n\n### Distribución Geométrica {#sec-geometrica}\n\nLa **distribución geométrica** modela el número de fracasos que ocurren *antes* de obtener el primer éxito en ensayos Bernoulli independientes, cada uno con probabilidad de éxito $p$. Se denota $X \\sim \\text{geo}(p)$.\n\n:::: {.content-visible when-format=\"html\"}\n[📖 Magín Zúñiga Estrada]{.fuente-badge .fuente-magin}\n\n::::\n\n::: {.callout-tip icon=false}\n## Definición formal: distribución Geométrica\n\nUna variable aleatoria $X$ tiene distribución **geométrica** con parámetro $p$ si modela el número de ensayos *antes* de obtener el primer éxito (probabilidad de éxito $p$, ensayos independientes). Se denota $X \\sim \\text{geo}(p)$.\n\nSu pmf en forma tabular:\n\n| $k$ | $0$ | $1$ | $2$ | $\\cdots$ | $k$ |\n|-----|-----|-----|-----|-----------|-----|\n| $p(k)$ | $p$ | $(1-p)\\,p$ | $(1-p)^2 p$ | $\\cdots$ | $(1-p)^k p$ |\n\n**Nota sobre nomenclatura:** hablar de \"éxito\" y \"fracaso\" puede resultar ambiguo — a veces interesa el número de éxitos antes del primer fracaso y a veces lo contrario. Para evitar confusión, se recomienda reformular en términos concretos: por ejemplo, *\"número de cruces antes de la primera cara\"*.\n\n:::\n\n**Función masa de probabilidad y momentos:**\n\n$$p(k;\\,p) = (1-p)^k\\,p, \\quad k = 0, 1, 2, \\ldots$$\n\n$$E[X] = \\frac{1-p}{p}, \\qquad \\text{Var}(X) = \\frac{1-p}{p^2}$$\n\nUna propiedad importante es la **falta de memoria**: dado que han ocurrido $k$ fracasos, la distribución de los fracasos adicionales hasta el primer éxito sigue siendo $\\text{geo}(p)$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/geom-plot-1.png){fig-align='center'}\n:::\n:::\n\n\n::: {.callout-tip icon=false}\n## Ejemplo: Planificación familiar (Magín Zúñiga)\n\nLos habitantes de una isla tienen hijos hasta que nace la primera niña (cada embarazo: niña con $p = 0.5$, independiente). Sea $X$ = número de niños (varones) antes de la primera niña. Entonces $X \\sim \\text{geo}(0.5)$.\n\n\n::: {.cell}\n\n```\n#> k  |  P(X=k)\n#> 0  |  0.50000\n#> 1  |  0.25000\n#> 2  |  0.12500\n#> 3  |  0.06250\n#> 4  |  0.03125\n#> 5  |  0.01562\n#> 6  |  0.00781\n#> 7  |  0.00391\n#> 8  |  0.00195\n#> \n#> E[X] = 1 niños varones en promedio antes de la primera niña\n```\n:::\n\n\nAunque cada familia puede tener muchos niños, la razón niños/niñas en la isla sigue siendo 1:1 en promedio.\n\n:::\n\n### Distribución Binomial Negativa {#sec-binomial-negativa}\n\nLa **distribución binomial negativa** generaliza la geométrica: modela el número de fracasos $X$ antes de obtener exactamente $r$ éxitos. Se denota $X \\sim \\text{NegBin}(r, p)$.\n\n**Función masa de probabilidad:**\n\n$$p(k;\\,r,p) = \\binom{k+r-1}{r-1}(1-p)^k\\,p^r, \\qquad k = 0, 1, 2, \\ldots$$\n\n**Esperanza y varianza:**\n\n$$E[X] = \\frac{r(1-p)}{p}, \\qquad \\text{Var}(X) = \\frac{r(1-p)}{p^2}$$\n\n::: {.callout-note icon=false}\n## Observación\nLa distribución geométrica es el caso $r = 1$: $\\text{Geo}(p) = \\text{NegBin}(1, p)$.\n\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/negbin-plot-1.png){fig-align='center'}\n:::\n:::\n\n\n::: {.callout-tip icon=false}\n## Ejemplo: Call center (Magín Zúñiga)\n\nCada llamada concreta una venta con $p = 0.2$. Sea $X$ el número de rechazos antes de lograr $r = 3$ ventas. $X \\sim \\text{NegBin}(3, 0.2)$.\n\n\n::: {.cell}\n\n```\n#> P(X = 5) = 0.05505\n#> E[X] = r(1-p)/p = 12 rechazos esperados\n#> Var[X] = 60\n```\n\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/negbin-callcenter-1.png)\n:::\n:::\n\n\n:::\n\n::: {.callout-tip icon=false}\n## Ejemplo: Ensayo clínico (Magín Zúñiga)\n\nTratamiento con probabilidad de respuesta positiva $p = 0.30$. Se desea lograr $r = 5$ respuestas positivas. Sea $X \\sim \\text{NegBin}(5, 0.3)$.\n\n**¿Cuál es la probabilidad de exactamente 8 pacientes sin respuesta antes de las 5 positivas?**\n\n$$P(X = 8) = \\binom{12}{4}(0.7)^8(0.3)^5 \\approx 0.0692$$\n\n\n::: {.cell}\n\n```\n#> P(X = 8) = 0.06934\n#> E[X] = 11.66667\n```\n:::\n\n\n:::\n\n::: {.callout-tip icon=false}\n## Ejercicio: Educación (Magín Zúñiga)\n\nUn profesor aplica un examen de opción múltiple. Cada pregunta se responde correctamente con probabilidad $p = 0.4$ (ensayos independientes). Se busca modelar el número de respuestas incorrectas antes de que un estudiante logre $r = 3$ correctas.\n\n**¿Cuál es la probabilidad de exactamente 5 respuestas incorrectas antes de las 3 correctas?**\n\nSea $X \\sim \\text{NegBin}(r=3,\\, p=0.4)$:\n\n$$P(X=5) = \\binom{7}{2}(0.6)^5(0.4)^3 \\approx 0.1045$$\n\n\n::: {.cell}\n\n```\n#> P(X = 5) = 0.10451\n#> E[X] = r(1-p)/p = 4.5\n#> Var[X] = 11.25\n```\n:::\n\n\n:::\n\n::: {.callout-tip icon=false}\n## Ejercicio: Ventas en call center (Magín Zúñiga)\n\nUn agente tiene probabilidad $p = 0.15$ de concretar una venta por llamada. Se modela el número de llamadas sin venta antes de lograr $r = 4$ ventas.\n\n**¿Cuál es la probabilidad de exactamente 10 llamadas sin venta antes de las 4 ventas?**\n\nSea $X \\sim \\text{NegBin}(r=4,\\, p=0.15)$:\n\n$$P(X=10) = \\binom{13}{3}(0.85)^{10}(0.15)^4 \\approx 0.0285$$\n\n\n::: {.cell}\n\n```\n#> P(X = 10) = 0.0285\n#> E[X] = r(1-p)/p = 22.66667\n#> Var[X] = 151.1111\n```\n:::\n\n\n:::\n\n### Distribuciones discretas conjuntas\n\nCuando se estudian dos variables aleatorias discretas $X$ e $Y$ simultáneamente, se define la **función de probabilidad conjunta** $p(x, y) = P(X = x,\\; Y = y)$, que satisface:\n\n$$p(x, y) \\ge 0, \\qquad \\sum_x \\sum_y p(x,y) = 1$$\n\nLas **distribuciones marginales** se obtienen:\n$$p_X(x) = \\sum_y p(x, y), \\qquad p_Y(y) = \\sum_x p(x, y)$$\n\n$X$ e $Y$ son **independientes** si y sólo si $p(x, y) = p_X(x)\\cdot p_Y(y)$ para todo $(x, y)$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap02-distribuciones_files/figure-docx/conjunta-suma-dados-1.png){fig-align='center'}\n:::\n\n```\n#> P(S = 7) = 0.1666667\n```\n:::\n\n\n:::: {.content-visible when-format=\"html\"}\n[📖 Magín Zúñiga Estrada]{.fuente-badge .fuente-magin}\n\n::::\n\n::: {.callout-note icon=false}\n## Ejercicios de pdf y cdf (Magín Zúñiga Estrada)\n\n1. **Funciones de densidad.** Muestra que las siguientes son funciones de densidad y demuestra la propiedad de mezcla:\n\n   $$f_1(x) = e^{-x},\\; x>0 \\qquad f_2(x) = 2e^{-2x},\\; x>0$$\n   $$f_3(x) = (\\theta+1)f_1(x) - \\theta f_2(x), \\quad 0 < \\theta < 1$$\n\n   Además, prueba que si $f_1$ y $f_2$ son densidades y $\\theta_1 + \\theta_2 = 1$, entonces $\\theta_1 f_1 + \\theta_2 f_2$ también lo es.\n\n2. **Bolas en cajas.** Se lanzan dos bolas en cuatro cajas, cada bola con igual probabilidad de caer en cualquier caja. Sea $X$ el número de bolas en la primera caja. Encuentra la cdf y la pmf de $X$.\n\n3. **Moneda hasta cara.** Se lanza una moneda justa hasta que sale cara. Sea $X$ el número de lanzamientos necesarios. Encuentra la pmf de $X$.\n\n4. **Juego de monedas.** El jugador A tiene dos monedas; B tiene una. Emparejan monedas hasta que uno de ellos reúne las tres. Sea $X$ el número de rondas necesarias. ¿Cuál es la pmf de $X$?\n\n5. **Variable aleatoria continua (pdf por partes).** Sea $X$ continua con:\n\n   $$f(x) = \\begin{cases} 3/4 & 0 \\le x \\le 1 \\\\ 1/4 & 2 \\le x \\le 3 \\\\ 0 & \\text{d.o.m.} \\end{cases}$$\n\n   Dibuja $f(x)$ y determina la función de distribución acumulada $F(x)$.\n\n6. **Puntuación en examen.** La puntuación $X$ de un estudiante sigue la distribución triangular:\n\n   $$f(x) = \\begin{cases} 4x & 0 \\le x \\le 1/2 \\\\ 4-4x & 1/2 \\le x \\le 1 \\\\ 0 & \\text{d.o.m.} \\end{cases}$$\n\n   El estudiante aprueba si $X \\ge 0.55$.\n\n   a. ¿Cuál es la probabilidad de reprobar?\n   b. ¿Cuál es la puntuación mediana?\n\n:::\n\n\n\n## Resumen del capítulo\n\n| Distribución | Parámetros | $E[X]$ | $\\text{Var}(X)$ | Uso típico |\n|:-------------|:----------:|:------:|:--------:|:-----------|\n| Uniforme discreta | $a, b$ | $(a+b)/2$ | $(b-a)(b-a+2)/12$ | Equiprobabilidad |\n| Bernoulli | $p$ | $p$ | $p(1-p)$ | Ensayo éxito/fracaso |\n| Binomial | $n, p$ | $np$ | $np(1-p)$ | Conteo de éxitos en $n$ ensayos |\n| Hipergeométrica | $N, K, n$ | $nK/N$ | $\\frac{nK(N-K)}{N^2}\\frac{N-n}{N-1}$ | Muestreo sin reemplazo |\n| Poisson | $\\lambda$ | $\\lambda$ | $\\lambda$ | Conteo de eventos raros |\n| Geométrica | $p$ | $(1-p)/p$ | $(1-p)/p^2$ | Ensayos hasta primer éxito |\n| Binomial Negativa | $r, p$ | $r(1-p)/p$ | $r(1-p)/p^2$ | Ensayos hasta $r$-ésimo éxito |\n\n::: {.callout-note icon=false}\n## Criterio de selección del modelo\n\n- Muestreo **con reemplazo** (o población grande): **Binomial**.\n- Muestreo **sin reemplazo** en población finita: **Hipergeométrica**.\n- Eventos raros o conteos en intervalo/espacio: **Poisson**.\n- Ensayos hasta el primer éxito: **Geométrica**.\n- Ensayos hasta el $r$-ésimo éxito: **Binomial Negativa**.\n\n:::\n\n## Conexión con el siguiente capítulo\n\nEn este capítulo modelamos variables que toman valores *contables* (0, 1, 2, ...). Muchos fenómenos reales — tiempos de espera, medidas físicas, proporciones — producen en cambio valores en un continuo. En el siguiente capítulo generalizaremos las ideas de pmf, $E[X]$ y $\\text{Var}(X)$ al mundo continuo, donde la probabilidad se mide como área bajo una curva de densidad, y conoceremos las distribuciones Normal, Exponencial, Gamma y Weibull.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}