{
  "hash": "757d13902dc31274246ebdcadce8767f",
  "result": {
    "engine": "knitr",
    "markdown": "# Distribuciones Muestrales {#cap-inferencia}\n\nEn esta unidad, estudiaremos las distribuciones generadas por características medidas a conjuntos de individuos (muestras). Antes de revisar las distribuciones de muestreo se definen conceptos importantes en la modelación estadística.\n\n::: {.callout-tip icon=false}\n## Objetivos de aprendizaje\n\nAl finalizar este capítulo, el estudiante será capaz de:\n\n- Distinguir entre población y muestra, y entre parámetro y estimador, identificando las propiedades deseables de un buen estimador (insesgamiento, consistencia y eficiencia).\n- Derivar y usar la distribución muestral de $\\bar{X}$, $S^2$ y $\\hat{P}$ para calcular probabilidades sobre estadísticos muestrales.\n- Aplicar las distribuciones $\\chi^2$, $t$ de Student y $F$ de Fisher para resolver problemas de inferencia sobre varianzas y medias.\n- Enunciar el Teorema del Límite Central y aplicarlo para aproximar distribuciones de sumas y promedios de muestras grandes.\n- Implementar pruebas de bondad de ajuste (chi-cuadrada y Kolmogórov-Smirnov) para evaluar si un conjunto de datos proviene de una distribución específica.\n\n:::\n\nEn este capítulo estudiaremos los conceptos básicos de la inferencia estadística: población, muestra aleatoria, parámetros y estimadores. A partir de ahí revisaremos las distribuciones muestrales de los principales estimadores (la media $\\bar{X}$, la varianza $S^2$ y la proporción $\\hat{P}$), así como las distribuciones teóricas asociadas (Chi-cuadrada, $t$ de Student y $F$ de Fisher), que nos permiten calcular probabilidades sobre el comportamiento de las muestras. Cerraremos el capítulo con el Teorema del Límite Central, una de las herramientas más importantes de la estadística inferencial. A lo largo del capítulo se incluyen ejemplos resueltos y ejercicios propuestos para practicar los conceptos.\n\n## Población\n\nUna población es un conjunto de elementos, objetos o seres vivos con características comunes $A$, $B$, $C$, $D$ y no comunes $E$, $F$, $G$ (que varían de un sujeto a otro).\n\nUn ejemplo de un conjunto de $n$ individuos con características similares, en cada individuo $i$, serían aquellos individuos con las siguientes características: \\* $A = \\text{Adultos}$ \\* $B = \\text{Viven en Jalisco}$ \\* $C = \\text{Sanos}$\n\nEn cada individuo $i$ se obtienen las siguientes observaciones o mediciones: $$Y_i = \\{Estatura, Ingreso, Hemoglobina\\}$$\n\nAlgunas características no comunes en los $n$ individuos, es decir, características que varían significativamente del individuo $i$ versus el individuo $j$ ($i \\neq j$) podrían ser: \\* $E$: Grupo sanguíneo \\* $F$: Origen étnico \\* $G$: Tipo de alimentación \\* $H$: Tipo de trabajo \\* $I$: Escolaridad\n\nSupongamos que nos interesa estudiar el “ingreso medio” de la población masculina obrera que labora en la ciudad de Aguascalientes en el sector automotriz, entonces: $$Y_i: \\text{Ingreso mensual}$$\n\nEn este ejemplo la población de interés posee las siguientes características comunes: \\* $A$: Masculino \\* $B$: Obrero \\* $C$: Labora en Aguascalientes \\* $D$: En sector automotriz\n\nPor otra parte, la lista de características no comunes: \\* $E$: Edad \\* $F$: Tipo de contratación \\* $G$: Años de experiencia\n\nSe esperaría que las variables no comunes tengan poca influencia sobre la variable de respuesta: “Ingreso mensual”, que puedan afectar su comportamiento al realizar un estudio, o en su defecto, en el diseño del experimento deben de controlarse adecuadamente, quizás con algún método de estratificación y seguramente en la definición de la población objetivo de interés, utilizando criterios de exclusión y de inclusión.\n\n::: {.callout-note icon=false}\n## Nota\nEn la teoría estadística, la población no solo es el conjunto de individuos u objetos físicos, sino el **conjunto completo de mediciones o respuestas** de interés para el experimentador. Por lo tanto, si nos interesa el ingreso mensual, la población conceptual estaría formada por todos los valores monetarios posibles de ese grupo, más que por los individuos mismos. Los valores numéricos constantes que resumen las características de esta población en su totalidad (como el verdadero ingreso medio $\\mu$ o la varianza del ingreso $\\sigma^2$) reciben el nombre de **parámetros**.\n\n:::\n\n## Muestra aleatoria\n\nSi de una población bajo estudio, digamos con una distribución de probabilidad $P(x; \\theta)$, seleccionamos un elemento al azar y medimos una característica de interés, se generará un dato que \"asumimos\" poseerá las mismas propiedades de la población general.\n\n**Ejemplo didáctico:** Supongamos que analizamos la resistencia a la tensión de ciertos componentes de acero producidos en una fábrica. Asumimos que en la población, la variable \"resistencia\" sigue una distribución normal con parámetros: media $\\mu = 65 \\text{ kg/mm}^2$ y varianza $\\sigma^2 = 4 \\text{ kg/mm}^2$. Cualquier componente que se seleccione al azar de esa población conservará, en términos probabilísticos, las características de la población entera.\n\nUna muestra es una subcolección de observaciones de $n$ individuos o elementos que pertenecen a una población de tamaño $N$ (donde $N \\ge n$).\n\nSi a un componente extraído de la población $P(x; \\theta)$ se le mide su resistencia y resulta ser 66.5 kg/mm², esto se expresa de la siguiente manera: $$x = 66.5 \\text{ kg/mm}^2$$\n\nLa expresión anterior señala que $x$ representa una *medición específica* de la característica en un elemento perteneciente a la población.\n\n¿Es $X$ una variable aleatoria? La respuesta es “sí”, porque si se realiza la medición a otro componente distinto, su valor no necesariamente será el mismo (otra medición posible sería $x = 63.2 \\text{ kg/mm}^2$). Notemos que $x \\in S_X$ (el soporte de la variable) y que su resultado no es constante. Si se obtuviera un gran número de mediciones, el comportamiento de los datos mostraría una regularidad similar al de las variables aleatorias teóricas (Normal [@sec-normal], Uniforme [@sec-uniforme-continua], Poisson [@sec-poisson], etc.). A este valor observado $x$ se le denomina una **realización** de la variable aleatoria $X$.\n\nEn estadística, no se trabaja con un único individuo, sino con una colección o muestra de variables aleatorias asociadas a $n$ elementos. Para que la inferencia estadística sea válida, Wackerly, Mendenhall y Scheaffer establecen que esta recolección debe cumplir con ciertas propiedades matemáticas rigurosas:\n\n> **Muestra aleatoria:** Es un conjunto de variables aleatorias $X_1, X_2, \\dots, X_n$ que son **independientes e idénticamente distribuidas (i.i.d.)**.\n>\n> -   **Idénticamente distribuidas:** Significa que cada elemento de la muestra tiene exactamente la misma función de densidad o masa de probabilidad que la población de la cual proviene.\n> -   **Independientes:** Significa que el resultado de una medición no afecta ni aporta información sobre el resultado de otra medición dentro de la muestra.\n\nPara referirnos a esta muestra teórica de $n$ variables aleatorias se utiliza la notación en mayúsculas: $$X_1, X_2, X_3, \\dots, X_n$$\n\nCuando se obtienen las mediciones reales en el laboratorio o campo (supongamos $n=4$), la *realización de la muestra* de variables aleatorias se escribe con letras minúsculas: $$x_1 = 65.1, \\quad x_2 = 62.8, \\quad x_3 = 67.5, \\quad x_4 = 64.9$$\n\nEn el análisis de datos, se hace uso de estas realizaciones (muestras observadas) para obtener estadísticas descriptivas, ajustar modelos probabilísticos y, posteriormente, extrapolar (inferir) los resultados a la población original.\n\nA partir de una realización de muestra aleatoria (por ejemplo, $n=100$ observaciones de resistencia), podemos construir un histograma. Si la muestra es representativa, este histograma se ajustará bien a la curva de densidad poblacional original.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-docx/muestra_aleatoria-1.png){fig-align='center'}\n:::\n:::\n\n\nComo la realización de la muestra indica que los datos provienen de una variable aleatoria normal, la notación matemática para cada una de las variables aleatorias antes de ser observadas es: $$X_1 \\sim N(\\mu = 65, \\sigma^2 = 4)$$ $$X_2 \\sim N(\\mu = 65, \\sigma^2 = 4)$$ $$\\vdots$$ $$X_n \\sim N(\\mu = 65, \\sigma^2 = 4)$$\n\n*(Nota: El símbolo* $\\sim$ es un operador estadístico que indica \"se distribuye como\").\n\nDado que las variables $X_1, X_2, \\dots, X_n$ provienen de una misma población y son independientes, a la variable aleatoria general $X$ que describe la característica en toda la población se le atribuye este comportamiento fundamental: $$X \\sim N(65, 4)$$\n\n## Estimadores de parámetros\n\nLos seres humanos tenemos características propias que nos definen. Por ejemplo, características anatómicas: tipo de rostro (redondo, alargado), ojos (grandes o pequeños), color de ojos (cafés, negros, etcétera), color de piel (moreno, claro, negro), estatura, etcétera. De manera que al mencionar todas sus características de la persona podremos definirla.\n\nHaciendo una analogía a las características anatómicas que empleamos para describir a una persona, la estadística también tiene sus propios elementos (parámetros) para poder caracterizar a una población.\n\nUn parámetro es una constante (cantidad numérica) propia de una población.\n\nComo tú ya habrás leído en la sección 4.2 de esta lectura, la función de densidad de probabilidad de una variable aleatoria normal queda establecida una vez conocido el valor de la media y la varianza, ambos son sus parámetros. En la práctica es poco común tener información de toda la población, por lo que se vuelve práctico trabajar con muestras. El hecho de trabajar con muestras y no con poblaciones, hace que no se conozca exactamente el valor del parámetro. La manera en que a través de una muestra se pueda estimar el valor de un parámetro de una población es mediante el uso de una función denominada estimador.\n\nUn estimador es una función matemática expresada únicamente en términos de los valores de la muestra empleada (es decir, es un estadístico) con el propósito de estimar un parámetro desconocido de la población.\n\nLa tabla siguiente muestra los parámetros que en esta lectura estudiaremos con sus correspondientes estimadores.\n\n**Ejemplo 1**\n\nSupongamos que una fábrica de componentes electrónicos produce un lote masivo de $N = 10,000$ resistencias eléctricas en un turno. El gerente de calidad está interesado en conocer tres **parámetros** fundamentales de esta población (lote completo):\n\n1.  La **media** de la resistencia eléctrica (en ohmios).\n2.  La **varianza** (para medir qué tan consistente es el proceso de fabricación).\n3.  La **proporción** de resistencias defectuosas (aquellas que no cumplen con los estándares mínimos).\n\nDado que probar las $10,000$ resistencias detendría la producción y sería muy costoso, el gerente decide extraer una muestra aleatoria de $n = 5$ resistencias y aplicar los **estimadores** correspondientes definidos en la Tabla 1.\n\n**Tabla 1. Parámetros, estimadores y estimaciones.**\n\n| Característica | Parámetro | Estimador | Estimación |\n|:---|:---|:---|:---|\n| **Media** | $\\mu = \\frac{\\sum_{i=1}^N X_i}{N}$ | $\\bar{X} = \\frac{\\sum_{i=1}^n X_i}{n}$ | $\\bar{x} = \\frac{\\sum_{i=1}^n x_i}{n}$ |\n| **Varianza** | $\\sigma^2 = \\frac{\\sum_{i=1}^N (X_i - \\mu)^2}{N}$ | $S^2 = \\frac{\\sum_{i=1}^n (X_i - \\bar{X})^2}{n-1}$ | $s^2 = \\frac{\\sum_{i=1}^n (x_i - \\bar{x})^2}{n-1}$ |\n| **Proporción** | $P = \\frac{X}{N}$ | $\\bar{P} = \\frac{X}{n}$ | $\\bar{p} = \\frac{x}{n}$ |\n\n*(Nota: En el caso de la proporción,* $X$ y $x$ en los numeradores representan el conteo de \"éxitos\" o elementos que cumplen la característica de interés en la población y en la muestra, respectivamente).\n\n**Recolección de datos (Realización de la muestra)**\n\nAl medir las $n = 5$ resistencias en el laboratorio, se obtienen los siguientes valores (en ohmios): $$x_1 = 101.2, \\quad x_2 = 98.5, \\quad x_3 = 102.1, \\quad x_4 = 99.0, \\quad x_5 = 99.2$$\n\nAl inspeccionarlas físicamente, el ingeniero determina que la resistencia $x_2$ (98.5 ohmios) está defectuosa porque sus terminales están dobladas. Por lo tanto, en nuestra muestra hay $x = 1$ artículo defectuoso.\n\n**Cálculo de las estimaciones**\n\nAhora procedemos a calcular las **estimaciones** (los valores numéricos fijos) sustituyendo nuestras observaciones en las fórmulas de los estimadores:\n\n**1. Estimación (**$\\bar{x}$): $$\\bar{x} = \\frac{101.2 + 98.5 + 102.1 + 99.0 + 99.2}{5} = \\frac{500.0}{5} = 100.0 \\text{ ohmios}$$ *Conclusión:* Estimamos que la verdadera media poblacional $\\mu$ del lote completo de 10,000 piezas es de aproximadamente 100.0 ohmios.\n\n**2. Estimación (**$s^2$): Primero calculamos las desviaciones al cuadrado de cada dato respecto a la media muestral ($\\bar{x} = 100.0$): \\* $(101.2 - 100.0)^2 = 1.44$ \\* $(98.5 - 100.0)^2 = 2.25$ \\* $(102.1 - 100.0)^2 = 4.41$ \\* $(99.0 - 100.0)^2 = 1.00$ \\* $(99.2 - 100.0)^2 = 0.64$\n\nSuma de cuadrados $= 1.44 + 2.25 + 4.41 + 1.00 + 0.64 = 9.74$\n\n$$s^2 = \\frac{9.74}{5 - 1} = \\frac{9.74}{4} = 2.435 \\text{ ohmios}^2$$ *Conclusión:* Estimamos que la varianza poblacional $\\sigma^2$ del proceso es 2.435 ohmios, por lo tanto el proceso varía en $\\sqrt{s}=\\pm1.5604$ ohmios.\n\n**3. Estimación de (**$\\bar{p}$): Dado que encontramos 1 resistencia defectuosa de las 5 revisadas: $$\\bar{p} = \\frac{1}{5} = 0.20$$ *Conclusión:* Estimamos que el 20% del lote completo de 10,000 resistencias presenta defectos.\n\n**Representación Gráfica del Ejemplo: Muestra vs. Población Estimada**\n\nEl siguiente gráfico superpone las observaciones individuales reales de nuestra muestra pequeña ($n=5$) con la curva de distribución Normal teórica que inferimos para toda la producción ($N=10,000$), usando la media estimada ($\\bar{x} = 100.0$) y la desviación estándar estimada ($s = \\sqrt{2.435} \\approx 1.56$).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-docx/grafica_ejemplo_resistencias-1.png){fig-align='center'}\n:::\n:::\n\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. Una muestra aleatoria de tamaño $n=8$ pesos (en kg) de paquetes de arroz es: 1.02, 0.98, 1.01, 1.00, 0.99, 1.03, 0.97, 1.00. Calcule la estimación de la media $\\bar{x}$ y de la varianza $s^2$.\n2. De un lote de 500 piezas se revisan 20 y se encuentran 3 defectuosas. Calcule la estimación de la proporción de piezas defectuosas $\\bar{p}$ en el lote.\n3. Explique con sus propias palabras la diferencia entre un parámetro y un estimador, y entre un estimador y una estimación.\n\n:::\n\n## Distribución muestral de un estimador\n\nComo ya hemos visto, una vez que se tienen los datos observados de una muestra, se calculan ciertas funciones llamadas estimadores que nos permiten inferir las características de la población estudiada. Los datos son realizaciones de variables aleatorias; por lo tanto, **los estimadores también son variables aleatorias** antes de que la muestra sea extraída. Al ser una variable aleatoria, todo estimador cuenta con una función de densidad o de probabilidad, a la cual llamaremos **distribución muestral del estimador**.\n\nLos estimadores \"aproximan\" a los parámetros poblacionales. Esto quiere decir que, aunque una estimación puntual nunca coincidirá de manera exacta con el parámetro (debido a la variabilidad aleatoria de la muestra), si la muestra fue seleccionada correctamente y es lo suficientemente grande, el resultado tenderá a concentrarse muy cerca del valor real del parámetro.\n\n> **Distribución muestral de un estimador:** Es la distribución teórica de probabilidad de todos los posibles valores que puede tomar un estimador, calculados a partir de todas las muestras posibles de tamaño $n$ extraídas de la misma población.\n\n::: {.callout-caution icon=false}\n## Errores comunes: parámetros y estimadores\n\n**Error 1 — Confundir el parámetro con el estimador.**  \nEl parámetro $\\mu$ (media poblacional) es un número fijo pero desconocido; el estimador $\\bar{X}$ es una *variable aleatoria* que cambia de muestra a muestra. Solo $\\bar{X}$ tiene distribución muestral; $\\mu$ no.\n\n**Error 2 — Dividir por $n$ en lugar de $n-1$ al estimar la varianza.**  \n$s^2 = \\frac{\\sum(x_i - \\bar{x})^2}{n-1}$ es el estimador *insesgado* de $\\sigma^2$. Dividir por $n$ produce un estimador sesgado que subestima sistemáticamente la varianza poblacional, especialmente con muestras pequeñas.\n\n:::\n\n\n\nLa distribución muestral proporciona:\n\n1.  El soporte de la variable, es decir, la lista de todos los posibles valores que puede tomar el estimador.\n2.  La probabilidad (o densidad de probabilidad) asociada a cada uno de esos valores, lo que nos permite medir el error de estimación.\n\nA continuación, estudiaremos las distribuciones muestrales teóricas para los estimadores de la media ($\\bar{X}$), la varianza ($S^2$) y la relación de esta última con la distribución Chi-cuadrada.\n\n------------------------------------------------------------------------\n\n## Distribución muestral de promedios ($\\bar{X}$)\n\nSi $X_1, X_2, \\dots, X_n$ representan una muestra aleatoria extraída de una población infinita (o con reemplazo) que posee una media $\\mu$ y una varianza $\\sigma^2$, entonces las propiedades del estimador media muestral $\\bar{X} = \\frac{\\sum_{i=1}^n X_i}{n}$ son:\n\n**Esperanza matemática (Valor esperado):** $$E[\\bar{X}] = \\mu_{\\bar{X}} = \\mu \\quad (1)$$ *(Esto demuestra que* $\\bar{X}$ es un estimador insesgado: en promedio, acierta al parámetro).\n\n**Varianza del estimador:** $$\\text{Var}(\\bar{X}) = \\sigma_{\\bar{X}}^2 = \\frac{\\sigma^2}{n} \\quad (2)$$ *(Esto demuestra que a mayor tamaño de muestra* $n$, menor es la varianza del estimador, haciendo nuestras estimaciones más precisas).\n\n> *Nota: Cuando la muestra se realiza **sin reemplazo** desde una población finita de tamaño* $N$, la esperanza sigue siendo $\\mu$, pero la varianza se ajusta multiplicándola por el factor de corrección por población finita: \\> $$\\text{Var}(\\bar{X}) = \\frac{\\sigma^2}{n} \\left(\\frac{N-n}{N-1}\\right) \\quad (2.1)$$\n\n**La forma de la distribución de** $\\bar{X}$\n\nIndependientemente de si calculamos la esperanza y la varianza por fuerza bruta (enumerando todas las combinaciones posibles), la pregunta fundamental en inferencia es: ¿Qué forma geométrica tiene la distribución de $\\bar{X}$?\n\nLa teoría estadística (Teorema de la combinación lineal de normales) establece que: Si las variables aleatorias $X_1, X_2, \\dots, X_n$ provienen de una **población normal** con media $\\mu$ y varianza $\\sigma^2$, entonces la distribución exacta del estimador $\\bar{X}$ también será Normal. $$\\bar{X} \\sim N\\left(\\mu_{\\bar{X}} = \\mu, \\sigma_{\\bar{X}}^2 = \\frac{\\sigma^2}{n}\\right)$$\n\nConociendo esta distribución matemática exacta, es posible calcular probabilidades sobre el comportamiento de nuestras muestras.\n\n**Ejemplo:** El coeficiente intelectual (CI) de los alumnos de un centro escolar se distribuye como una variable aleatoria Normal con $\\mu = 80$ y varianza $\\sigma^2 = 100$. Si se extrae una muestra aleatoria de $n=25$ alumnos.\n\n**¿Cuál es la probabilidad de que el CI promedio de esa muestra en particular sea mayor a 75 puntos?**\n\nDefinimos $X$: CI de un alumno $\\sim N(80, 10^2)$. Como la población es normal, la distribución de la media muestral será: $$\\bar{X} \\sim N\\left(\\mu_{\\bar{X}} = 80, \\sigma_{\\bar{X}}^2 = \\frac{100}{25} = 4\\right)$$\n\nLa desviación estándar de la media muestral (conocida como error estándar) es $\\sqrt{4} = 2$. La probabilidad de interés es calcular el área a la derecha de 75: $P(\\bar{X} > 75)$.\n\n\n::: {.cell}\n\n```\n#> [1] 0.994\n```\n:::\n\n\nLa probabilidad de que la media muestral exceda los 75 puntos es de **0.994** (o 99.4%). *(Nota didáctica: Al ser el error estándar muy pequeño (2), es casi seguro que el promedio de un grupo de 25 alumnos estará muy cerca de la media real de 80, por eso la probabilidad de que sea mayor a 75 es tan alta).*\n\n------------------------------------------------------------------------\n\n## Esperanza o media del estimador de la varianza ($S^2$)\n\nSi $X_1, X_2, \\dots, X_n$ representan una muestra aleatoria, el estimador insesgado de la varianza poblacional se define como: $$S^2 = \\frac{\\sum_{i=1}^n (X_i - \\bar{X})^2}{n-1}$$\n\nLa propiedad fundamental de este estimador es que su valor esperado es exactamente igual al parámetro poblacional que intenta estimar: $$E[S^2] = \\sigma^2 \\quad (5)$$\n\nA diferencia del estimador de la media ($\\bar{X}$), cuya distribución puede modelarse directamente con la campana de Gauss, el estimador de la varianza ($S^2$) suma números que están elevados al cuadrado. Dado que un cuadrado nunca puede ser negativo, la distribución de $S^2$ no puede ser simétrica ni abarcar números negativos. Para estudiar probabilísticamente a la varianza, debemos introducir una nueva familia matemática: la distribución Chi-cuadrada.\n\n------------------------------------------------------------------------\n\n## Distribución $\\chi^2$ (Chi-cuadrada)\n\nLa distribución $\\chi^2$ es un pilar de la inferencia estadística, estrechamente vinculada a la distribución Normal. Supongamos que tenemos una variable aleatoria de interés que sigue una distribución normal: $X \\sim N(\\mu, \\sigma^2)$. Si seleccionamos una muestra aleatoria $X_1, X_2, \\dots, X_n$, es lógico suponer que cada observación se comporta como una normal.\n\nA continuación, transformamos (estandarizamos) estas variables normales restándoles su media poblacional y dividiéndolas por su desviación estándar poblacional: $$Z_i = \\frac{X_i - \\mu}{\\sigma}$$ Cada $Z_i$ ahora es una Normal Estándar $N(0, 1)$.\n\nSi elevamos al cuadrado cada una de estas variables estandarizadas independientes y las sumamos, generamos una nueva variable aleatoria matemática: $$\\sum_{i=1}^n Z_i^2 = \\left(\\frac{X_1 - \\mu}{\\sigma}\\right)^2 + \\left(\\frac{X_2 - \\mu}{\\sigma}\\right)^2 + \\dots + \\left(\\frac{X_n - \\mu}{\\sigma}\\right)^2$$\n\n> **Definición:** Una variable aleatoria Chi-cuadrada se define como la suma de variables aleatorias independientes, cada una con distribución Normal Estándar elevada al cuadrado.\n\nPor su propia naturaleza de suma de cuadrados, el soporte (campo de variación) de una variable $\\chi^2$ es estrictamente no negativo, de $0$ a $+\\infty$. Se simboliza como $\\chi^2_n$, donde $n$ representa los **grados de libertad** (el número de variables normales independientes que se están sumando).\n\n**Propiedades teóricas:** Para una variable $Y \\sim \\chi^2_n$: \\* Esperanza: $E[Y] = n$ \\* Varianza: $\\text{Var}(Y) = 2n$\n\nEl parámetro único que define a esta distribución son sus grados de libertad $n$. En la figura siguiente se muestra cómo la forma fuertemente asimétrica a la derecha (sesgada) de la distribución $\\chi^2$ va cambiando a medida que aumentan los grados de libertad.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-docx/chi_cuadrada_forma-1.png){fig-align='center'}\n:::\n:::\n\n\n*(Nota: Eventualmente, cuando los grados de libertad tienden a infinito, la curva se vuelve perfectamente simétrica, aproximándose a una distribución Normal por efecto del Teorema del Límite Central).*\n\n------------------------------------------------------------------------\n\n## Cálculo de probabilidades para la distribución $\\chi^2$\n\nEn lugar de recurrir a las clásicas tablas impresas (que solo muestran cuantiles acumulados fijos), podemos calcular probabilidades exactas para cualquier escenario utilizando el software estadístico R.\n\nConsidere que tiene una variable aleatoria $X$ que proviene de una distribución Chi-cuadrada con $12$ grados de libertad ($X \\sim \\chi^2_{12}$).\n\nEn R, la función `pchisq(q, df)` calcula la probabilidad acumulada a la izquierda (cola inferior) hasta el valor $q$ dado, esto es, $F(x) = P(X \\le x)$.\n\n**a) Calcular probabilidad en un intervalo:** $P(5.23 \\le X \\le 14.8)$\n\nPara encontrar el área entre dos puntos, calculamos el área acumulada hasta el límite superior y le restamos el área acumulada hasta el límite inferior: $$P(5.23 \\le X \\le 14.8) = P(X \\le 14.8) - P(X \\le 5.23)$$\n\n\n::: {.cell}\n\n```\n#> [1] 0.697\n```\n:::\n\n\nLa probabilidad de caer en este intervalo central es aproximadamente **0.697**.\n\n**b) Calcular probabilidad acumulada (Cola izquierda):** $P(X < 26.2)$\n\nAl ser una distribución continua, el signo estricto ($<$) es equivalente al no estricto ($\\le$).\n\n\n::: {.cell}\n\n```\n#> [1] 0.99\n```\n:::\n\n\nLa probabilidad de observar un valor menor a 26.2 es de **0.99**.\n\n**c) Calcular probabilidad de excedencia (Cola derecha):** $P(X > 6.30)$\n\nLa función `pchisq` por defecto acumula a la izquierda. Para calcular la cola derecha (\"área mayor que\"), debemos usar la regla del complemento (1 menos el área izquierda). $$P(X > 6.30) = 1 - P(X \\le 6.30)$$\n\n\n::: {.cell}\n\n```\n#> [1] 0.9\n```\n:::\n\n\nLa probabilidad de observar un valor superior a 6.30 es de **0.90**.\n\n**d) Encontrar un percentil/cuantil inverso: Si** $P(X < a) = 0.01$, ¿quién es el valor $a$?\n\nAquí el problema está invertido. Conocemos el área (0.01) y buscamos el punto de corte en el eje horizontal. En R, las funciones inversas para buscar cuantiles comienzan con la letra 'q'. En este caso usamos `qchisq(p, df)`.\n\n\n::: {.cell}\n\n```\n#> [1] 3.57\n```\n:::\n\n\nEl valor crítico es $a = 3.57$. Es decir, hay un 1% de probabilidad de que esta variable $\\chi^2_{12}$ tome un valor inferior a 3.57.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-docx/grafica_cola_izq-1.png){fig-align='center'}\n:::\n:::\n\n\n## Distribución del estimador $S^2$\n\nComo mencionamos anteriormente, el estimador de la varianza $S^2$ por sí solo no tiene una distribución de probabilidad que podamos tipificar directamente en una tabla. Sin embargo, existe una transformación matemática fundamental que asocia a este estadístico con una distribución conocida.\n\n> **Teorema:** Si $X_1, X_2, \\dots, X_n$ es una muestra aleatoria extraída de una **población normal** con media $\\mu$ y varianza $\\sigma^2$, entonces la variable aleatoria creada al multiplicar la varianza muestral por sus grados de libertad y dividirla entre la varianza poblacional, se distribuye como una Chi-cuadrada con $n-1$ grados de libertad.\n\n$$\\frac{(n-1)S^2}{\\sigma^2} \\sim \\chi^2_{n-1} \\quad (8)$$\n\n::: {.callout-note icon=false}\n## Nota\nEsta relación es el núcleo de la inferencia para varianzas, pero depende fuertemente de la suposición de que la población original sea Normal. Si la población no es Normal, este estadístico no seguirá una distribución Chi-cuadrada.\n\n:::\n\n**Ejemplo 1**\n\nSe considera una medición física realizada con un instrumento de precisión donde el interés se centra en la variabilidad de la lectura. Se sabe que la medición es una variable aleatoria con distribución Normal y desviación típica de 4 unidades (es decir, una varianza poblacional $\\sigma^2 = 16$).\n\nSe toma una muestra aleatoria de tamaño $n = 25$. **¿Cuál es la probabilidad de que la varianza muestral calculada (**$S^2$) sea mayor a 12.16 unidades cuadradas?\n\nEl evento de interés es $P(S^2 > 12.16)$. Desafortunadamente, calcular la probabilidad directa de $S^2$ no es posible. Para resolverlo, transformamos ambos lados de la desigualdad utilizando la ecuación (8):\n\nMultiplicamos por $(n-1)$ y dividimos por $\\sigma^2$: $$P\\left( S^2 > 12.16 \\right) = P\\left( \\frac{(25-1)S^2}{16} > \\frac{(25-1)(12.16)}{16} \\right)$$ $$= P\\left( \\chi^2_{24} > \\frac{24 \\cdot 12.16}{16} \\right) = P(\\chi^2_{24} > 18.24) \\quad (9)$$\n\nAhora el problema se reduce a buscar el área a la derecha del valor 18.24 en una distribución Chi-cuadrada con 24 grados de libertad. En R, calculamos el complemento del área acumulada:\n\n\n::: {.cell}\n\n```\n#> [1] 0.791\n```\n:::\n\n\nLa probabilidad de que la varianza muestral sea mayor a 12.16 es de **0.791** (79.1%).\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. El tiempo de vida de cierto componente se distribuye $N(\\mu, \\sigma^2)$ con $\\sigma = 5$. Si se toma una muestra de $n=16$, calcule $P(\\bar{X} > \\mu + 2)$.\n2. Si $Y \\sim \\chi^2_{15}$, use R (funciones `pchisq`/`qchisq`) para calcular $P(Y > 22)$ y el valor crítico $a$ tal que $P(Y < a) = 0.05$.\n3. Una muestra de $n=10$ observaciones normales tiene $\\sigma^2 = 9$. Calcule $P(S^2 > 14)$ usando la relación entre $S^2$ y la distribución Chi-cuadrada.\n\n:::\n\n------------------------------------------------------------------------\n\n## Distribución $t$ de Student\n\nLa distribución $t$ de Student es el modelo matemático que utilizamos cuando queremos hacer inferencias sobre la media poblacional $\\mu$, pero **desconocemos la verdadera desviación estándar poblacional** $\\sigma$ y nos vemos obligados a estimarla usando la desviación estándar de nuestra muestra ($S$).\n\nUna variable aleatoria $T$ tiene una distribución $t$ de Student si se define como la razón entre una variable Normal Estándar y la raíz cuadrada de una variable Chi-cuadrada dividida por sus grados de libertad (Mendenhall et al.):\n\nSean $Z \\sim N(0,1)$ y $U \\sim \\chi^2_n$ variables aleatorias independientes. Entonces: $$T = \\frac{Z}{\\sqrt{U/n}} \\sim t_n$$\n\nAplicando esto a nuestros estimadores muestrales ($Z = \\frac{\\bar{X}-\\mu}{\\sigma/\\sqrt{n}}$ y $U = \\frac{(n-1)S^2}{\\sigma^2}$): $$T = \\frac{\\bar{X} - \\mu}{S / \\sqrt{n}} \\sim t_{n-1} \\quad (10.1)$$\n\n**Propiedades de la distribución** $t$\n\na)  Varía de $-\\infty$ a $\\infty$, igual que la Normal.\nb)  Es perfectamente simétrica con respecto al $0$.\nc)  Presenta una mayor dispersión que la Normal Estándar. Esto se debe a que la fórmula del estadístico $T$ tiene dos fuentes de variabilidad por el muestreo: la de $\\bar{X}$ en el numerador y la de $S$ en el denominador (a diferencia de $Z$, donde $\\sigma$ es una constante fija).\nd)  **Colas pesadas:** Alrededor de la media, la campana Normal es más alta. Sin embargo, en los extremos (las colas), la distribución $t$ acumula más área (probabilidad).\ne)  A medida que aumenta el tamaño de la muestra ($n \\to \\infty$), la estimación $S$ se vuelve tan precisa que la distribución $t$ se vuelve idéntica a la Normal Estándar.\n\n------------------------------------------------------------------------\n\n## Cálculo de probabilidades de una distribución $t$ de Student\n\n**Ejemplo:** Un ingeniero agrónomo ha desarrollado una variedad de maíz (\"xy32\") y afirma que su rendimiento medio es de $\\mu = 1.5 \\text{ kg/planta}$. En un campo experimental se cultivaron $n = 20$ plantas. Tras la cosecha, se estimó una desviación estándar muestral de $S = 0.8 \\text{ kg/planta}$.\n\nEl agrónomo teme que, por azar, el rendimiento medio de la muestra resulte ser muy bajo. **¿Cuál es la probabilidad de que el rendimiento medio muestral (**$\\bar{X}$) sea inferior a 1 kg?\n\nSi **erróneamente** asumiéramos que la desviación poblacional es conocida y exacta ($\\sigma = 0.8$), usaríamos la distribución Normal: $$P(\\bar{X} \\le 1) = P\\left( Z \\le \\frac{1 - 1.5}{0.8 / \\sqrt{20}} \\right) = P(Z \\le -2.80) \\approx 0.0026$$\n\nSin embargo, esto es incorrecto. Sabemos que $0.8$ es solo una estimación ($S$), por lo que debemos usar la distribución $t$ de Student con $n-1 = 19$ grados de libertad, según la ecuación (10.1):\n\n$$P(\\bar{X} \\le 1) = P\\left( T_{19} \\le \\frac{1 - 1.5}{0.8 / \\sqrt{20}} \\right) = P(T_{19} \\le -2.80)$$\n\n\n::: {.cell}\n\n```\n#> [1] 0.006\n```\n:::\n\n\nLa probabilidad real es de **0.006**. Observa que es más del doble de lo que estimamos erróneamente con la Normal. Esto ilustra el concepto de las \"colas pesadas\": la incertidumbre adicional de no conocer $\\sigma$ hace que los eventos extremos sean más probables.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-docx/grafica_comparativa_t_normal-1.png){fig-align='center'}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Distribución $F$ de Fisher\n\nLa distribución $F$ surge de manera natural cuando queremos **comparar las varianzas de dos poblaciones distintas**.\n\n> **Definición:** Sean $U \\sim \\chi^2_{v_1}$ y $W \\sim \\chi^2_{v_2}$ dos variables aleatorias independientes con distribución Chi-cuadrada. La variable aleatoria $F$ se define como la razón de ambas variables, cada una dividida previamente por sus respectivos grados de libertad: $$F_{v_1, v_2} = \\frac{U / v_1}{W / v_2} \\quad (13)$$\n\n**Ejemplo:** Se tiene muy bien estudiado el tiempo de vuelo de dos aerolíneas. Ambas tienen el mismo tiempo medio de vuelo y, supongamos, **la misma varianza poblacional** ($\\sigma_1^2 = \\sigma_2^2$).\n\nSe obtiene una muestra aleatoria de $n_1 = 15$ vuelos de la aerolínea 1, y $n_2 = 25$ de la aerolínea 2. **¿Cuál es la probabilidad de que la varianza muestral de la primera aerolínea sea más del doble que la de la segunda?** Es decir, calcular: $P\\left( \\frac{S_1^2}{S_2^2} > 2 \\right)$.\n\nSabiendo por la ecuación (8) que $U = \\frac{(n_1-1)S_1^2}{\\sigma_1^2} \\sim \\chi^2_{n_1-1}$, si dividimos $U$ entre sus grados de libertad ($n_1-1$), obtenemos simplemente $\\frac{S_1^2}{\\sigma_1^2}$. Haciendo lo mismo para la segunda muestra, la razón $F$ queda estructurada como:\n\n$$F_{n_1-1, n_2-1} = \\frac{ \\frac{S_1^2}{\\sigma_1^2} }{ \\frac{S_2^2}{\\sigma_2^2} } = \\left(\\frac{S_1^2}{S_2^2}\\right) \\left(\\frac{\\sigma_2^2}{\\sigma_1^2}\\right)$$\n\nDado que asumimos que las varianzas poblacionales son iguales ($\\sigma_1^2 = \\sigma_2^2$), el término de la derecha se cancela (es 1). Por lo tanto, **el cociente de las varianzas muestrales sigue exactamente una distribución** $F$: $$\\frac{S_1^2}{S_2^2} \\sim F_{14, 24}$$\n\nLa probabilidad de interés se convierte directamente en: $$P\\left( \\frac{S_1^2}{S_2^2} > 2 \\right) = P(F_{14, 24} > 2)$$\n\nCalculamos esto en R usando la función `pf`, que requiere el cuantil y los dos grados de libertad correspondientes:\n\n\n::: {.cell}\n\n```\n#> [1] 0.065\n```\n:::\n\n\nLa probabilidad de que, por puro azar del muestreo, la varianza observada de la aerolínea 1 sea el doble que la de la aerolínea 2 (aun cuando en la realidad sean iguales) es de **0.063** (6.3%).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-docx/grafica_f_fisher-1.png){fig-align='center'}\n:::\n:::\n\n\n## Cálculo de probabilidades de una distribución F\n\nPara hacer más ágil y preciso el cálculo de probabilidades, se emplea el software estadístico R en lugar de las tradicionales tablas impresas.\n\nRetomando el ejemplo anterior de las dos aerolíneas, la probabilidad de interés en la ecuación (16) era: $$P(F_{14, 24} > 1.167) = 1 - P(F_{14, 24} \\le 1.167)$$\n\nLa probabilidad de que la razón de las varianzas muestrales exceda a 2 (sabiendo que la razón de las varianzas poblacionales se asume igual a 1) se calcula en R de la siguiente manera:\n\n\n::: {.cell}\n\n```\n#> [1] 0.358\n```\n:::\n\n\nLa función `pf(q, df1, df2)` tiene como primer argumento el valor de interés a calcular su probabilidad ($q$), después los grados de libertad del numerador ($df1$) y por último los grados de libertad del denominador ($df2$). Por defecto, la función `pf` calcula la probabilidad de la cola izquierda (probabilidad acumulada).\n\nLa distribución $F$ tiene gran aplicación en inferencia estadística, principalmente en el famoso Análisis de Varianza (mejor conocido como ANOVA).\n\n**Cálculo de cuantiles (valores críticos):** En algunas situaciones, se conoce el valor de los grados de libertad $v_1$, $v_2$ y un nivel de probabilidad $\\alpha$ (área en la cola), de modo que el interés será encontrar el valor de corte $k$. $$P(F_{v_1, v_2} > k) = \\alpha$$\n\nSi $v_1 = 14$, $v_2 = 24$ y $\\alpha = 0.05$, se tiene que: $$P(F_{14, 24} > k) = 0.05 \\quad (17)$$\n\nEn R, el código para encontrar este valor crítico $k$ es el siguiente:\n\n\n::: {.cell}\n\n```\n#> [1] 2.13\n```\n:::\n\n\nAl especificar `lower.tail = FALSE` en la función `qf`, le indicamos al software que considere el área de probabilidad en la cola derecha. En este caso, $k \\approx 2.13$.\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. Una muestra de $n=12$ observaciones normales tiene $\\bar{x}=48$ y $s=6$. Pruebe si es razonable suponer $\\mu=50$ calculando $P(\\bar{X} \\le 48)$ usando la distribución $t$ con los grados de libertad correspondientes.\n2. Use R (`qt`) para encontrar el valor crítico $t$ que deja un área de 0.025 en la cola derecha de una distribución $t$ con 18 grados de libertad.\n3. Se comparan las varianzas de dos máquinas con muestras de tamaño $n_1=10$ y $n_2=13$. Calcule $P(F_{9,12} > 1.5)$ usando R (`pf`).\n\n:::\n\n------------------------------------------------------------------------\n\n## Distribución muestral del estimador de la proporción\n\nCuando estudiamos una característica cualitativa en una población (por ejemplo: artículo defectuoso vs. no defectuoso, alquila vivienda vs. no alquila), trabajamos con variables que asumen solo dos valores.\n\nSea $X_i$ una variable de Bernoulli (ver @sec-bernoulli) tal que: $$X_i = \\begin{cases} 1, & \\text{si se presenta la característica de interés} \\\\ 0, & \\text{si no se presenta la característica de interés} \\end{cases}$$\n\nLa **proporción muestral** ($\\hat{P}$ o $\\bar{P}$) se define como el promedio de estas variables: $$\\hat{P} = \\frac{X_1 + X_2 + \\dots + X_n}{n} = \\frac{\\sum_{i=1}^n X_i}{n}$$\n\nSea $X_1, X_2, \\dots, X_n$ una muestra aleatoria extraída de una distribución Bernoulli (@sec-bernoulli) con parámetro poblacional $P$ (la verdadera proporción de \"éxitos\" en la población). Según la teoría estadística (Mendenhall et al.), las propiedades del estimador $\\hat{P}$ son:\n\n**Esperanza matemática:** $$E[\\hat{P}] = \\mu_{\\hat{P}} = P \\quad (18)$$ *(El estimador de la proporción es insesgado).*\n\n**Varianza del estimador:** $$\\text{Var}(\\hat{P}) = \\sigma_{\\hat{P}}^2 = \\frac{P \\cdot Q}{n} \\quad (19)$$ Donde $Q = 1 - P$.\n\n**Ejemplo 1**\n\nConsideremos una población minúscula que consta de $N = 4$ familias. Nos interesa conocer qué familias alquilan una vivienda. En la Tabla 7 se expone la población y el cálculo del parámetro real.\n\n**Tabla 7. Población de viviendas.**\n\n| Familia ($i$) | Alquila ($x_i$) |\n|:-------------:|:---------------:|\n|     A (1)     |        0        |\n|     B (2)     |        1        |\n|     C (3)     |        0        |\n|     D (4)     |        0        |\n\nEl **parámetro poblacional** real (Proporción de familias que alquilan) es: $$P = \\frac{\\sum_{i=1}^N x_i}{N} = \\frac{0 + 1 + 0 + 0}{4} = \\frac{1}{4} = 0.25$$\n\nAhora construyamos la distribución muestral del estimador $\\hat{P}$ tomando todas las muestras posibles de tamaño $n = 2$ con reemplazo. El número total de muestras posibles es $N^n = 4^2 = 16$.\n\n**Tabla 8. Distribución muestral de la Proporción.**\n\n| Viviendas Seleccionadas | Valores Observados | Proporción Estimada $\\hat{p}$ | Probabilidad $P(\\hat{P} = \\hat{p})$ |\n|:---|:--:|:--:|:--:|\n| (A,A), (A,C), (A,D), (C,A), (C,C), (C,D), (D,A), (D,C), (D,D) | 0 y 0 | 0 | 9/16 |\n| (A,B), (B,A), (B,C), (C,B), (B,D), (D,B) | 0 y 1 / 1 y 0 | 0.5 | 6/16 |\n| (B,B) | 1 y 1 | 1 | 1/16 |\n| **Total** |  |  | **1** |\n\nCon base en la Tabla 8, es evidente que $\\hat{P}$ es una variable aleatoria. Podemos comprobar la Ecuación (18) calculando la esperanza a partir de esta distribución muestral empírica: $$E[\\hat{P}] = \\sum \\left( \\hat{p}_i \\cdot P(\\hat{P} = \\hat{p}_i) \\right) = \\left(0 \\cdot \\frac{9}{16}\\right) + \\left(0.5 \\cdot \\frac{6}{16}\\right) + \\left(1 \\cdot \\frac{1}{16}\\right) = \\frac{3}{16} + \\frac{1}{16} = \\frac{4}{16} = 0.25$$ Vemos que $E[\\hat{P}] = P = 0.25$.\n\nComprobando la Ecuación (19) para la varianza: $$\\text{Var}(\\hat{P}) = \\frac{P(1-P)}{n} = \\frac{0.25(0.75)}{2} = \\frac{0.1875}{2} = 0.09375$$\n\n------------------------------------------------------------------------\n\n## Teorema del Límite Central (TLC)\n\nEste es, quizás, el teorema de mayor importancia práctica en la estadística inferencial.\n\n::: {.callout-caution icon=false}\n## Errores comunes: Teorema del Límite Central\n\n**Error 1 — Creer que el TLC dice que *los datos* se distribuyen normal.**  \nEl TLC habla de la distribución del *promedio muestral* $\\bar{X}$, no de los datos individuales $X_i$. Una muestra de 100 observaciones de una distribución exponencial seguirá siendo exponencial; lo que se aproxima a la normal es la distribución de $\\bar{X}$ entre muestras repetidas.\n\n**Error 2 — Aplicar el TLC con $n$ pequeño en distribuciones muy asimétricas.**  \nLa regla $n \\geq 30$ es una guía general. En distribuciones con colas muy pesadas o alta asimetría, puede necesitarse $n$ mucho mayor para que la aproximación normal sea razonable.\n\n:::\n\n Especifica cuál es el comportamiento de las distribuciones de promedios o sumas cuando el tamaño de la muestra crece.\n\n> **Teorema del Límite Central:** Sea $X_1, X_2, \\dots, X_n$ una muestra aleatoria de tamaño $n$, extraída de una población con **cualquier** distribución de probabilidad (no necesariamente normal), que posea una media finita $\\mu$ y una varianza finita $\\sigma^2$. A medida que el tamaño de la muestra $n$ se vuelve grande ($n \\to \\infty$), la distribución muestral del promedio $\\bar{X}$ se aproxima a una distribución Normal con media $\\mu_{\\bar{X}} = \\mu$ y varianza $\\sigma_{\\bar{X}}^2 = \\frac{\\sigma^2}{n}$.\n\n$$\\bar{X} \\approx N\\left(\\mu, \\frac{\\sigma^2}{n}\\right)$$\n\n**¿Qué tan grande debe ser** $n$? El valor necesario de $n$ depende de qué tan asimétrica sea la distribución original de la población: \\* Si la población es bastante simétrica, un $n \\ge 5$ puede ser suficiente. \\* Si la distribución original está muy sesgada o es altamente irregular (ej. Exponencial [@sec-exponencial], bimodal), la regla de oro en estadística dicta que un tamaño de muestra $n \\ge 30$ garantiza una aproximación excelente a la Normal.\n\n**El TLC para el Estimador del Total (**$T$): El teorema también se aplica a la suma total de las observaciones $T = \\sum_{i=1}^n X_i$. Si $n$ es grande: $$T \\approx N\\left( \\mu_T = n\\mu, \\sigma_T^2 = n\\sigma^2 \\right)$$\n\n**Ejemplo 1**\n\nSuponga que el peso de los paquetes de café de cierto tipo tiene una media de $\\mu = 1 \\text{ kg}$ y una desviación estándar de $\\sigma = 0.05 \\text{ kg}$ (distribución poblacional desconocida). En una caja se empacan $n = 64$ paquetes.\n\n**¿Cuál es la probabilidad de que el peso total de los 64 paquetes esté entre 63 y 64.4 kg?**\n\nBuscamos $P(63 \\le T \\le 64.4)$. Aunque no conocemos la distribución individual, como $n=64$ es un tamaño grande, aplicamos el TLC para el Total: $$T \\sim N\\left( \\mu_T = 64(1) = 64, \\sigma_T^2 = 64(0.05)^2 = 0.16 \\right)$$ La desviación estándar del total será $\\sigma_T = \\sqrt{0.16} = 0.4 \\text{ kg}$.\n\n\n::: {.cell}\n\n```\n#> [1] 0.835\n```\n:::\n\n\nLa probabilidad es de **0.835**.\n\n------------------------------------------------------------------------\n\n## Teorema del límite central para el estimador de la proporción\n\nDado que la proporción muestral $\\hat{P}$ es, matemáticamente, un promedio de variables aleatorias Bernoulli (@sec-bernoulli; 1s y 0s), **el Teorema del Límite Central también aplica a las proporciones**.\n\nSi $n$ es grande, el proceso de tomar muestras y estimar la proporción genera una distribución que se puede modelar con una curva Normal: $$\\hat{P} \\approx N\\left( \\mu_{\\hat{P}} = P, \\sigma_{\\hat{P}}^2 = \\frac{P(1-P)}{n} \\right)$$\n\n**Ejemplo 1**\n\nUn medicamento para el malestar estomacal tiene la advertencia de que puede causar reacciones adversas. Por estudios clínicos, se asume que el parámetro poblacional es $P = 0.03$ (el 3% de los usuarios presenta reacción).\n\nSi se receta el medicamento a una muestra de $n = 150$ personas, **¿cuál es la probabilidad de que la proporción observada en esta muestra supere el 4%?**\n\nPor el TLC para proporciones, la variable $\\hat{P}$ (proporción de reacciones en la muestra) se distribuye como: $$\\hat{P} \\approx N\\left( 0.03, \\frac{0.03(1 - 0.03)}{150} \\right) = N(0.03, 0.000194)$$\n\nLa desviación estándar (error estándar de la proporción) es $\\sqrt{0.000194} \\approx 0.0139$. La probabilidad de interés es $P(\\hat{P} > 0.04)$.\n\n\n::: {.cell}\n\n```\n#> [1] 0.236\n```\n:::\n\n\nLa probabilidad de que más del 4% de la muestra presente reacciones adversas es de **0.236** (23.6%).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-docx/grafica_tlc_prop-1.png){fig-align='center'}\n:::\n:::\n\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. El tiempo de ensamblaje de una pieza tiene media $\\mu = 12$ minutos y desviación estándar $\\sigma = 3$ minutos (distribución desconocida). Para una muestra de $n = 49$ piezas, use el TLC para calcular $P(\\bar{X} > 12.5)$.\n2. En una encuesta a $n = 200$ personas, se asume que la verdadera proporción que prefiere un producto es $P = 0.40$. Calcule, usando el TLC para proporciones, la probabilidad de que la proporción muestral sea menor a 0.35.\n3. Explique por qué el Teorema del Límite Central es útil incluso cuando no conocemos la distribución exacta de la población original.\n\n:::\n\n## Distribuciones de muestreo {#sec-distribuciones-muestreo}\n\n::: {.content-visible when-format=\"html\"}\n[📖 Humberto Martínez Bautista]{.fuente-badge .fuente-humberto}\n\n:::\n\n\n::: {.callout-tip icon=false}\n## Fuente: Apuntes del curso (Prof. Magín Zúñiga Estrada)\n\n:::\n\nAntes de estimar parámetros o probar hipótesis es indispensable conocer cómo se distribuyen los **estadísticos muestrales** (funciones de la muestra). Las tres distribuciones siguientes son el puente entre los capítulos de distribuciones de probabilidad y la inferencia estadística.\n\n### Media y varianza muestrales\n\nSea $X_1, \\ldots, X_n$ una muestra aleatoria de una población con media $\\mu$ y varianza $\\sigma^2 < \\infty$. Se definen:\n\n$$\\bar{X} = \\frac{1}{n}\\sum_{i=1}^n X_i, \\qquad S^2 = \\frac{1}{n-1}\\sum_{i=1}^n (X_i - \\bar{X})^2$$\n\n**Propiedades exactas:**\n\n$$E[\\bar{X}] = \\mu, \\qquad \\text{Var}(\\bar{X}) = \\frac{\\sigma^2}{n}, \\qquad E[S^2] = \\sigma^2$$\n\nLa primera igualdad dice que $\\bar{X}$ es un estimador **insesgado** de $\\mu$; la segunda, que su precisión mejora con el tamaño de la muestra; la tercera, que $S^2$ es un estimador insesgado de $\\sigma^2$ (de ahí el divisor $n-1$).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-docx/muestral-sim-1.png){fig-align='center'}\n:::\n:::\n\n\n### Distribución Chi-cuadrada ($\\chi^2$) {#sec-chi2}\n\nLa distribución $\\chi^2$ surge naturalmente de la varianza muestral. Si $X_1, \\ldots, X_n \\sim N(\\mu, \\sigma^2)$, entonces:\n\n$$\\frac{(n-1)S^2}{\\sigma^2} \\sim \\chi^2_{n-1}$$\n\n**Definición formal:** $X$ tiene distribución $\\chi^2$ con $k$ grados de libertad si su función de densidad es:\n\n$$f(x) = \\frac{1}{\\Gamma(k/2)}\\left(\\frac{1}{2}\\right)^{k/2} x^{k/2-1} e^{-x/2}, \\quad x > 0$$\n\n**Resultado clave:** si $Z_1, \\ldots, Z_n$ son normales estándar independientes, entonces $\\sum Z_i^2 \\sim \\chi^2_n$.\n\n$$E[X] = k, \\qquad \\text{Var}(X) = 2k$$\n\n::: {.callout-note icon=false}\n### Observación\nAl estimar $\\mu$ con $\\bar{X}$, se pierde un grado de libertad porque la restricción $\\sum(X_i - \\bar{X}) = 0$ hace que solo $n-1$ desviaciones sean libres. Por eso la distribución de $(n-1)S^2/\\sigma^2$ tiene $n-1$ g.l., no $n$.\n\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-docx/chi2-plot-1.png){fig-align='center'}\n:::\n:::\n\n\n**Aplicación — IC para la varianza:** si $x_1, \\ldots, x_n$ es una muestra de $N(\\mu, \\sigma^2)$, el intervalo de confianza de nivel $(1-\\alpha)$ para $\\sigma^2$ es:\n\n$$\\left(\\frac{(n-1)s^2}{\\chi^2_{n-1,\\,\\alpha/2}},\\; \\frac{(n-1)s^2}{\\chi^2_{n-1,\\,1-\\alpha/2}}\\right)$$\n\n\n::: {.cell}\n\n```\n#> IC 95% para sigma^2: (2.776, 10.240)\n#> IC 95% para sigma:  (1.666, 3.200)\n```\n:::\n\n\n### Distribución $t$ de Student {#sec-t-student}\n\nCuando $\\sigma^2$ es **desconocida**, se reemplaza por $S^2$ y el estadístico pivotal deja de ser normal estándar: se convierte en una $t$ de Student.\n\n**Definición:** si $Z \\sim N(0,1)$ y $U \\sim \\chi^2_k$ son independientes, entonces:\n\n$$T = \\frac{Z}{\\sqrt{U/k}} \\sim t_k$$\n\ncon función de densidad:\n\n$$f(x) = \\frac{\\Gamma\\!\\left[(k+1)/2\\right]}{\\Gamma(k/2)\\sqrt{k\\pi}} \\cdot \\frac{1}{\\left(1+x^2/k\\right)^{(k+1)/2}}, \\quad x \\in \\mathbb{R}$$\n\n**Corolario fundamental:** si $X_1,\\ldots,X_n \\sim N(\\mu, \\sigma^2)$, entonces:\n\n$$T = \\frac{\\bar{X} - \\mu}{S/\\sqrt{n}} \\sim t_{n-1}$$\n\nEsto permite construir IC y pruebas sobre $\\mu$ **sin conocer $\\sigma$**.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-docx/t-plot-1.png){fig-align='center'}\n:::\n:::\n\n\n::: {.callout-note icon=false}\n### Propiedad\nCuando $k \\to \\infty$, $t_k \\to N(0,1)$. En la práctica, para $k \\geq 30$ la diferencia es despreciable.\n\n:::\n\n### Distribución $F$ de Fisher {#sec-F-fisher}\n\nLa distribución $F$ surge al comparar **varianzas** de dos poblaciones normales independientes.\n\n**Definición:** si $U \\sim \\chi^2_m$ y $V \\sim \\chi^2_n$ son independientes, entonces:\n\n$$X = \\frac{U/m}{V/n} \\sim F_{m,n}$$\n\ncon función de densidad:\n\n$$f(x) = \\frac{\\Gamma[(m+n)/2]}{\\Gamma(m/2)\\,\\Gamma(n/2)} \\left(\\frac{m}{n}\\right)^{m/2} \\frac{x^{(m-2)/2}}{\\left[1+(m/n)x\\right]^{(m+n)/2}}, \\quad x>0$$\n\n**Corolario:** si $X_1,\\ldots,X_{m+1}$ y $Y_1,\\ldots,Y_{n+1}$ son muestras independientes de $N(\\mu_x, \\sigma^2)$ y $N(\\mu_y, \\sigma^2)$, entonces:\n\n$$F = \\frac{S_X^2}{S_Y^2} \\sim F_{m,n}$$\n\nEsto es la base de la prueba $F$ en ANOVA y en pruebas de igualdad de varianzas.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-docx/F-plot-1.png){fig-align='center'}\n:::\n:::\n\n\n**Relación entre distribuciones:** $t_k^2 \\sim F_{1,k}$.\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. Si $S^2 = 5.2$ con $n = 25$ observaciones de $N(\\mu, \\sigma^2)$, construya un IC del 90% para $\\sigma^2$.\n2. Demuestre que si $T \\sim t_k$, entonces $T^2 \\sim F_{1,k}$.\n3. Una muestra de $n=16$ de $N(\\mu, 4)$ tiene $\\bar{x} = 12.3$. Construya un IC del 95% para $\\mu$ usando la distribución $t$.\n\n:::\n\n## Estadísticas de orden {#sec-order-stats}\n\n:::: {.content-visible when-format=\"html\"}\n[📖 Magín Zúñiga Estrada]{.fuente-badge .fuente-magin}\n\n::::\n\nLas **estadísticas de orden** desempeñan en la inferencia un papel análogo al de los cuantiles poblacionales: son cuantiles muestrales. Dado que los datos observados son una realización de variables aleatorias, las estadísticas de orden son en sí mismas variables aleatorias con distribuciones propias.\n\n::: {.callout-tip icon=false}\n## Definición: estadísticas de orden\n\nSea $X_1, \\ldots, X_n$ una muestra aleatoria de tamaño $n$ de una distribución con cdf $F$. Las **estadísticas de orden** $Y_1 \\leq Y_2 \\leq \\cdots \\leq Y_n$ son las observaciones ordenadas de menor a mayor:\n\n$$Y_1 = \\min(X_1,\\ldots,X_n), \\quad Y_n = \\max(X_1,\\ldots,X_n)$$\n\nLas estadísticas de orden **no son independientes**: si $Y_k \\geq y$ entonces necesariamente $Y_{k+1} \\geq y$.\n\n:::\n\n::: {.callout-tip icon=false}\n## Resultado: CDF de la k-ésima estadística de orden\n\nLa función de distribución acumulada marginal de $Y_k$ ($k = 1, \\ldots, n$) es:\n\n$$F_{Y_k}(y) = \\sum_{j=k}^{n} \\binom{n}{j} [F(y)]^j [1-F(y)]^{n-j}$$\n\n**Demostración.** Fijado $y$, defina $Z_i = \\mathbf{1}\\{X_i \\leq y\\}$. Entonces $\\sum_{i=1}^n Z_i \\sim \\text{Bin}(n, F(y))$ y:\n\n$$F_{Y_k}(y) = P(Y_k \\leq y) = P\\!\\left(\\sum_{i=1}^n Z_i \\geq k\\right) = \\sum_{j=k}^{n} \\binom{n}{j} [F(y)]^j [1-F(y)]^{n-j}$$\n\nEl paso clave es la equivalencia $\\{Y_k \\leq y\\} \\Leftrightarrow \\{\\text{al menos } k \\text{ de las } X_i \\text{ caen en } (-\\infty, y]\\}$.\n\n:::\n\n::: {.callout-note icon=false}\n## Corolarios: mínimo y máximo\n\n**Máximo** ($k = n$):\n$$F_{Y_n}(y) = [F(y)]^n$$\n\n**Mínimo** ($k = 1$):\n$$F_{Y_1}(y) = 1 - [1-F(y)]^n$$\n\nEstos resultados son consecuencia directa de la independencia de la muestra: el máximo es $\\leq y$ sii todos los $X_i$ son $\\leq y$; el mínimo es $> y$ sii todos los $X_i$ son $> y$.\n\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-docx/order-stats-demo-1.png){fig-align='center'}\n:::\n:::\n\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. Sea $X_1,\\ldots,X_5 \\sim U(0,1)$. Calcula $P(Y_1 > 0.3)$ y $P(Y_5 \\leq 0.8)$ usando la cdf de las estadísticas de orden.\n2. Para $X_i \\sim \\text{Exp}(\\lambda)$, muestra que $Y_1 \\sim \\text{Exp}(n\\lambda)$ usando el corolario del mínimo.\n3. Escribe una simulación en R para verificar numéricamente la cdf de $Y_k$ para $k=3$, $n=7$ y $X_i \\sim U(0,1)$.\n\n:::\n\n\n\n## Métodos de estimación puntual {#sec-metodos-estimacion}\n\n::: {.content-visible when-format=\"html\"}\n[📖 Humberto Martínez Bautista]{.fuente-badge .fuente-humberto}\n\n:::\n\n\n::: {.callout-tip icon=false}\n## Fuente: Apuntes del curso (Prof. Magín Zúñiga Estrada)\n\nEl desarrollo de esta sección sigue el texto del Dr. Magín Zúñiga\nEstrada. Se presentan los dos métodos clásicos de estimación puntual:\nel método de momentos y el de máxima verosimilitud.\n\n:::\n\nUn **estimador** es un estadístico $T(\\mathbf{X})$ que, dada una\nrealización $x_1,\\ldots,x_n$ de la muestra, produce una estimación\n$\\hat{\\theta} = T(\\mathbf{x})$ del parámetro desconocido $\\theta$.\n\n::: {.callout-note icon=false}\n## Estimación puntual\n\nLa **estimación puntual** consiste en derivar un estadístico\n$\\hat{\\theta} = T(\\mathbf{X})$ que estime $\\theta$ mediante un solo\nvalor. Por convención $\\hat{\\theta}$ es una variable aleatoria (depende\nde los datos) y $\\theta$ es fijo y desconocido.\n\n:::\n\n### Método de momentos\n\nPropuesto por Karl Pearson (1902). La idea es **igualar momentos\npoblacionales con momentos muestrales**.\n\nEl $k$-ésimo momento poblacional es $\\mu_k = E[X^k]$ (función de\n$\\theta$). El $k$-ésimo momento muestral es\n$\\hat{\\mu}_k = \\frac{1}{n}\\sum_{i=1}^n x_i^k$.\n\nSe igualan $\\mu_k(\\theta) = \\hat{\\mu}_k$ y se despeja $\\theta$.\n\n**Ejemplo.** Sea $X_1,\\ldots,X_n \\overset{iid}{\\sim} \\text{Exp}(\\lambda)$.\nEncontrar el estimador de momentos de $\\lambda$.\n\n**Solución.** El primer momento poblacional es $\\mu_1 = E[X] = 1/\\lambda$.\nEl primer momento muestral es $\\hat{\\mu}_1 = \\bar{x}$.\nIgualando: $1/\\lambda = \\bar{x}$, por tanto $\\hat{\\lambda}_{MM} = 1/\\bar{x}$.\n\n\n::: {.cell}\n\n```\n#> lambda verdadera  : 2\n#> Estimación (MOM)  : 1.7789\n#> Error relativo    : 11.06 %\n```\n:::\n\n\n### Método de máxima verosimilitud\n\nPropuesto por Ronald Fisher (1912–1922). Es el método de estimación más\nimportante: los estimadores resultantes tienen propiedades óptimas\nasintóticas.\n\n::: {.callout-note icon=false}\n## Función de verosimilitud\n\nDada una muestra $x_1,\\ldots,x_n$ con $X_i \\sim f(x;\\theta)$, la\n**función de verosimilitud** es:\n$$L(\\theta \\mid x_1,\\ldots,x_n) = \\prod_{i=1}^n f(x_i;\\theta).$$\n\nLa **log-verosimilitud** es $\\ell(\\theta) = \\log L(\\theta)$.\n\n:::\n\n::: {.callout-note icon=false}\n## Estimador de Máxima Verosimilitud (EMV)\n\nEl **EMV** $\\hat{\\theta}_{MV}$ es el valor de $\\theta$ que maximiza\n$L(\\theta)$ (equivalentemente, $\\ell(\\theta)$):\n$$\\hat{\\theta}_{MV} = \\arg\\max_{\\theta \\in \\Theta} L(\\theta).$$\n\n:::\n\n**Principio:** se elige el valor de $\\theta$ que hace más probable\n(verosímil) haber observado los datos disponibles.\n\n**Ejemplo (Exponencial).** Sea $X_i \\sim \\text{Exp}(\\theta)$.\n\n$$L(\\theta) = \\prod_{i=1}^n \\theta e^{-\\theta x_i} = \\theta^n e^{-\\theta \\sum x_i}$$\n\n$$\\ell(\\theta) = n\\log\\theta - \\theta\\sum x_i \\quad \\Rightarrow \\quad\n\\frac{d\\ell}{d\\theta} = \\frac{n}{\\theta} - \\sum x_i = 0\n\\quad \\Rightarrow \\quad \\hat{\\theta}_{MV} = \\frac{n}{\\sum x_i} = \\frac{1}{\\bar{x}}.$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-docx/emv-exp-1.png){fig-align='center'}\n:::\n:::\n\n\n**Tabla EMV para distribuciones comunes:**\n\n| Distribución | Parámetro | EMV |\n|:-------------|:---------|:----|\n| $N(\\mu,\\sigma^2)$ | $\\mu$ | $\\hat{\\mu} = \\bar{X}$ |\n| $N(\\mu,\\sigma^2)$ | $\\sigma^2$ | $\\hat{\\sigma}^2 = \\frac{1}{n}\\sum(X_i-\\bar{X})^2$ |\n| $\\text{Exp}(\\lambda)$ | $\\lambda$ | $\\hat{\\lambda} = 1/\\bar{X}$ |\n| $\\text{Ber}(p)$ | $p$ | $\\hat{p} = \\bar{X}$ |\n| $\\text{Poisson}(\\lambda)$ | $\\lambda$ | $\\hat{\\lambda} = \\bar{X}$ |\n\n## Propiedades de los estimadores {#sec-propiedades-estimadores}\n\n::: {.content-visible when-format=\"html\"}\n[📖 Magín Zúñiga Estrada]{.fuente-badge .fuente-magin}\n\n:::\n\n\n::: {.callout-tip icon=false}\n## Fuente: Apuntes del curso (Prof. Magín Zúñiga Estrada)\n\n:::\n\nNo basta con obtener un estimador; es necesario evaluar su calidad. A\ncontinuación se presentan los criterios formales para comparar\nestimadores.\n\n### Sesgo (insesgamiento)\n\n::: {.callout-note icon=false}\n## Definición: Estimador insesgado y sesgo\n\nUn estimador $T(X_1,\\ldots,X_n)$ es **insesgado** para $\\theta$ si:\n$$E[T(X_1,\\ldots,X_n)] = \\theta.$$\n\nMás generalmente, para una función $g(\\theta)$ del parámetro:\n$$E[g(T(X_1,\\ldots,X_n))] = g(\\theta).$$\n\nEl **sesgo** de un estimador es:\n$$\\text{Sesgo}(T) = E[T] - \\theta.$$\n\n$T$ es sesgado si y solo si $\\text{Sesgo}(T) \\neq 0$.\n\n:::\n\n**Ejemplo.** $\\bar{X}$ es insesgado para $\\mu$. El estimador\n$\\hat{\\sigma}^2 = \\frac{1}{n}\\sum(X_i-\\bar{X})^2$ es sesgado para\n$\\sigma^2$; el insesgado es $S^2 = \\frac{1}{n-1}\\sum(X_i-\\bar{X})^2$.\n\n::: {.callout-note icon=false}\n## Definición: Estimador asintóticamente insesgado\n\n$\\hat{\\theta}_n$ es **asintóticamente insesgado** para $\\theta$ si:\n$$\\lim_{n\\to\\infty} E[\\hat{\\theta}_n] = \\theta.$$\n\n:::\n\n### Error cuadrático medio (ECM)\n\n::: {.callout-note icon=false}\n## Definición: CME\n\nEl **cuadrado medio del error (CME)** o error cuadrático medio de un\nestimador $T$ para $\\theta$ es:\n$$\\text{CME}(T, \\theta) = E_\\theta\\!\\left[(T - \\theta)^2\\right].$$\n\n**Descomposición fundamental:**\n$$\\text{CME}(T,\\theta) = \\text{Var}(T) + \\left[\\text{Sesgo}(T)\\right]^2.$$\n\n:::\n\n**Ejemplo — Comparación de estimadores de $\\sigma^2$:**\nSea $X_1,\\ldots,X_n$ muestra aleatoria de $N(\\mu,\\sigma^2)$. Considere\ndos estimadores para $\\sigma^2$:\n\n$$S_1^2 = \\frac{1}{n-1}\\sum_{i=1}^n (X_i-\\bar{X})^2 \\quad (\\text{insesgado}), \\qquad\n  S_2^2 = \\frac{1}{n+1}\\sum_{i=1}^n (X_i-\\bar{X})^2 \\quad (\\text{sesgado}).$$\n\nSus CMEs son: $\\text{CME}(S_1^2) = \\dfrac{2\\sigma^4}{n-1}$ y\n$\\text{CME}(S_2^2) = \\dfrac{2\\sigma^4}{n+1}$.\n\nComo $\\dfrac{2\\sigma^4}{n-1} > \\dfrac{2\\sigma^4}{n+1}$, el estimador\n**sesgado** $S_2^2$ tiene menor CME que el insesgado $S_1^2$. Esto\nilustra que un estimador sesgado puede ser preferible cuando su CME es\nmenor.\n\n\n::: {.cell}\n\n```\n#> --- Comparación S1² vs S2² (n=10, σ²=4) ---\n#> S1² insesgado — E[S1²]=4.0074  Sesgo=0.0074  CME=3.5134\n#> S2² sesgado   — E[S2²]=3.2788  Sesgo=-0.7212  CME=2.8721\n#> CME teórico  — S1²: 3.5556  S2²: 2.9091\n```\n:::\n\n\n### Consistencia\n\n::: {.callout-note icon=false}\n## Definición: Estimador consistente\n\n$\\hat{\\theta}_n$ es **consistente** para $\\theta$ si:\n$$\\lim_{n\\to\\infty} P(|\\hat{\\theta}_n - \\theta| > \\varepsilon) = 0\n  \\quad \\forall\\, \\varepsilon > 0.$$\n\nEs decir, $\\hat{\\theta}_n \\xrightarrow{p} \\theta$.\n\n:::\n\n::: {.callout-note icon=false}\n## Teorema: Criterio de consistencia\n\nSea $\\hat{\\theta}_n$ estimador puntual para $\\theta$. Si\n\n- $\\lim_{n\\to\\infty} E[\\hat{\\theta}_n] = \\theta$ (asintóticamente insesgado), y\n- $\\lim_{n\\to\\infty} \\text{Var}(\\hat{\\theta}_n) = 0$,\n\nentonces $\\hat{\\theta}_n$ es consistente.\n\n**Corolario:** $\\bar{X}$ es consistente para $\\mu$ (ya que\n$E[\\bar{X}]=\\mu$ y $\\text{Var}(\\bar{X})=\\sigma^2/n \\to 0$).\n\n:::\n\n### Estimadores insesgados de varianza uniformemente mínima (EIVUM)\n\n::: {.callout-note icon=false}\n## Definición: EIVUM (UMVUE)\n\nUn estimador $\\hat{\\theta}_n$ para $\\theta$ es un **estimador insesgado\nde varianza uniformemente mínima (EIVUM)** si:\n\n1. Es insesgado: $E[\\hat{\\theta}_n] = \\theta$.\n2. Su varianza es la mínima entre todos los estimadores insesgados para\n   $\\theta$, para todo $\\theta \\in \\Theta$.\n\n:::\n\n**Ejemplo — Poisson:** Sea $X_1,\\ldots,X_n$ muestra de $\\text{Poi}(\\lambda)$.\nTanto $\\bar{X}$ como $S^2$ son insesgados para $\\lambda$ (pues\n$E[X_i]=\\text{Var}(X_i)=\\lambda$). Sus varianzas son:\n$$\\text{Var}(\\bar{X}) = \\frac{\\lambda}{n}, \\qquad\n  \\text{Var}(S^2) = \\frac{\\lambda}{n} + \\frac{2\\lambda^2}{n-1}.$$\nComo $\\text{Var}(\\bar{X}) < \\text{Var}(S^2)$, $\\bar{X}$ es el mejor\nestimador insesgado entre los dos.\n\n### Cota de Cramér-Rao e información de Fisher\n\n::: {.callout-note icon=false}\n## Teorema: Cota inferior de Cramér-Rao (CICR)\n\nSea $X_1,\\ldots,X_n$ muestra aleatoria de $f(x;\\theta)$ y\n$g(T(X_1,\\ldots,X_n))$ estimador insesgado para $g(\\theta)$. Bajo\ncondiciones de regularidad:\n$$\\text{Var}(g(T)) \\geq\n  \\frac{[g'(\\theta)]^2}{n\\, \\mathcal{I}(\\theta)},$$\ndonde la **información de Fisher** es:\n$$\\mathcal{I}(\\theta) = E\\!\\left[\\left(\\frac{\\partial}{\\partial\\theta}\n  \\ln f(X;\\theta)\\right)^2\\right].$$\n\nEn particular, para $g(\\theta)=\\theta$ (estimación directa):\n$$\\text{CICR}(\\theta) = \\frac{1}{n\\,\\mathcal{I}(\\theta)}.$$\n\nUn estimador insesgado que **alcanza** la CICR es automáticamente EIVUM.\n\n:::\n\n::: {.callout-tip icon=false}\n## Ejemplo: CICR para Bernoulli($\\theta$)\n\nSea $X \\sim \\text{Ber}(\\theta)$. La log-verosimilitud es\n$\\ln f(X;\\theta) = X\\ln\\theta + (1-X)\\ln(1-\\theta)$, luego:\n$$\\frac{\\partial}{\\partial\\theta}\\ln f(X;\\theta) =\n  \\frac{X}{\\theta} - \\frac{1-X}{1-\\theta}.$$\n\nSu cuadrado en esperanza:\n$$\\mathcal{I}(\\theta) = E\\!\\left[\\left(\\frac{X}{\\theta}-\\frac{1-X}{1-\\theta}\\right)^2\\right]\n  = \\frac{1}{\\theta(1-\\theta)}.$$\n\nPor lo tanto:\n$$\\text{CICR}(\\theta) = \\frac{\\theta(1-\\theta)}{n}.$$\n\nComo $\\text{Var}(\\bar{X}) = \\theta(1-\\theta)/n = \\text{CICR}(\\theta)$,\nel estimador $\\bar{X}$ alcanza la cota y es EIVUM.\n\n:::\n\n\n::: {.cell}\n\n```\n#> CICR(theta) = theta*(1-theta)/n para Bern(theta), n=20:\n#>   theta=0.1  CICR=0.00450\n#>   theta=0.2  CICR=0.00800\n#>   theta=0.3  CICR=0.01050\n#>   theta=0.4  CICR=0.01200\n#>   theta=0.5  CICR=0.01250\n#>   theta=0.6  CICR=0.01200\n#>   theta=0.7  CICR=0.01050\n#>   theta=0.8  CICR=0.00800\n#>   theta=0.9  CICR=0.00450\n```\n:::\n\n\n### Eficiencia\n\n::: {.callout-note icon=false}\n## Definición: Estimador eficiente\n\nUn estimador insesgado es **eficiente** si su varianza alcanza la cota\ninferior de Cramér-Rao. La **eficiencia** de $\\hat{\\theta}$ es:\n$$\\text{Efi}(\\hat{\\theta}) = \\frac{\\text{CICR}(\\theta)}{\\text{Var}(\\hat{\\theta})}, \\quad 0 < \\text{Efi} \\leq 1.$$\n\nSe dice que $\\hat{\\theta}_n$ es **asintóticamente eficiente** si:\n$$\\lim_{n\\to\\infty} \\text{Efi}(\\hat{\\theta}_n) = 1.$$\n\n:::\n\n### Suficiencia\n\n::: {.callout-note icon=false}\n## Definición: Estadístico suficiente\n\nUna estadística $T(X_1,\\ldots,X_n)$ es **suficiente** para $\\theta$ si\nla distribución conjunta de la muestra $(X_1,\\ldots,X_n)$ condicionada\na $T=t$ no depende de $\\theta$, para cualquier valor posible $t$.\n\n**Interpretación:** dado el valor de $T$, la muestra no aporta\ninformación adicional sobre $\\theta$.\n\n:::\n\n::: {.callout-tip icon=false}\n## Ejemplo: Suficiencia de $T=\\sum X_i$ para Bernoulli\n\nSea $X_1,\\ldots,X_n$ muestra de $\\text{Ber}(\\theta)$, $T=\\sum X_i$.\nComo $T\\sim\\text{Bin}(n,\\theta)$:\n$$P(\\mathbf{X}=\\mathbf{x}\\mid T=t)\n  = \\frac{\\prod_{i=1}^n \\theta^{x_i}(1-\\theta)^{1-x_i}\\,\n    I_{\\{t\\}}(\\sum x_i)}{\\binom{n}{t}\\theta^t(1-\\theta)^{n-t}}\n  = \\frac{I_{\\{t\\}}(\\sum x_i)}{\\binom{n}{t}},$$\nque no depende de $\\theta$. Por tanto $T$ es suficiente.\n\n:::\n\n::: {.callout-note icon=false}\n## Teorema de Factorización de Neyman\n\n$T(X_1,\\ldots,X_n)$ es suficiente para $\\theta$ si y solo si la función\nde densidad conjunta puede factorizarse como:\n$$f(x_1,\\ldots,x_n;\\theta) = g(T(x_1,\\ldots,x_n),\\,\\theta)\\cdot h(x_1,\\ldots,x_n),$$\ndonde $g$ depende de los datos solo a través de $T$, y $h$ no depende\nde $\\theta$.\n\n:::\n\n**Ejemplo:** Para $\\text{Ber}(\\theta)$:\n$$f(\\mathbf{x};\\theta) = \\theta^{\\sum x_i}(1-\\theta)^{n-\\sum x_i}\n  \\prod_{i=1}^n I_{\\{0,1\\}}(x_i).$$\nCon $g(t,\\theta)=\\theta^t(1-\\theta)^{n-t}$ y\n$h(\\mathbf{x})=\\prod I_{\\{0,1\\}}(x_i)$, la factorización confirma que\n$T=\\sum X_i$ es suficiente.\n\n### Teorema de Rao-Blackwell\n\n::: {.callout-note icon=false}\n## Teorema de Rao-Blackwell\n\nSea $\\hat{\\theta}$ cualquier estimador insesgado para $\\theta$ y $T$ una\nestadística suficiente para $\\theta$. Define:\n$$\\phi(T) = E[\\hat{\\theta}\\mid T].$$\n\nEntonces:\n\n1. $E[\\phi(T)] = \\theta$ ($\\phi(T)$ es insesgado).\n2. $\\text{Var}(\\phi(T)) \\leq \\text{Var}(\\hat{\\theta})$ para todo $\\theta$.\n\nEs decir, $\\phi(T)$ es un estimador insesgado **uniformemente mejor**\nque $\\hat{\\theta}$.\n\n**Demostración:** Por la ley de la esperanza total:\n$$E[\\phi(T)] = E[E(\\hat{\\theta}\\mid T)] = E[\\hat{\\theta}] = \\theta.$$\nPor la ley de la varianza total:\n$$\\text{Var}(\\hat{\\theta}) = \\underbrace{\\text{Var}(E[\\hat{\\theta}\\mid T])}_{=\\,\\text{Var}(\\phi(T))}\n  + \\underbrace{E[\\text{Var}(\\hat{\\theta}\\mid T)]}_{\\geq\\,0}\n  \\geq \\text{Var}(\\phi(T)).$$\n\n:::\n\n## Pruebas de bondad de ajuste {#sec-bondad-ajuste}\n\nLas pruebas de bondad de ajuste responden la pregunta: **¿los datos observados son compatibles con una distribución teórica propuesta?** Son el puente entre la exploración de datos y la elección formal del modelo probabilístico.\n\n### Prueba chi-cuadrada de Pearson\n\n::: {.callout-note icon=false}\n## Definición: Prueba $\\chi^2$ de bondad de ajuste\n\nSea $X_1, \\ldots, X_n$ una muestra. Se divide el soporte de $X$ en $k$ clases (intervalos o categorías). Sea $O_i$ la frecuencia **observada** en la clase $i$ y $E_i = n \\cdot p_i$ la frecuencia **esperada** bajo la hipótesis $H_0$.\n\nEl estadístico de prueba es:\n\n$$\\chi^2 = \\sum_{i=1}^{k} \\frac{(O_i - E_i)^2}{E_i}$$\n\nBajo $H_0$, este estadístico sigue aproximadamente una distribución $\\chi^2$ con $\\nu = k - 1 - p$ grados de libertad, donde $p$ es el número de parámetros estimados de los datos.\n\n**Regla de decisión:** Se rechaza $H_0$ si $\\chi^2 > \\chi^2_{\\alpha, \\nu}$.\n\n**Requisito:** $E_i \\geq 5$ en cada clase (combinar clases si es necesario).\n\n:::\n\n::: {.callout-tip icon=false}\n## Ejemplo: ¿Los lanzamientos de un dado son uniformes?\n\nSe lanza un dado 120 veces y se registran los resultados:\n\n| Cara | 1 | 2 | 3 | 4 | 5 | 6 |\n|:----:|:-:|:-:|:-:|:-:|:-:|:-:|\n| $O_i$ | 25 | 17 | 15 | 23 | 24 | 16 |\n\n**$H_0$:** El dado es justo ($p_i = 1/6$ para cada cara).\n\nBajo $H_0$: $E_i = 120/6 = 20$ para toda $i$.\n\n$$\\chi^2 = \\frac{(25-20)^2}{20} + \\frac{(17-20)^2}{20} + \\frac{(15-20)^2}{20} + \\frac{(23-20)^2}{20} + \\frac{(24-20)^2}{20} + \\frac{(16-20)^2}{20}$$\n\n$$= \\frac{25 + 9 + 25 + 9 + 16 + 16}{20} = \\frac{100}{20} = 5.0$$\n\nCon $\\nu = 6 - 1 = 5$ grados de libertad y $\\alpha = 0.05$: $\\chi^2_{0.05, 5} = 11.07$.\n\nComo $5.0 < 11.07$, **no se rechaza $H_0$**. No hay evidencia de que el dado sea cargado.\n\n\n::: {.cell}\n\n```\n#> \n#> \tChi-squared test for given probabilities\n#> \n#> data:  observados\n#> X-squared = 5, df = 5, p-value = 0.4159\n#> Valor crítico chi2(0.05, 5) = 11.0705\n```\n:::\n\n\n:::\n\n::: {.callout-tip icon=false}\n## Ejemplo: ¿Los tiempos de servicio siguen una Normal?\n\nUn banco registra los tiempos de atención (en minutos) de $n=80$ clientes. Se agrupa en clases:\n\n| Clase | $[0,2)$ | $[2,4)$ | $[4,6)$ | $[6,8)$ | $[8,\\infty)$ |\n|:-----:|:-------:|:-------:|:-------:|:-------:|:------------:|\n| $O_i$ | 8 | 22 | 30 | 15 | 5 |\n\nSe estima $\\hat{\\mu} = 4.8$ min y $\\hat{\\sigma} = 1.9$ min de los datos ($p=2$ parámetros).\n\n\n::: {.cell}\n\n```\n#> Frecuencias esperadas:\n#> [1]  5.62 21.33 31.94 17.42  3.69\n#> \n#> Estadístico chi2 = 1.95 \n#> gl = 2 \n#> p-valor = 0.3772\n```\n:::\n\n\n:::\n\n---\n\n### Prueba de Kolmogorov-Smirnov\n\n::: {.callout-note icon=false}\n## Definición: Prueba KS\n\nLa prueba de **Kolmogorov-Smirnov** compara la función de distribución empírica $F_n(x)$ con la cdf teórica $F_0(x)$ propuesta en $H_0$.\n\n$$F_n(x) = \\frac{1}{n}\\sum_{i=1}^{n}\\mathbf{1}\\{X_i \\leq x\\}$$\n\nEl estadístico de prueba mide la máxima discrepancia:\n\n$$D_n = \\sup_{x \\in \\mathbb{R}} |F_n(x) - F_0(x)|$$\n\nSe rechaza $H_0$ si $D_n > d_{\\alpha,n}$ (valor crítico de la tabla KS o p-valor de `ks.test`).\n\n**Ventajas sobre $\\chi^2$:** No requiere agrupar los datos en clases y es exacta para distribuciones continuas con parámetros conocidos.\n\n**Limitación:** Si se estiman parámetros de los datos, el p-valor de `ks.test` es conservador (usar la prueba de Lilliefors para la Normal).\n\n:::\n\n::: {.callout-tip icon=false}\n## Ejemplo: ¿Los tiempos entre llegadas son Exponenciales?\n\nSe registran 50 tiempos entre llegadas a una tienda (en minutos). Se propone $H_0: X \\sim \\text{Exp}(\\lambda)$.\n\n\n::: {.cell}\n\n```\n#> Lambda estimado: 0.2936\n#> Media estimada: 3.4058 min\n#> \n#> \tExact one-sample Kolmogorov-Smirnov test\n#> \n#> data:  datos\n#> D = 0.12381, p-value = 0.3952\n#> alternative hypothesis: two-sided\n```\n\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-docx/ks-exponencial-1.png)\n:::\n:::\n\n\n:::\n\n::: {.callout-note icon=false}\n## Comparación: ¿cuándo usar cada prueba?\n\n| Criterio | $\\chi^2$ de Pearson | Kolmogorov-Smirnov |\n|:---------|:-------------------:|:------------------:|\n| Tipo de datos | Discretos o continuos agrupados | Continuos (sin agrupar) |\n| Tamaño muestral mínimo | $n \\geq 50$, $E_i \\geq 5$ | $n \\geq 25$ |\n| Parámetros estimados | Descuenta $p$ gl fácilmente | P-valor conservador |\n| Sensibilidad | A diferencias en colas | A diferencias globales |\n| Uso típico | Distribuciones discretas, normalidad con clases | Exponencial, Uniforme, continuas en general |\n\n:::\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. En una empresa se registran el número de llamadas de soporte por día durante 100 días. Los resultados son: 0 llamadas (30 días), 1 llamada (35 días), 2 llamadas (20 días), 3 llamadas (10 días), 4 o más (5 días). Pruebe con $\\alpha=0.05$ si los datos siguen una distribución $\\text{Poisson}(\\lambda)$. Estime $\\lambda$ de los datos.\n\n2. Un ingeniero mide el grosor de 60 láminas de acero. Calcule la media y desviación estándar muestral, luego aplique la prueba $\\chi^2$ con 5 clases para determinar si los datos provienen de una distribución Normal.\n\n3. Genere en R 100 observaciones de una $\\text{Gamma}(2, 1)$ y aplique la prueba KS para evaluar si los datos provienen de: (a) $\\text{Exp}(0.5)$ y (b) $\\text{Gamma}(2, 1)$. Compare los p-valores.\n\n4. ¿Por qué la prueba KS pierde validez cuando los parámetros de $F_0$ se estiman de los mismos datos? Investigue la prueba de Lilliefors como alternativa para normalidad.\n\n:::\n\n\n## Ejercicios propuestos\n\n1. Sea $X_1,\\ldots,X_{25}$ muestra aleatoria de $\\text{Ber}(p)$.\n   Calcule $E[S/N]$ y su error estándar, donde $S=\\sum X_i$.\n2. Demuestre que $S_1^2 = \\frac{1}{n-1}\\sum(X_i-\\bar{X})^2$ es\n   consistente para $\\sigma^2$.\n3. Encuentre la información de Fisher $\\mathcal{I}(\\lambda)$ para la\n   distribución $\\text{Poi}(\\lambda)$ y la CICR de $\\lambda$.\n4. Para $X_1,\\ldots,X_n$ muestra de $\\text{Exp}(\\lambda)$, muestre que\n   $T=\\sum X_i$ es suficiente para $\\lambda$ usando el teorema de\n   factorización de Neyman.\n\n## Intervalos de confianza {#sec-intervalos-confianza}\n\n::: {.content-visible when-format=\"html\"}\n[📖 Humberto Martínez Bautista]{.fuente-badge .fuente-humberto}\n\n:::\n\n\nLa **estimación por intervalo** va más allá de un valor único: produce\nun rango de valores plausibles para $\\theta$.\n\n::: {.callout-note icon=false}\n## Intervalo de confianza\n\nSea $\\alpha \\in (0,1)$. Un **intervalo de confianza (IC)** de nivel\n$1-\\alpha$ para $\\theta$ es un intervalo aleatorio\n$(\\hat{\\theta}_L, \\hat{\\theta}_U)$ tal que:\n$$P(\\hat{\\theta}_L \\leq \\theta \\leq \\hat{\\theta}_U) = 1-\\alpha.$$\n\nAl valor $1-\\alpha$ se le llama **coeficiente de confianza** (e.g., 0.95).\n\n:::\n\n**Interpretación frecuentista:** si el procedimiento se repitiera muchas\nveces, el $(1-\\alpha)\\times 100\\%$ de los intervalos construidos\ncontendría al verdadero $\\theta$.\n\n### IC para la media muestral\n\n## Métodos para encontrar pruebas {#sec-metodos-pruebas}\n\n::: {.content-visible when-format=\"html\"}\n[📖 Magín Zúñiga Estrada]{.fuente-badge .fuente-magin}\n\n:::\n\n\n::: {.callout-tip icon=false}\n## Fuente: Apuntes del curso (Prof. Magín Zúñiga Estrada)\n\n:::\n\n### Pruebas de razón de verosimilitud (LRT)\n\nLas pruebas de razón de verosimilitud están íntimamente relacionadas con\nlos estimadores de máxima verosimilitud y son aplicables en gran\nvariedad de situaciones.\n\n::: {.callout-note icon=false}\n## Definición: Estadístico de razón de verosimilitud\n\nSea $X_1,\\ldots,X_n$ muestra aleatoria con densidad $f(x;\\theta)$ y\nfunción de verosimilitud $L(\\theta;\\mathbf{x})=\\prod_{i=1}^n f(x_i;\\theta)$.\nPara probar $H_0:\\theta\\in\\Theta_0$ vs. $H_1:\\theta\\in\\Theta_0^c$, el\n**estadístico de razón de verosimilitud** es:\n$$\\lambda(\\mathbf{x}) = \\frac{\\sup_{\\theta\\in\\Theta_0} L(\\theta;\\mathbf{x})}\n  {\\sup_{\\theta\\in\\Theta} L(\\theta;\\mathbf{x})}.$$\n\nUna **prueba LRT** rechaza $H_0$ cuando $\\lambda(\\mathbf{x})\\leq c$,\ncon $0\\leq c\\leq 1$.\n\n:::\n\n::: {.callout-tip icon=false}\n## Ejemplo: LRT para media normal con varianza conocida\n\nSea $X_1,\\ldots,X_n \\sim N(\\theta,1)$. Para probar\n$H_0:\\theta=\\theta_0$ vs. $H_1:\\theta\\neq\\theta_0$, el EMV es\n$\\hat{\\theta}=\\bar{X}$, y la estadística LRT resulta:\n$$\\lambda(\\mathbf{x}) = \\exp\\!\\left[-\\frac{n(\\bar{x}-\\theta_0)^2}{2}\\right].$$\n\nLa región de rechazo $\\lambda(\\mathbf{x})\\leq c$ equivale a:\n$$|\\bar{x}-\\theta_0| \\geq \\sqrt{-2\\log(c)/n},$$\nque corresponde a la prueba bilateral usual sobre $\\bar{X}$.\n\n:::\n\n::: {.callout-tip icon=false}\n## Ejemplo: LRT para distribución exponencial desplazada\n\nSea $X_i \\sim f(x;\\theta) = e^{-(x-\\theta)} \\mathbf{1}_{x\\geq\\theta}$\ny $H_0:\\theta\\leq\\theta_0$ vs. $H_1:\\theta>\\theta_0$. El estadístico\nLRT es:\n$$\\lambda(\\mathbf{x}) = \\begin{cases}\n  1 & \\text{si } X_{(1)} \\leq \\theta_0, \\\\\n  e^{-n(X_{(1)}-\\theta_0)} & \\text{si } X_{(1)} > \\theta_0.\n\\end{cases}$$\n\nLa LRT rechaza $H_0$ si $X_{(1)} \\geq c$, con $c$ elegida para\ncontrolar el error tipo I.\n\n:::\n\n**Conexión con suficiencia:** Si $T(\\mathbf{X})$ es suficiente para\n$\\theta$, la LRT basada en la muestra completa y la basada en $T$ son\nequivalentes.\n\n### Función potencia\n\n::: {.callout-note icon=false}\n## Definición: Función potencia\n\nDada una región de rechazo $R$, la **función potencia** de la prueba es:\n$$\\gamma(\\theta) = P(\\mathbf{X}\\in R\\mid\\theta).$$\n\nEsta función cumple:\n$$\\gamma(\\theta) = \\begin{cases}\n  \\text{prob. de Error Tipo I} & \\text{si } \\theta\\in\\Theta_0, \\\\\n  1 - \\text{prob. de Error Tipo II} & \\text{si } \\theta\\in\\Theta_0^c.\n\\end{cases}$$\n\nUna **prueba de tamaño $\\alpha$** satisface $\\alpha = \\sup_{\\theta\\in\\Theta_0}\\gamma(\\theta)$.\nUna **prueba de nivel $\\alpha$** satisface $\\alpha \\geq \\sup_{\\theta\\in\\Theta_0}\\gamma(\\theta)$.\n\n:::\n\n::: {.callout-tip icon=false}\n## Ejemplo: Función potencia para prueba binomial\n\nSea $X\\sim\\text{Bin}(5,\\theta)$. Para $H_0:\\theta\\leq 0.5$ vs.\n$H_1:\\theta>0.5$:\n\n- Prueba 1 (rechaza si $X=5$): $\\gamma_1(\\theta)=\\theta^5$, error tipo I\n  máximo $= (0.5)^5 = 0.03$.\n- Prueba 2 (rechaza si $X\\geq 3$): $\\gamma_2(\\theta)=\\sum_{k=3}^5\\binom{5}{k}\\theta^k(1-\\theta)^{5-k}$,\n  mayor potencia pero también mayor error tipo I.\n\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-docx/potencia-binomial-1.png){fig-align='center'}\n:::\n:::\n\n\n### Pruebas uniformemente más potentes (UMP) — Lema de Neyman-Pearson\n\n::: {.callout-note icon=false}\n## Definición: Prueba UMP\n\nSea $\\mathcal{C}$ una clase de pruebas de nivel $\\alpha$ para\n$H_0:\\theta\\in\\Theta_0$ vs. $H_1:\\theta\\in\\Theta_0^c$. Una prueba en\n$\\mathcal{C}$ con función potencia $\\gamma(\\theta)$ es **uniformemente\nmás potente (UMP)** en $\\mathcal{C}$ si:\n$$\\gamma(\\theta) \\geq \\gamma'(\\theta) \\quad \\forall\\,\\theta\\in\\Theta_0^c,$$\npara toda $\\gamma'$ función potencia de cualquier otra prueba en\n$\\mathcal{C}$.\n\n:::\n\n::: {.callout-note icon=false}\n## Teorema: Lema de Neyman-Pearson\n\nPara probar $H_0:\\theta=\\theta_0$ vs. $H_1:\\theta=\\theta_1$, sea $R$ la\nregión de rechazo tal que:\n$$\\mathbf{x}\\in R \\iff f(\\mathbf{x};\\theta_1) > k\\,f(\\mathbf{x};\\theta_0),$$\ncon $k\\geq 0$ y $\\alpha = P(\\mathbf{X}\\in R\\mid\\theta=\\theta_0)$.\n\nEntonces:\n\n1. **(Suficiencia)** Esta prueba es UMP de nivel $\\alpha$.\n2. **(Necesidad)** Si existe tal prueba con $k>0$, toda prueba UMP de\n   nivel $\\alpha$ tiene tamaño $\\alpha$ y satisface la condición anterior\n   salvo en un conjunto de probabilidad cero.\n\n**Corolario (estadístico suficiente):** Si $T(\\mathbf{X})$ es suficiente\npara $\\theta$ y $g(t;\\theta_i)$ es su densidad, la prueba UMP de nivel\n$\\alpha$ puede construirse rechazando $H_0$ cuando\n$g(T;\\theta_1) > k\\,g(T;\\theta_0)$.\n\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-docx/neyman-pearson-demo-1.png){fig-align='center'}\n:::\n:::\n\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. Sea $X_1,\\ldots,X_n \\sim N(\\theta,\\sigma^2)$ con $\\sigma^2$ conocida.\n   Use el lema de Neyman-Pearson para encontrar la prueba UMP de nivel\n   $\\alpha$ para $H_0:\\theta=\\theta_0$ vs. $H_1:\\theta=\\theta_1>\\theta_0$.\n2. Para $X\\sim\\text{Bin}(10,p)$ y $H_0:p=0.3$ vs. $H_1:p=0.7$, encuentre\n   la región de rechazo de tamaño $\\alpha\\leq 0.05$ basada en el lema\n   de Neyman-Pearson.\n3. Sea $X_1,\\ldots,X_n \\sim \\text{Exp}(\\lambda)$. Encuentre la prueba LRT\n   de nivel $\\alpha$ para $H_0:\\lambda=\\lambda_0$ vs.\n   $H_1:\\lambda\\neq\\lambda_0$.\n4. Grafique la función potencia de la prueba del ejercicio anterior para\n   $\\lambda_0=1$, $n=15$, $\\alpha=0.05$.\n\n:::\n\n\n## Resumen del capítulo\n\n| Distribución | Origen | Parámetros | $E[X]$ | $\\text{Var}(X)$ | Uso típico |\n|:-------------|:------:|:----------:|:------:|:---------------:|:-----------|\n| $\\chi^2_\\nu$ | $\\sum_{i=1}^\\nu Z_i^2$ | $\\nu$ (g.l.) | $\\nu$ | $2\\nu$ | Pruebas sobre varianzas |\n| $t_\\nu$ | $Z/\\sqrt{\\chi^2_\\nu/\\nu}$ | $\\nu$ (g.l.) | $0$ ($\\nu>1$) | $\\nu/(\\nu-2)$ | IC y pruebas sobre $\\mu$ con $\\sigma^2$ desconocida |\n| $F_{\\nu_1,\\nu_2}$ | $\\chi^2_{\\nu_1}/\\chi^2_{\\nu_2}$ | $\\nu_1, \\nu_2$ | $\\nu_2/(\\nu_2-2)$ | — | Comparación de varianzas |\n\n::: {.callout-note icon=false}\n## Distribuciones muestrales clave\n\nDada una muestra aleatoria $X_1,\\ldots,X_n \\sim N(\\mu,\\sigma^2)$:\n\n$$\\bar{X} \\sim N\\!\\left(\\mu,\\frac{\\sigma^2}{n}\\right), \\qquad\n\\frac{(n-1)S^2}{\\sigma^2} \\sim \\chi^2_{n-1}, \\qquad\n\\frac{\\bar{X}-\\mu}{S/\\sqrt{n}} \\sim t_{n-1}$$\n\nPara muestras **grandes** (cualquier distribución), el TCL garantiza:\n$$\\bar{X} \\approx N\\!\\left(\\mu,\\frac{\\sigma^2}{n}\\right), \\qquad\n\\hat{P} \\approx N\\!\\left(p,\\frac{p(1-p)}{n}\\right)$$\n\n:::\n\n::: {.callout-tip icon=false}\n## Ideas clave del capítulo\n\n- Un **parámetro** ($\\mu, \\sigma^2, p$) es una constante poblacional desconocida; un **estimador** ($\\bar{X}, S^2, \\hat{P}$) es una variable aleatoria calculada con la muestra.\n- Un estimador es **insesgado** si $E[\\hat{\\theta}] = \\theta$, **consistente** si converge en probabilidad al parámetro, y **eficiente** si minimiza la varianza entre los insesgados.\n- Las distribuciones $\\chi^2$, $t$ y $F$ son herramientas para construir intervalos de confianza y pruebas de hipótesis en poblaciones normales.\n- El **Teorema del Límite Central** aplica a $\\bar{X}$ (y $\\hat{P}$), no a los datos individuales. Con $n \\geq 30$, la aproximación suele ser excelente.\n\n:::\n\n## Cierre del curso\n\nCon este capítulo completamos el recorrido del curso: de la probabilidad básica y las distribuciones discretas, pasando por las distribuciones continuas y conjuntas, hasta llegar a la inferencia estadística. Las distribuciones muestrales que aquí estudiamos — $\\chi^2$, $t$, $F$ y el TLC — son los cimientos sobre los que se construyen los temas avanzados de estadística: intervalos de confianza, pruebas de hipótesis, regresión y modelos lineales generalizados. El pensamiento probabilístico y la distinción entre parámetro y estimador que desarrollaste aquí te acompañarán en cualquier análisis estadístico futuro.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}