{
  "hash": "71a339e56e5a0cc8606882d69e7b1ae2",
  "result": {
    "engine": "knitr",
    "markdown": "# Distribuciones Muestrales {#cap-inferencia}\n\nEn esta unidad, estudiaremos las distribuciones generadas por características medidas a conjuntos de individuos (muestras). Antes de revisar las distribuciones de muestreo se definen conceptos importantes en la modelación estadística.\n\nEn este capítulo estudiaremos los conceptos básicos de la inferencia estadística: población, muestra aleatoria, parámetros y estimadores. A partir de ahí revisaremos las distribuciones muestrales de los principales estimadores (la media $\\bar{X}$, la varianza $S^2$ y la proporción $\\hat{P}$), así como las distribuciones teóricas asociadas (Chi-cuadrada, $t$ de Student y $F$ de Fisher), que nos permiten calcular probabilidades sobre el comportamiento de las muestras. Cerraremos el capítulo con el Teorema del Límite Central, una de las herramientas más importantes de la estadística inferencial. A lo largo del capítulo se incluyen ejemplos resueltos y ejercicios propuestos para practicar los conceptos.\n\n## Población\n\nUna población es un conjunto de elementos, objetos o seres vivos con características comunes $A$, $B$, $C$, $D$ y no comunes $E$, $F$, $G$ (que varían de un sujeto a otro).\n\nUn ejemplo de un conjunto de $n$ individuos con características similares, en cada individuo $i$, serían aquellos individuos con las siguientes características: \\* $A = \\text{Adultos}$ \\* $B = \\text{Viven en Jalisco}$ \\* $C = \\text{Sanos}$\n\nEn cada individuo $i$ se obtienen las siguientes observaciones o mediciones: $$Y_i = \\{Estatura, Ingreso, Hemoglobina\\}$$\n\nAlgunas características no comunes en los $n$ individuos, es decir, características que varían significativamente del individuo $i$ versus el individuo $j$ ($i \\neq j$) podrían ser: \\* $E$: Grupo sanguíneo \\* $F$: Origen étnico \\* $G$: Tipo de alimentación \\* $H$: Tipo de trabajo \\* $I$: Escolaridad\n\nSupongamos que nos interesa estudiar el “ingreso medio” de la población masculina obrera que labora en la ciudad de Aguascalientes en el sector automotriz, entonces: $$Y_i: \\text{Ingreso mensual}$$\n\nEn este ejemplo la población de interés posee las siguientes características comunes: \\* $A$: Masculino \\* $B$: Obrero \\* $C$: Labora en Aguascalientes \\* $D$: En sector automotriz\n\nPor otra parte, la lista de características no comunes: \\* $E$: Edad \\* $F$: Tipo de contratación \\* $G$: Años de experiencia\n\nSe esperaría que las variables no comunes tengan poca influencia sobre la variable de respuesta: “Ingreso mensual”, que puedan afectar su comportamiento al realizar un estudio, o en su defecto, en el diseño del experimento deben de controlarse adecuadamente, quizás con algún método de estratificación y seguramente en la definición de la población objetivo de interés, utilizando criterios de exclusión y de inclusión.\n\n::: {.callout-note icon=false}\n## Nota\nEn la teoría estadística, la población no solo es el conjunto de individuos u objetos físicos, sino el **conjunto completo de mediciones o respuestas** de interés para el experimentador. Por lo tanto, si nos interesa el ingreso mensual, la población conceptual estaría formada por todos los valores monetarios posibles de ese grupo, más que por los individuos mismos. Los valores numéricos constantes que resumen las características de esta población en su totalidad (como el verdadero ingreso medio $\\mu$ o la varianza del ingreso $\\sigma^2$) reciben el nombre de **parámetros**.\n:::\n\n## Muestra aleatoria\n\nSi de una población bajo estudio, digamos con una distribución de probabilidad $P(x; \\theta)$, seleccionamos un elemento al azar y medimos una característica de interés, se generará un dato que \"asumimos\" poseerá las mismas propiedades de la población general.\n\n**Ejemplo didáctico:** Supongamos que analizamos la resistencia a la tensión de ciertos componentes de acero producidos en una fábrica. Asumimos que en la población, la variable \"resistencia\" sigue una distribución normal con parámetros: media $\\mu = 65 \\text{ kg/mm}^2$ y varianza $\\sigma^2 = 4 \\text{ kg/mm}^2$. Cualquier componente que se seleccione al azar de esa población conservará, en términos probabilísticos, las características de la población entera.\n\nUna muestra es una subcolección de observaciones de $n$ individuos o elementos que pertenecen a una población de tamaño $N$ (donde $N \\ge n$).\n\nSi a un componente extraído de la población $P(x; \\theta)$ se le mide su resistencia y resulta ser 66.5 kg/mm², esto se expresa de la siguiente manera: $$x = 66.5 \\text{ kg/mm}^2$$\n\nLa expresión anterior señala que $x$ representa una *medición específica* de la característica en un elemento perteneciente a la población.\n\n¿Es $X$ una variable aleatoria? La respuesta es “sí”, porque si se realiza la medición a otro componente distinto, su valor no necesariamente será el mismo (otra medición posible sería $x = 63.2 \\text{ kg/mm}^2$). Notemos que $x \\in S_X$ (el soporte de la variable) y que su resultado no es constante. Si se obtuviera un gran número de mediciones, el comportamiento de los datos mostraría una regularidad similar al de las variables aleatorias teóricas (Normal, Uniforme, Poisson, etc.). A este valor observado $x$ se le denomina una **realización** de la variable aleatoria $X$.\n\nEn estadística, no se trabaja con un único individuo, sino con una colección o muestra de variables aleatorias asociadas a $n$ elementos. Para que la inferencia estadística sea válida, Wackerly, Mendenhall y Scheaffer establecen que esta recolección debe cumplir con ciertas propiedades matemáticas rigurosas:\n\n> **Muestra aleatoria:** Es un conjunto de variables aleatorias $X_1, X_2, \\dots, X_n$ que son **independientes e idénticamente distribuidas (v.a.i.i.d.)**.\n>\n> -   **Idénticamente distribuidas:** Significa que cada elemento de la muestra tiene exactamente la misma función de densidad o masa de probabilidad que la población de la cual proviene.\n> -   **Independientes:** Significa que el resultado de una medición no afecta ni aporta información sobre el resultado de otra medición dentro de la muestra.\n\nPara referirnos a esta muestra teórica de $n$ variables aleatorias se utiliza la notación en mayúsculas: $$X_1, X_2, X_3, \\dots, X_n$$\n\nCuando se obtienen las mediciones reales en el laboratorio o campo (supongamos $n=4$), la *realización de la muestra* de variables aleatorias se escribe con letras minúsculas: $$x_1 = 65.1, \\quad x_2 = 62.8, \\quad x_3 = 67.5, \\quad x_4 = 64.9$$\n\nEn el análisis de datos, se hace uso de estas realizaciones (muestras observadas) para obtener estadísticas descriptivas, ajustar modelos probabilísticos y, posteriormente, extrapolar (inferir) los resultados a la población original.\n\nA partir de una realización de muestra aleatoria (por ejemplo, $n=100$ observaciones de resistencia), podemos construir un histograma. Si la muestra es representativa, este histograma se ajustará bien a la curva de densidad poblacional original.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# Fijamos una semilla para reproducibilidad\nset.seed(123) \n\n# Parámetros poblacionales\nn <- 100\nmu_pob <- 65\nsigma_pob <- 2 # Desviación estándar (raíz cuadrada de la varianza 4)\n\n# Realización de la muestra aleatoria\nrealizacion_muestra <- data.frame(\n  resistencia = rnorm(n, mean = mu_pob, sd = sigma_pob)\n)\n\n# Construcción del histograma y superposición de la curva teórica\nggplot(realizacion_muestra, aes(x = resistencia)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 15,\n                 fill = \"skyblue\", color = \"black\", alpha = 0.7) +\n  stat_function(fun = dnorm, args = list(mean = mean(realizacion_muestra$resistencia),\n                                         sd = sd(realizacion_muestra$resistencia)),\n                color = \"red\", linewidth = 1.2) +\n  theme_minimal() +\n  labs(\n    title = \"Histograma de la realización de la muestra\",\n    subtitle = \"La curva roja aproxima la distribución de la población original\",\n    x = expression(\"Resistencia a la tensión (kg/mm\"^2*\")\"),\n    y = \"Densidad\"\n  )\n```\n\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-html/muestra_aleatoria-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nComo la realización de la muestra indica que los datos provienen de una variable aleatoria normal, la notación matemática para cada una de las variables aleatorias antes de ser observadas es: $$X_1 \\sim N(\\mu = 65, \\sigma^2 = 4)$$ $$X_2 \\sim N(\\mu = 65, \\sigma^2 = 4)$$ $$\\vdots$$ $$X_n \\sim N(\\mu = 65, \\sigma^2 = 4)$$\n\n*(Nota: El símbolo* $\\sim$ es un operador estadístico que indica \"se distribuye como\").\n\nDado que las variables $X_1, X_2, \\dots, X_n$ provienen de una misma población y son independientes, a la variable aleatoria general $X$ que describe la característica en toda la población se le atribuye este comportamiento fundamental: $$X \\sim N(65, 4)$$\n\n## Estimadores de parámetros\n\nLos seres humanos tenemos características propias que nos definen. Por ejemplo, características anatómicas: tipo de rostro (redondo, alargado), ojos (grandes o pequeños), color de ojos (cafés, negros, etcétera), color de piel (moreno, claro, negro), estatura, etcétera. De manera que al mencionar todas sus características de la persona podremos definirla.\n\nHaciendo una analogía a las características anatómicas que empleamos para describir a una persona, la estadística también tiene sus propios elementos (parámetros) para poder caracterizar a una población.\n\nUn parámetro es una constante (cantidad numérica) propia de una población.\n\nComo tú ya habrás leído en la sección 4.2 de esta lectura, la función de densidad de probabilidad de una variable aleatoria normal queda establecida una vez conocido el valor de la media y la varianza, ambos son sus parámetros. En la práctica es poco común tener información de toda la población, por lo que se vuelve práctico trabajar con muestras. El hecho de trabajar con muestras y no con poblaciones, hace que no se conozca exactamente el valor del parámetro. La manera en que a través de una muestra se pueda estimar el valor de un parámetro de una población es mediante el uso de una función denominada estimador.\n\nUn estimador es una función matemática expresada únicamente en términos de los valores de la muestra empleada (es decir, es un estadístico) con el propósito de estimar un parámetro desconocido de la población.\n\nLa tabla siguiente muestra los parámetros que en esta lectura estudiaremos con sus correspondientes estimadores.\n\n**Ejemplo 1**\n\nSupongamos que una fábrica de componentes electrónicos produce un lote masivo de $N = 10,000$ resistencias eléctricas en un turno. El gerente de calidad está interesado en conocer tres **parámetros** fundamentales de esta población (lote completo):\n\n1.  La **media** de la resistencia eléctrica (en ohmios).\n2.  La **varianza** (para medir qué tan consistente es el proceso de fabricación).\n3.  La **proporción** de resistencias defectuosas (aquellas que no cumplen con los estándares mínimos).\n\nDado que probar las $10,000$ resistencias detendría la producción y sería muy costoso, el gerente decide extraer una muestra aleatoria de $n = 5$ resistencias y aplicar los **estimadores** correspondientes definidos en la Tabla 1.\n\n**Tabla 1. Parámetros, estimadores y estimaciones.**\n\n| Característica | Parámetro | Estimador | Estimación |\n|:---|:---|:---|:---|\n| **Media** | $\\mu = \\frac{\\sum_{i=1}^N X_i}{N}$ | $\\bar{X} = \\frac{\\sum_{i=1}^n X_i}{n}$ | $\\bar{x} = \\frac{\\sum_{i=1}^n x_i}{n}$ |\n| **Varianza** | $\\sigma^2 = \\frac{\\sum_{i=1}^N (X_i - \\mu)^2}{N}$ | $S^2 = \\frac{\\sum_{i=1}^n (X_i - \\bar{X})^2}{n-1}$ | $s^2 = \\frac{\\sum_{i=1}^n (x_i - \\bar{x})^2}{n-1}$ |\n| **Proporción** | $P = \\frac{X}{N}$ | $\\bar{P} = \\frac{X}{n}$ | $\\bar{p} = \\frac{x}{n}$ |\n\n*(Nota: En el caso de la proporción,* $X$ y $x$ en los numeradores representan el conteo de \"éxitos\" o elementos que cumplen la característica de interés en la población y en la muestra, respectivamente).\n\n**Recolección de datos (Realización de la muestra)**\n\nAl medir las $n = 5$ resistencias en el laboratorio, se obtienen los siguientes valores (en ohmios): $$x_1 = 101.2, \\quad x_2 = 98.5, \\quad x_3 = 102.1, \\quad x_4 = 99.0, \\quad x_5 = 99.2$$\n\nAl inspeccionarlas físicamente, el ingeniero determina que la resistencia $x_2$ (98.5 ohmios) está defectuosa porque sus terminales están dobladas. Por lo tanto, en nuestra muestra hay $x = 1$ artículo defectuoso.\n\n**Cálculo de las estimaciones**\n\nAhora procedemos a calcular las **estimaciones** (los valores numéricos fijos) sustituyendo nuestras observaciones en las fórmulas de los estimadores:\n\n**1. Estimación (**$\\bar{x}$): $$\\bar{x} = \\frac{101.2 + 98.5 + 102.1 + 99.0 + 99.2}{5} = \\frac{500.0}{5} = 100.0 \\text{ ohmios}$$ *Conclusión:* Estimamos que la verdadera media poblacional $\\mu$ del lote completo de 10,000 piezas es de aproximadamente 100.0 ohmios.\n\n**2. Estimación (**$s^2$): Primero calculamos las desviaciones al cuadrado de cada dato respecto a la media muestral ($\\bar{x} = 100.0$): \\* $(101.2 - 100.0)^2 = 1.44$ \\* $(98.5 - 100.0)^2 = 2.25$ \\* $(102.1 - 100.0)^2 = 4.41$ \\* $(99.0 - 100.0)^2 = 1.00$ \\* $(99.2 - 100.0)^2 = 0.64$\n\nSuma de cuadrados $= 1.44 + 2.25 + 4.41 + 1.00 + 0.64 = 9.74$\n\n$$s^2 = \\frac{9.74}{5 - 1} = \\frac{9.74}{4} = 2.435 \\text{ ohmios}^2$$ *Conclusión:* Estimamos que la varianza poblacional $\\sigma^2$ del proceso es 2.435 ohmios, por lo tanto el proceso varía en $\\sqrt{s}=\\pm1.5604$ ohmios.\n\n**3. Estimación de (**$\\bar{p}$): Dado que encontramos 1 resistencia defectuosa de las 5 revisadas: $$\\bar{p} = \\frac{1}{5} = 0.20$$ *Conclusión:* Estimamos que el 20% del lote completo de 10,000 resistencias presenta defectos.\n\n**Representación Gráfica del Ejemplo: Muestra vs. Población Estimada**\n\nEl siguiente gráfico superpone las observaciones individuales reales de nuestra muestra pequeña ($n=5$) con la curva de distribución Normal teórica que inferimos para toda la producción ($N=10,000$), usando la media estimada ($\\bar{x} = 100.0$) y la desviación estándar estimada ($s = \\sqrt{2.435} \\approx 1.56$).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Definir los datos de la muestra (Realizaciones)\ndf_muestra <- data.frame(\n  resistencia = c(101.2, 98.5, 102.1, 99.0, 99.2),\n  y_pos = rep(0, 5) # Altura 0 para poner los puntos sobre el eje horizontal\n)\n\n# 2. Definir las estimaciones calculadas previamente\nmedia_est <- 100.0\nvarianza_est <- 2.435\ndesviacion_est <- sqrt(varianza_est)\n\n# 3. Crear el gráfico\nggplot() +\n  # Curva de densidad de la POBLACIÓN ESTIMADA\n  stat_function(data = data.frame(x = c(94, 106)), aes(x = x), \n                fun = dnorm, args = list(mean = media_est, sd = desviacion_est), \n                color = \"darkgray\", linewidth = 1.2, fill = \"lightgray\", alpha = 0.3, geom = \"area\") +\n  \n  # Puntos observados de la MUESTRA (Realización)\n  geom_point(data = df_muestra, aes(x = resistencia, y = y_pos), \n             color = \"darkblue\", size = 5, alpha = 0.8) +\n  \n  # Línea representativa del ESTIMADOR (Media muestral)\n  geom_vline(xintercept = media_est, color = \"red\", linetype = \"dashed\", linewidth = 1.2) +\n  \n  # Etiquetas y anotaciones didácticas\n  annotate(\"text\", x = media_est + 0.3, y = 0.20, \n           label = expression(bar(x) == 100.0), color = \"red\", size = 6, fontface = \"bold\", hjust = 0) +\n  annotate(\"text\", x = 103, y = 0.10, \n           label = \"Curva de la población\\nestimada N(100, 2.435)\", color = \"gray30\", size = 4) +\n  annotate(\"text\", x = 101.2, y = 0.02, \n           label = \"Muestra (n=5)\", color = \"darkblue\", size = 4) +\n  \n  # Estética general\n  theme_minimal() +\n  labs(\n    title = \"Inferencia Estadística: Control de Calidad\",\n    subtitle = \"A partir de 5 puntos (azules), estimamos el comportamiento de 10,000 resistencias (área gris)\",\n    x = \"Resistencia Eléctrica (ohmios)\",\n    y = \"Densidad / Probabilidad\"\n  ) +\n  scale_x_continuous(breaks = seq(94, 106, by = 1)) +\n  coord_cartesian(ylim = c(0, 0.27)) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14),\n    axis.text.x = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-html/grafica_ejemplo_resistencias-1.png){fig-align='center' width=768}\n:::\n:::\n\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. Una muestra aleatoria de tamaño $n=8$ pesos (en kg) de paquetes de arroz es: 1.02, 0.98, 1.01, 1.00, 0.99, 1.03, 0.97, 1.00. Calcule la estimación de la media $\\bar{x}$ y de la varianza $s^2$.\n2. De un lote de 500 piezas se revisan 20 y se encuentran 3 defectuosas. Calcule la estimación de la proporción de piezas defectuosas $\\bar{p}$ en el lote.\n3. Explique con sus propias palabras la diferencia entre un parámetro y un estimador, y entre un estimador y una estimación.\n:::\n\n## Distribución muestral de un estimador\n\nComo ya hemos visto, una vez que se tienen los datos observados de una muestra, se calculan ciertas funciones llamadas estimadores que nos permiten inferir las características de la población estudiada. Los datos son realizaciones de variables aleatorias; por lo tanto, **los estimadores también son variables aleatorias** antes de que la muestra sea extraída. Al ser una variable aleatoria, todo estimador cuenta con una función de densidad o de probabilidad, a la cual llamaremos **distribución muestral del estimador**.\n\nLos estimadores \"aproximan\" a los parámetros poblacionales. Esto quiere decir que, aunque una estimación puntual nunca coincidirá de manera exacta con el parámetro (debido a la variabilidad aleatoria de la muestra), si la muestra fue seleccionada correctamente y es lo suficientemente grande, el resultado tenderá a concentrarse muy cerca del valor real del parámetro.\n\n> **Distribución muestral de un estimador:** Es la distribución teórica de probabilidad de todos los posibles valores que puede tomar un estimador, calculados a partir de todas las muestras posibles de tamaño $n$ extraídas de la misma población.\n\nLa distribución muestral proporciona:\n\n1.  El soporte de la variable, es decir, la lista de todos los posibles valores que puede tomar el estimador.\n2.  La probabilidad (o densidad de probabilidad) asociada a cada uno de esos valores, lo que nos permite medir el error de estimación.\n\nA continuación, estudiaremos las distribuciones muestrales teóricas para los estimadores de la media ($\\bar{X}$), la varianza ($S^2$) y la relación de esta última con la distribución Chi-cuadrada.\n\n------------------------------------------------------------------------\n\n## Distribución muestral de promedios ($\\bar{X}$)\n\nSi $X_1, X_2, \\dots, X_n$ representan una muestra aleatoria extraída de una población infinita (o con reemplazo) que posee una media $\\mu$ y una varianza $\\sigma^2$, entonces las propiedades del estimador media muestral $\\bar{X} = \\frac{\\sum_{i=1}^n X_i}{n}$ son:\n\n**Esperanza matemática (Valor esperado):** $$E[\\bar{X}] = \\mu_{\\bar{X}} = \\mu \\quad (1)$$ *(Esto demuestra que* $\\bar{X}$ es un estimador insesgado: en promedio, acierta al parámetro).\n\n**Varianza del estimador:** $$Var(\\bar{X}) = \\sigma_{\\bar{X}}^2 = \\frac{\\sigma^2}{n} \\quad (2)$$ *(Esto demuestra que a mayor tamaño de muestra* $n$, menor es la varianza del estimador, haciendo nuestras estimaciones más precisas).\n\n> *Nota: Cuando la muestra se realiza **sin reemplazo** desde una población finita de tamaño* $N$, la esperanza sigue siendo $\\mu$, pero la varianza se ajusta multiplicándola por el factor de corrección por población finita: \\> $$Var(\\bar{X}) = \\frac{\\sigma^2}{n} \\left(\\frac{N-n}{N-1}\\right) \\quad (2.1)$$\n\n**La forma de la distribución de** $\\bar{X}$\n\nIndependientemente de si calculamos la esperanza y la varianza por fuerza bruta (enumerando todas las combinaciones posibles), la pregunta fundamental en inferencia es: ¿Qué forma geométrica tiene la distribución de $\\bar{X}$?\n\nLa teoría estadística (Teorema de la combinación lineal de normales) establece que: Si las variables aleatorias $X_1, X_2, \\dots, X_n$ provienen de una **población normal** con media $\\mu$ y varianza $\\sigma^2$, entonces la distribución exacta del estimador $\\bar{X}$ también será Normal. $$\\bar{X} \\sim N\\left(\\mu_{\\bar{X}} = \\mu, \\sigma_{\\bar{X}}^2 = \\frac{\\sigma^2}{n}\\right)$$\n\nConociendo esta distribución matemática exacta, es posible calcular probabilidades sobre el comportamiento de nuestras muestras.\n\n**Ejemplo:** El coeficiente intelectual (CI) de los alumnos de un centro escolar se distribuye como una variable aleatoria Normal con $\\mu = 80$ y varianza $\\sigma^2 = 100$. Si se extrae una muestra aleatoria de $n=25$ alumnos.\n\n**¿Cuál es la probabilidad de que el CI promedio de esa muestra en particular sea mayor a 75 puntos?**\n\nDefinimos $X$: CI de un alumno $\\sim N(80, 10^2)$. Como la población es normal, la distribución de la media muestral será: $$\\bar{X} \\sim N\\left(\\mu_{\\bar{X}} = 80, \\sigma_{\\bar{X}}^2 = \\frac{100}{25} = 4\\right)$$\n\nLa desviación estándar de la media muestral (conocida como error estándar) es $\\sqrt{4} = 2$. La probabilidad de interés es calcular el área a la derecha de 75: $P(\\bar{X} > 75)$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# En R, usamos pnorm para calcular el área acumulada a la izquierda y restamos de 1.\n# pnorm(q, mean, sd) -> mean = 80, sd = sqrt(4) = 2\nprob_mayor_75 <- 1 - pnorm(75, mean = 80, sd = 2)\nround(prob_mayor_75, 3)\n#> [1] 0.994\n```\n:::\n\n\nLa probabilidad de que la media muestral exceda los 75 puntos es de **0.994** (o 99.4%). *(Nota didáctica: Al ser el error estándar muy pequeño (2), es casi seguro que el promedio de un grupo de 25 alumnos estará muy cerca de la media real de 80, por eso la probabilidad de que sea mayor a 75 es tan alta).*\n\n------------------------------------------------------------------------\n\n## Esperanza o media del estimador de la varianza ($S^2$)\n\nSi $X_1, X_2, \\dots, X_n$ representan una muestra aleatoria, el estimador insesgado de la varianza poblacional se define como: $$S^2 = \\frac{\\sum_{i=1}^n (X_i - \\bar{X})^2}{n-1}$$\n\nLa propiedad fundamental de este estimador es que su valor esperado es exactamente igual al parámetro poblacional que intenta estimar: $$E[S^2] = \\sigma^2 \\quad (5)$$\n\nA diferencia del estimador de la media ($\\bar{X}$), cuya distribución puede modelarse directamente con la campana de Gauss, el estimador de la varianza ($S^2$) suma números que están elevados al cuadrado. Dado que un cuadrado nunca puede ser negativo, la distribución de $S^2$ no puede ser simétrica ni abarcar números negativos. Para estudiar probabilísticamente a la varianza, debemos introducir una nueva familia matemática: la distribución Chi-cuadrada.\n\n------------------------------------------------------------------------\n\n## Distribución $\\chi^2$ (Chi-cuadrada)\n\nLa distribución $\\chi^2$ es un pilar de la inferencia estadística, estrechamente vinculada a la distribución Normal. Supongamos que tenemos una variable aleatoria de interés que sigue una distribución normal: $X \\sim N(\\mu, \\sigma^2)$. Si seleccionamos una muestra aleatoria $X_1, X_2, \\dots, X_n$, es lógico suponer que cada observación se comporta como una normal.\n\nA continuación, transformamos (estandarizamos) estas variables normales restándoles su media poblacional y dividiéndolas por su desviación estándar poblacional: $$Z_i = \\frac{X_i - \\mu}{\\sigma}$$ Cada $Z_i$ ahora es una Normal Estándar $N(0, 1)$.\n\nSi elevamos al cuadrado cada una de estas variables estandarizadas independientes y las sumamos, generamos una nueva variable aleatoria matemática: $$\\sum_{i=1}^n Z_i^2 = \\left(\\frac{X_1 - \\mu}{\\sigma}\\right)^2 + \\left(\\frac{X_2 - \\mu}{\\sigma}\\right)^2 + \\dots + \\left(\\frac{X_n - \\mu}{\\sigma}\\right)^2$$\n\n> **Definición:** Una variable aleatoria Chi-cuadrada se define como la suma de variables aleatorias independientes, cada una con distribución Normal Estándar elevada al cuadrado.\n\nPor su propia naturaleza de suma de cuadrados, el soporte (campo de variación) de una variable $\\chi^2$ es estrictamente no negativo, de $0$ a $+\\infty$. Se simboliza como $\\chi^2_n$, donde $n$ representa los **grados de libertad** (el número de variables normales independientes que se están sumando).\n\n**Propiedades teóricas:** Para una variable $Y \\sim \\chi^2_n$: \\* Esperanza: $E[Y] = n$ \\* Varianza: $Var(Y) = 2n$\n\nEl parámetro único que define a esta distribución son sus grados de libertad $n$. En la figura siguiente se muestra cómo la forma fuertemente asimétrica a la derecha (sesgada) de la distribución $\\chi^2$ va cambiando a medida que aumentan los grados de libertad.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nx_val <- seq(0, 20, length.out = 500)\ndf_chi <- data.frame(\n  x = rep(x_val, 3),\n  densidad = c(dchisq(x_val, df=2), dchisq(x_val, df=5), dchisq(x_val, df=10)),\n  grados = factor(rep(c(\"n = 2\", \"n = 5\", \"n = 10\"), each=500), levels = c(\"n = 2\", \"n = 5\", \"n = 10\"))\n)\n\nggplot(df_chi, aes(x=x, y=densidad, color=grados)) +\n  geom_line(linewidth = 1.2) +\n  theme_minimal() +\n  labs(\n    title = \"Función de densidad Chi-cuadrada (\\U03C7\\U00B2)\",\n    subtitle = \"El sesgo disminuye a medida que aumentan los grados de libertad (n)\",\n    x = \"Valor de la variable\",\n    y = \"f(x)\"\n  ) +\n  scale_color_brewer(palette = \"Set1\", name=\"Grados de libertad\")\n```\n\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-html/chi_cuadrada_forma-1.png){fig-align='center' width=768}\n:::\n:::\n\n\n*(Nota: Eventualmente, cuando los grados de libertad tienden a infinito, la curva se vuelve perfectamente simétrica, aproximándose a una distribución Normal por efecto del Teorema del Límite Central).*\n\n------------------------------------------------------------------------\n\n## Cálculo de probabilidades para la distribución $\\chi^2$\n\nEn lugar de recurrir a las clásicas tablas impresas (que solo muestran cuantiles acumulados fijos), podemos calcular probabilidades exactas para cualquier escenario utilizando el software estadístico R.\n\nConsidere que tiene una variable aleatoria $X$ que proviene de una distribución Chi-cuadrada con $12$ grados de libertad ($X \\sim \\chi^2_{12}$).\n\nEn R, la función `pchisq(q, df)` calcula la probabilidad acumulada a la izquierda (cola inferior) hasta el valor $q$ dado, esto es, $F(x) = P(X \\le x)$.\n\n**a) Calcular probabilidad en un intervalo:** $P(5.23 \\le X \\le 14.8)$\n\nPara encontrar el área entre dos puntos, calculamos el área acumulada hasta el límite superior y le restamos el área acumulada hasta el límite inferior: $$P(5.23 \\le X \\le 14.8) = P(X \\le 14.8) - P(X \\le 5.23)$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Área hasta 14.8\narea_sup <- pchisq(14.8, df=12)\n# Área hasta 5.23\narea_inf <- pchisq(5.23, df=12)\n\nprob_intervalo <- area_sup - area_inf\nround(prob_intervalo, 3)\n#> [1] 0.697\n```\n:::\n\n\nLa probabilidad de caer en este intervalo central es aproximadamente **0.697**.\n\n**b) Calcular probabilidad acumulada (Cola izquierda):** $P(X < 26.2)$\n\nAl ser una distribución continua, el signo estricto ($<$) es equivalente al no estricto ($\\le$).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(pchisq(26.2, df=12), 3)\n#> [1] 0.99\n```\n:::\n\n\nLa probabilidad de observar un valor menor a 26.2 es de **0.99**.\n\n**c) Calcular probabilidad de excedencia (Cola derecha):** $P(X > 6.30)$\n\nLa función `pchisq` por defecto acumula a la izquierda. Para calcular la cola derecha (\"área mayor que\"), debemos usar la regla del complemento (1 menos el área izquierda). $$P(X > 6.30) = 1 - P(X \\le 6.30)$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1 menos el área acumulada hasta 6.30\nprob_cola_der <- 1 - pchisq(6.30, df=12)\nround(prob_cola_der, 3)\n#> [1] 0.9\n\n# Alternativa directa en R usando lower.tail = FALSE\n# round(pchisq(6.30, df=12, lower.tail=FALSE), 3)\n```\n:::\n\n\nLa probabilidad de observar un valor superior a 6.30 es de **0.90**.\n\n**d) Encontrar un percentil/cuantil inverso: Si** $P(X < a) = 0.01$, ¿quién es el valor $a$?\n\nAquí el problema está invertido. Conocemos el área (0.01) y buscamos el punto de corte en el eje horizontal. En R, las funciones inversas para buscar cuantiles comienzan con la letra 'q'. En este caso usamos `qchisq(p, df)`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Buscamos el cuantil que acumula un 1% (0.01) de área a la izquierda\nvalor_a <- qchisq(0.01, df=12)\nround(valor_a, 2)\n#> [1] 3.57\n```\n:::\n\n\nEl valor crítico es $a = 3.57$. Es decir, hay un 1% de probabilidad de que esta variable $\\chi^2_{12}$ tome un valor inferior a 3.57.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Representación visual del inciso d)\nx_rango <- seq(0, 35, length.out=400)\ndf_d <- data.frame(x = x_rango, fx = dchisq(x_rango, df=12))\n\nggplot(df_d, aes(x=x, y=fx)) +\n  geom_line(color=\"darkblue\", linewidth=1) +\n  geom_area(data = subset(df_d, x <= 3.57), fill=\"orange\", alpha=0.8) +\n  geom_vline(xintercept = 3.57, color=\"red\", linetype=\"dashed\", linewidth=1) +\n  theme_minimal() +\n  labs(\n    title = bquote(\"Encontrando el valor crítico a = 3.57 para un área de 0.01\"),\n    x = bquote(\"\\U03C7\\U00B2 con n=12\"),\n    y = \"Densidad\"\n  ) +\n  annotate(\"text\", x=8, y=0.01, label=\"Área \\n = 0.01\", color=\"darkorange\", fontface=\"bold\")\n```\n\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-html/grafica_cola_izq-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n## Distribución del estimador $S^2$\n\nComo mencionamos anteriormente, el estimador de la varianza $S^2$ por sí solo no tiene una distribución de probabilidad que podamos tipificar directamente en una tabla. Sin embargo, existe una transformación matemática fundamental que asocia a este estadístico con una distribución conocida.\n\n> **Teorema:** Si $X_1, X_2, \\dots, X_n$ es una muestra aleatoria extraída de una **población normal** con media $\\mu$ y varianza $\\sigma^2$, entonces la variable aleatoria creada al multiplicar la varianza muestral por sus grados de libertad y dividirla entre la varianza poblacional, se distribuye como una Chi-cuadrada con $n-1$ grados de libertad.\n\n$$\\frac{(n-1)S^2}{\\sigma^2} \\sim \\chi^2_{n-1} \\quad (8)$$\n\n::: {.callout-note icon=false}\n## Nota\nEsta relación es el núcleo de la inferencia para varianzas, pero depende fuertemente de la suposición de que la población original sea Normal. Si la población no es Normal, este estadístico no seguirá una distribución Chi-cuadrada.\n:::\n\n**Ejemplo 1**\n\nSe considera una medición física realizada con un instrumento de precisión donde el interés se centra en la variabilidad de la lectura. Se sabe que la medición es una variable aleatoria con distribución Normal y desviación típica de 4 unidades (es decir, una varianza poblacional $\\sigma^2 = 16$).\n\nSe toma una muestra aleatoria de tamaño $n = 25$. **¿Cuál es la probabilidad de que la varianza muestral calculada (**$S^2$) sea mayor a 12.16 unidades cuadradas?\n\nEl evento de interés es $P(S^2 > 12.16)$. Desafortunadamente, calcular la probabilidad directa de $S^2$ no es posible. Para resolverlo, transformamos ambos lados de la desigualdad utilizando la ecuación (8):\n\nMultiplicamos por $(n-1)$ y dividimos por $\\sigma^2$: $$P\\left( S^2 > 12.16 \\right) = P\\left( \\frac{(25-1)S^2}{16} > \\frac{(25-1)(12.16)}{16} \\right)$$ $$= P\\left( \\chi^2_{24} > \\frac{24 \\cdot 12.16}{16} \\right) = P(\\chi^2_{24} > 18.24) \\quad (9)$$\n\nAhora el problema se reduce a buscar el área a la derecha del valor 18.24 en una distribución Chi-cuadrada con 24 grados de libertad. En R, calculamos el complemento del área acumulada:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# P(X^2_24 > 18.24) = 1 - P(X^2_24 <= 18.24)\nprob_s2 <- 1 - pchisq(18.24, df = 24)\nround(prob_s2, 3)\n#> [1] 0.791\n```\n:::\n\n\nLa probabilidad de que la varianza muestral sea mayor a 12.16 es de **0.791** (79.1%).\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. El tiempo de vida de cierto componente se distribuye $N(\\mu, \\sigma^2)$ con $\\sigma = 5$. Si se toma una muestra de $n=16$, calcule $P(\\bar{X} > \\mu + 2)$.\n2. Si $Y \\sim \\chi^2_{15}$, use R (funciones `pchisq`/`qchisq`) para calcular $P(Y > 22)$ y el valor crítico $a$ tal que $P(Y < a) = 0.05$.\n3. Una muestra de $n=10$ observaciones normales tiene $\\sigma^2 = 9$. Calcule $P(S^2 > 14)$ usando la relación entre $S^2$ y la distribución Chi-cuadrada.\n:::\n\n------------------------------------------------------------------------\n\n## Distribución $t$ de Student\n\nLa distribución $t$ de Student es el modelo matemático que utilizamos cuando queremos hacer inferencias sobre la media poblacional $\\mu$, pero **desconocemos la verdadera desviación estándar poblacional** $\\sigma$ y nos vemos obligados a estimarla usando la desviación estándar de nuestra muestra ($S$).\n\nUna variable aleatoria $T$ tiene una distribución $t$ de Student si se define como la razón entre una variable Normal Estándar y la raíz cuadrada de una variable Chi-cuadrada dividida por sus grados de libertad (Mendenhall et al.):\n\nSean $Z \\sim N(0,1)$ y $U \\sim \\chi^2_n$ variables aleatorias independientes. Entonces: $$T = \\frac{Z}{\\sqrt{U/n}} \\sim t_n$$\n\nAplicando esto a nuestros estimadores muestrales ($Z = \\frac{\\bar{X}-\\mu}{\\sigma/\\sqrt{n}}$ y $U = \\frac{(n-1)S^2}{\\sigma^2}$): $$T = \\frac{\\bar{X} - \\mu}{S / \\sqrt{n}} \\sim t_{n-1} \\quad (10.1)$$\n\n**Propiedades de la distribución** $t$\n\na)  Varía de $-\\infty$ a $\\infty$, igual que la Normal.\nb)  Es perfectamente simétrica con respecto al $0$.\nc)  Presenta una mayor dispersión que la Normal Estándar. Esto se debe a que la fórmula del estadístico $T$ tiene dos fuentes de variabilidad por el muestreo: la de $\\bar{X}$ en el numerador y la de $S$ en el denominador (a diferencia de $Z$, donde $\\sigma$ es una constante fija).\nd)  **Colas pesadas:** Alrededor de la media, la campana Normal es más alta. Sin embargo, en los extremos (las colas), la distribución $t$ acumula más área (probabilidad).\ne)  A medida que aumenta el tamaño de la muestra ($n \\to \\infty$), la estimación $S$ se vuelve tan precisa que la distribución $t$ se vuelve idéntica a la Normal Estándar.\n\n------------------------------------------------------------------------\n\n## Cálculo de probabilidades de una distribución $t$ de Student\n\n**Ejemplo:** Un ingeniero agrónomo ha desarrollado una variedad de maíz (\"xy32\") y afirma que su rendimiento medio es de $\\mu = 1.5 \\text{ kg/planta}$. En un campo experimental se cultivaron $n = 20$ plantas. Tras la cosecha, se estimó una desviación estándar muestral de $S = 0.8 \\text{ kg/planta}$.\n\nEl agrónomo teme que, por azar, el rendimiento medio de la muestra resulte ser muy bajo. **¿Cuál es la probabilidad de que el rendimiento medio muestral (**$\\bar{X}$) sea inferior a 1 kg?\n\nSi **erróneamente** asumiéramos que la desviación poblacional es conocida y exacta ($\\sigma = 0.8$), usaríamos la distribución Normal: $$P(\\bar{X} \\le 1) = P\\left( Z \\le \\frac{1 - 1.5}{0.8 / \\sqrt{20}} \\right) = P(Z \\le -2.80) \\approx 0.0026$$\n\nSin embargo, esto es incorrecto. Sabemos que $0.8$ es solo una estimación ($S$), por lo que debemos usar la distribución $t$ de Student con $n-1 = 19$ grados de libertad, según la ecuación (10.1):\n\n$$P(\\bar{X} \\le 1) = P\\left( T_{19} \\le \\frac{1 - 1.5}{0.8 / \\sqrt{20}} \\right) = P(T_{19} \\le -2.80)$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Probabilidad usando la distribución t con 19 grados de libertad\nprob_t <- pt(-2.80, df = 19)\nround(prob_t, 3)\n#> [1] 0.006\n```\n:::\n\n\nLa probabilidad real es de **0.006**. Observa que es más del doble de lo que estimamos erróneamente con la Normal. Esto ilustra el concepto de las \"colas pesadas\": la incertidumbre adicional de no conocer $\\sigma$ hace que los eventos extremos sean más probables.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nx_vals <- seq(-4, 4, length.out = 400)\ndf_comp <- data.frame(\n  x = rep(x_vals, 2),\n  densidad = c(dnorm(x_vals), dt(x_vals, df=5)), # Usamos df=5 para exagerar visualmente la diferencia\n  Distribucion = factor(rep(c(\"Normal Estándar (Z)\", \"t de Student (v=5)\"), each=400))\n)\n\nggplot(df_comp, aes(x=x, y=densidad, color=Distribucion)) +\n  geom_line(linewidth=1.2) +\n  theme_minimal() +\n  labs(\n    title = \"Comparación: Distribución Normal vs. t de Student\",\n    subtitle = \"Notar cómo la línea azul (t) está por encima de la roja (Normal) en los extremos (colas)\",\n    x = \"Valor estandarizado\",\n    y = \"Densidad\"\n  ) +\n  scale_color_manual(values = c(\"red\", \"blue\")) +\n  theme(legend.position = \"bottom\", legend.title = element_blank())\n```\n\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-html/grafica_comparativa_t_normal-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Distribución $F$ de Fisher\n\nLa distribución $F$ surge de manera natural cuando queremos **comparar las varianzas de dos poblaciones distintas**.\n\n> **Definición:** Sean $U \\sim \\chi^2_{v_1}$ y $W \\sim \\chi^2_{v_2}$ dos variables aleatorias independientes con distribución Chi-cuadrada. La variable aleatoria $F$ se define como la razón de ambas variables, cada una dividida previamente por sus respectivos grados de libertad: $$F_{v_1, v_2} = \\frac{U / v_1}{W / v_2} \\quad (13)$$\n\n**Ejemplo:** Se tiene muy bien estudiado el tiempo de vuelo de dos aerolíneas. Ambas tienen el mismo tiempo medio de vuelo y, supongamos, **la misma varianza poblacional** ($\\sigma_1^2 = \\sigma_2^2$).\n\nSe obtiene una muestra aleatoria de $n_1 = 15$ vuelos de la aerolínea 1, y $n_2 = 25$ de la aerolínea 2. **¿Cuál es la probabilidad de que la varianza muestral de la primera aerolínea sea más del doble que la de la segunda?** Es decir, calcular: $P\\left( \\frac{S_1^2}{S_2^2} > 2 \\right)$.\n\nSabiendo por la ecuación (8) que $U = \\frac{(n_1-1)S_1^2}{\\sigma_1^2} \\sim \\chi^2_{n_1-1}$, si dividimos $U$ entre sus grados de libertad ($n_1-1$), obtenemos simplemente $\\frac{S_1^2}{\\sigma_1^2}$. Haciendo lo mismo para la segunda muestra, la razón $F$ queda estructurada como:\n\n$$F_{n_1-1, n_2-1} = \\frac{ \\frac{S_1^2}{\\sigma_1^2} }{ \\frac{S_2^2}{\\sigma_2^2} } = \\left(\\frac{S_1^2}{S_2^2}\\right) \\left(\\frac{\\sigma_2^2}{\\sigma_1^2}\\right)$$\n\nDado que asumimos que las varianzas poblacionales son iguales ($\\sigma_1^2 = \\sigma_2^2$), el término de la derecha se cancela (es 1). Por lo tanto, **el cociente de las varianzas muestrales sigue exactamente una distribución** $F$: $$\\frac{S_1^2}{S_2^2} \\sim F_{14, 24}$$\n\nLa probabilidad de interés se convierte directamente en: $$P\\left( \\frac{S_1^2}{S_2^2} > 2 \\right) = P(F_{14, 24} > 2)$$\n\nCalculamos esto en R usando la función `pf`, que requiere el cuantil y los dos grados de libertad correspondientes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# P(F > 2) = 1 - P(F <= 2)\nprob_f <- 1 - pf(2, df1 = 14, df2 = 24)\nround(prob_f, 3)\n#> [1] 0.065\n```\n:::\n\n\nLa probabilidad de que, por puro azar del muestreo, la varianza observada de la aerolínea 1 sea el doble que la de la aerolínea 2 (aun cuando en la realidad sean iguales) es de **0.063** (6.3%).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Representación de la Distribución F(14, 24)\nx_f <- seq(0, 4, length.out = 400)\ndf_fisher <- data.frame(x = x_f, densidad = df(x_f, df1 = 14, df2 = 24))\n\nggplot(df_fisher, aes(x=x, y=densidad)) +\n  geom_line(color=\"darkgreen\", linewidth=1) +\n  geom_area(data = subset(df_fisher, x > 2), fill=\"lightgreen\", alpha=0.7) +\n  geom_vline(xintercept = 2, color=\"red\", linetype=\"dashed\", linewidth=1) +\n  theme_minimal() +\n  labs(\n    title = bquote(\"Distribución F de Fisher (\"*v[1]==14~\",\"~v[2]==24*\")\"),\n    x = \"Valor del cociente de varianzas (F)\",\n    y = \"Densidad\"\n  ) +\n  annotate(\"text\", x=2.5, y=0.1, label=\"P(F > 2) = 0.063\", color=\"darkgreen\", fontface=\"bold\")\n```\n\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-html/grafica_f_fisher-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n## Cálculo de probabilidades de una distribución F\n\nPara hacer más ágil y preciso el cálculo de probabilidades, se emplea el software estadístico R en lugar de las tradicionales tablas impresas.\n\nRetomando el ejemplo anterior de las dos aerolíneas, la probabilidad de interés en la ecuación (16) era: $$P(F_{14, 24} > 1.167) = 1 - P(F_{14, 24} \\le 1.167)$$\n\nLa probabilidad de que la razón de las varianzas muestrales exceda a 2 (sabiendo que la razón de las varianzas poblacionales se asume igual a 1) se calcula en R de la siguiente manera:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculamos la probabilidad de la cola derecha\nprob_f <- 1 - pf(1.167, df1 = 14, df2 = 24)\nround(prob_f, 3)\n#> [1] 0.358\n```\n:::\n\n\nLa función `pf(q, df1, df2)` tiene como primer argumento el valor de interés a calcular su probabilidad ($q$), después los grados de libertad del numerador ($df1$) y por último los grados de libertad del denominador ($df2$). Por defecto, la función `pf` calcula la probabilidad de la cola izquierda (probabilidad acumulada).\n\nLa distribución $F$ tiene gran aplicación en inferencia estadística, principalmente en el famoso Análisis de Varianza (mejor conocido como ANOVA).\n\n**Cálculo de cuantiles (valores críticos):** En algunas situaciones, se conoce el valor de los grados de libertad $v_1$, $v_2$ y un nivel de probabilidad $\\alpha$ (área en la cola), de modo que el interés será encontrar el valor de corte $k$. $$P(F_{v_1, v_2} > k) = \\alpha$$\n\nSi $v_1 = 14$, $v_2 = 24$ y $\\alpha = 0.05$, se tiene que: $$P(F_{14, 24} > k) = 0.05 \\quad (17)$$\n\nEn R, el código para encontrar este valor crítico $k$ es el siguiente:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Buscamos el valor k que deja un 5% de área a su derecha\nk_valor <- qf(0.05, df1 = 14, df2 = 24, lower.tail = FALSE)\nround(k_valor, 3)\n#> [1] 2.13\n```\n:::\n\n\nAl especificar `lower.tail = FALSE` en la función `qf`, le indicamos al software que considere el área de probabilidad en la cola derecha. En este caso, $k \\approx 2.13$.\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. Una muestra de $n=12$ observaciones normales tiene $\\bar{x}=48$ y $s=6$. Pruebe si es razonable suponer $\\mu=50$ calculando $P(\\bar{X} \\le 48)$ usando la distribución $t$ con los grados de libertad correspondientes.\n2. Use R (`qt`) para encontrar el valor crítico $t$ que deja un área de 0.025 en la cola derecha de una distribución $t$ con 18 grados de libertad.\n3. Se comparan las varianzas de dos máquinas con muestras de tamaño $n_1=10$ y $n_2=13$. Calcule $P(F_{9,12} > 1.5)$ usando R (`pf`).\n:::\n\n------------------------------------------------------------------------\n\n## Distribución muestral del estimador de la proporción\n\nCuando estudiamos una característica cualitativa en una población (por ejemplo: artículo defectuoso vs. no defectuoso, alquila vivienda vs. no alquila), trabajamos con variables que asumen solo dos valores.\n\nSea $X_i$ una variable de Bernoulli tal que: $$X_i = \\begin{cases} 1, & \\text{si se presenta la característica de interés} \\\\ 0, & \\text{si no se presenta la característica de interés} \\end{cases}$$\n\nLa **proporción muestral** ($\\hat{P}$ o $\\bar{P}$) se define como el promedio de estas variables: $$\\hat{P} = \\frac{X_1 + X_2 + \\dots + X_n}{n} = \\frac{\\sum_{i=1}^n X_i}{n}$$\n\nSea $X_1, X_2, \\dots, X_n$ una muestra aleatoria extraída de una distribución Bernoulli con parámetro poblacional $P$ (la verdadera proporción de \"éxitos\" en la población). Según la teoría estadística (Mendenhall et al.), las propiedades del estimador $\\hat{P}$ son:\n\n**Esperanza matemática:** $$E[\\hat{P}] = \\mu_{\\hat{P}} = P \\quad (18)$$ *(El estimador de la proporción es insesgado).*\n\n**Varianza del estimador:** $$Var(\\hat{P}) = \\sigma_{\\hat{P}}^2 = \\frac{P \\cdot Q}{n} \\quad (19)$$ Donde $Q = 1 - P$.\n\n**Ejemplo 1**\n\nConsideremos una población minúscula que consta de $N = 4$ familias. Nos interesa conocer qué familias alquilan una vivienda. En la Tabla 7 se expone la población y el cálculo del parámetro real.\n\n**Tabla 7. Población de viviendas.**\n\n| Familia ($i$) | Alquila ($x_i$) |\n|:-------------:|:---------------:|\n|     A (1)     |        0        |\n|     B (2)     |        1        |\n|     C (3)     |        0        |\n|     D (4)     |        0        |\n\nEl **parámetro poblacional** real (Proporción de familias que alquilan) es: $$P = \\frac{\\sum_{i=1}^N x_i}{N} = \\frac{0 + 1 + 0 + 0}{4} = \\frac{1}{4} = 0.25$$\n\nAhora construyamos la distribución muestral del estimador $\\hat{P}$ tomando todas las muestras posibles de tamaño $n = 2$ con reemplazo. El número total de muestras posibles es $N^n = 4^2 = 16$.\n\n**Tabla 8. Distribución muestral de la Proporción.**\n\n| Viviendas Seleccionadas | Valores Observados | Proporción Estimada $\\hat{p}$ | Probabilidad $P(\\hat{P} = \\hat{p})$ |\n|:---|:--:|:--:|:--:|\n| (A,A), (A,C), (A,D), (C,A), (C,C), (C,D), (D,A), (D,C), (D,D) | 0 y 0 | 0 | 9/16 |\n| (A,B), (B,A), (B,C), (C,B), (B,D), (D,B) | 0 y 1 / 1 y 0 | 0.5 | 6/16 |\n| (B,B) | 1 y 1 | 1 | 1/16 |\n| **Total** |  |  | **1** |\n\nCon base en la Tabla 8, es evidente que $\\hat{P}$ es una variable aleatoria. Podemos comprobar la Ecuación (18) calculando la esperanza a partir de esta distribución muestral empírica: $$E[\\hat{P}] = \\sum \\left( \\hat{p}_i \\cdot P(\\hat{P} = \\hat{p}_i) \\right) = \\left(0 \\cdot \\frac{9}{16}\\right) + \\left(0.5 \\cdot \\frac{6}{16}\\right) + \\left(1 \\cdot \\frac{1}{16}\\right) = \\frac{3}{16} + \\frac{1}{16} = \\frac{4}{16} = 0.25$$ Vemos que $E[\\hat{P}] = P = 0.25$.\n\nComprobando la Ecuación (19) para la varianza: $$Var(\\hat{P}) = \\frac{P(1-P)}{n} = \\frac{0.25(0.75)}{2} = \\frac{0.1875}{2} = 0.09375$$\n\n------------------------------------------------------------------------\n\n## Teorema del Límite Central (TLC)\n\nEste es, quizás, el teorema de mayor importancia práctica en la estadística inferencial. Especifica cuál es el comportamiento de las distribuciones de promedios o sumas cuando el tamaño de la muestra crece.\n\n> **Teorema del Límite Central:** Sea $X_1, X_2, \\dots, X_n$ una muestra aleatoria de tamaño $n$, extraída de una población con **cualquier** distribución de probabilidad (no necesariamente normal), que posea una media finita $\\mu$ y una varianza finita $\\sigma^2$. A medida que el tamaño de la muestra $n$ se vuelve grande ($n \\to \\infty$), la distribución muestral del promedio $\\bar{X}$ se aproxima a una distribución Normal con media $\\mu_{\\bar{X}} = \\mu$ y varianza $\\sigma_{\\bar{X}}^2 = \\frac{\\sigma^2}{n}$.\n\n$$\\bar{X} \\approx N\\left(\\mu, \\frac{\\sigma^2}{n}\\right)$$\n\n**¿Qué tan grande debe ser** $n$? El valor necesario de $n$ depende de qué tan asimétrica sea la distribución original de la población: \\* Si la población es bastante simétrica, un $n \\ge 5$ puede ser suficiente. \\* Si la distribución original está muy sesgada o es altamente irregular (ej. exponencial, bimodal), la regla de oro en estadística dicta que un tamaño de muestra $n \\ge 30$ garantiza una aproximación excelente a la Normal.\n\n**El TLC para el Estimador del Total (**$T$): El teorema también se aplica a la suma total de las observaciones $T = \\sum_{i=1}^n X_i$. Si $n$ es grande: $$T \\approx N\\left( \\mu_T = n\\mu, \\sigma_T^2 = n\\sigma^2 \\right)$$\n\n**Ejemplo 1**\n\nSuponga que el peso de los paquetes de café de cierto tipo tiene una media de $\\mu = 1 \\text{ kg}$ y una desviación estándar de $\\sigma = 0.05 \\text{ kg}$ (distribución poblacional desconocida). En una caja se empacan $n = 64$ paquetes.\n\n**¿Cuál es la probabilidad de que el peso total de los 64 paquetes esté entre 63 y 64.4 kg?**\n\nBuscamos $P(63 \\le T \\le 64.4)$. Aunque no conocemos la distribución individual, como $n=64$ es un tamaño grande, aplicamos el TLC para el Total: $$T \\sim N\\left( \\mu_T = 64(1) = 64, \\sigma_T^2 = 64(0.05)^2 = 0.16 \\right)$$ La desviación estándar del total será $\\sigma_T = \\sqrt{0.16} = 0.4 \\text{ kg}$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# P(63 <= T <= 64.4) = P(T <= 64.4) - P(T <= 63)\nprob_total <- pnorm(64.4, mean = 64, sd = 0.4) - pnorm(63, mean = 64, sd = 0.4)\nround(prob_total, 3)\n#> [1] 0.835\n```\n:::\n\n\nLa probabilidad es de **0.835**.\n\n------------------------------------------------------------------------\n\n## Teorema del límite central para el estimador de la proporción\n\nDado que la proporción muestral $\\hat{P}$ es, matemáticamente, un promedio de variables aleatorias Bernoulli (1s y 0s), **el Teorema del Límite Central también aplica a las proporciones**.\n\nSi $n$ es grande, el proceso de tomar muestras y estimar la proporción genera una distribución que se puede modelar con una curva Normal: $$\\hat{P} \\approx N\\left( \\mu_{\\hat{P}} = P, \\sigma_{\\hat{P}}^2 = \\frac{P(1-P)}{n} \\right)$$\n\n**Ejemplo 1**\n\nUn medicamento para el malestar estomacal tiene la advertencia de que puede causar reacciones adversas. Por estudios clínicos, se asume que el parámetro poblacional es $P = 0.03$ (el 3% de los usuarios presenta reacción).\n\nSi se receta el medicamento a una muestra de $n = 150$ personas, **¿cuál es la probabilidad de que la proporción observada en esta muestra supere el 4%?**\n\nPor el TLC para proporciones, la variable $\\hat{P}$ (proporción de reacciones en la muestra) se distribuye como: $$\\hat{P} \\approx N\\left( 0.03, \\frac{0.03(1 - 0.03)}{150} \\right) = N(0.03, 0.000194)$$\n\nLa desviación estándar (error estándar de la proporción) es $\\sqrt{0.000194} \\approx 0.0139$. La probabilidad de interés es $P(\\hat{P} > 0.04)$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Definimos los parámetros\nP_pob <- 0.03\nn_muestra <- 150\nerror_estandar <- sqrt((P_pob * (1 - P_pob)) / n_muestra)\n\n# Calculamos P(P_hat > 0.04) = 1 - P(P_hat <= 0.04)\nprob_prop <- 1 - pnorm(0.04, mean = P_pob, sd = error_estandar)\nround(prob_prop, 3)\n#> [1] 0.236\n```\n:::\n\n\nLa probabilidad de que más del 4% de la muestra presente reacciones adversas es de **0.236** (23.6%).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Representación visual de la proporción muestral\nlibrary(ggplot2)\n\nx_prop <- seq(0, 0.08, length.out = 400)\ndf_prop <- data.frame(x = x_prop, densidad = dnorm(x_prop, mean = P_pob, sd = error_estandar))\n\nggplot(df_prop, aes(x = x, y = densidad)) +\n  geom_line(color = \"darkred\", linewidth = 1) +\n  geom_area(data = subset(df_prop, x > 0.04), fill = \"salmon\", alpha = 0.7) +\n  geom_vline(xintercept = 0.04, color = \"black\", linetype = \"dashed\") +\n  theme_minimal() +\n  labs(\n    title = \"Distribución Muestral de la Proporción (TLC)\",\n    subtitle = \"Aproximación Normal para \\U0050\\U0302 con P = 0.03 y n = 150\",\n    x = \"Proporción Muestral (\\U0050\\U0302)\",\n    y = \"Densidad\"\n  ) +\n  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +\n  annotate(\"text\", x = 0.055, y = 5, label = \"Área \\u2248 0.236\", color = \"darkred\", fontface = \"bold\")\n```\n\n::: {.cell-output-display}\n![](cap04-inferencia_files/figure-html/grafica_tlc_prop-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. El tiempo de ensamblaje de una pieza tiene media $\\mu = 12$ minutos y desviación estándar $\\sigma = 3$ minutos (distribución desconocida). Para una muestra de $n = 49$ piezas, use el TLC para calcular $P(\\bar{X} > 12.5)$.\n2. En una encuesta a $n = 200$ personas, se asume que la verdadera proporción que prefiere un producto es $P = 0.40$. Calcule, usando el TLC para proporciones, la probabilidad de que la proporción muestral sea menor a 0.35.\n3. Explique por qué el Teorema del Límite Central es útil incluso cuando no conocemos la distribución exacta de la población original.\n:::\n\n::: {.callout-note icon=false}\n## Resumen del capítulo\n\n- **Población:** conjunto completo de mediciones de interés; sus valores numéricos resumen (como $\\mu$ y $\\sigma^2$) se llaman **parámetros**.\n- **Muestra aleatoria:** conjunto de variables aleatorias $X_1, \\ldots, X_n$ independientes e idénticamente distribuidas (v.a.i.i.d.).\n- **Estimador:** función de la muestra usada para estimar un parámetro desconocido; su valor calculado a partir de datos observados es la **estimación**.\n- **Distribución muestral:** distribución de probabilidad de un estimador, considerando todas las muestras posibles de tamaño $n$.\n- **Media muestral** $\\bar{X}$: $E[\\bar{X}] = \\mu$, $Var(\\bar{X}) = \\sigma^2/n$; si la población es normal, $\\bar{X}$ también es normal.\n- **Varianza muestral** $S^2$: estimador insesgado de $\\sigma^2$; bajo población normal, $(n-1)S^2/\\sigma^2 \\sim \\chi^2_{n-1}$.\n- **Distribución $t$ de Student:** sustituye a la Normal cuando $\\sigma$ es desconocida y se estima con $S$; tiene colas más pesadas, y converge a la Normal cuando $n$ crece.\n- **Distribución $F$ de Fisher:** modela el cociente de dos varianzas muestrales independientes; útil para comparar la variabilidad de dos poblaciones.\n- **Proporción muestral** $\\hat{P}$: $E[\\hat{P}] = P$, $Var(\\hat{P}) = P(1-P)/n$.\n- **Teorema del Límite Central:** para $n$ suficientemente grande, $\\bar{X}$ (y también $\\hat{P}$) se aproxima a una distribución Normal, sin importar la forma de la distribución original de la población.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}