{
  "hash": "da8eb61814e1f87a23cc7d039e09643e",
  "result": {
    "engine": "knitr",
    "markdown": "# Variable Aleatoria Continua {#cap-distribucion-conjunta}\n\nCiertos fenómenos originan resultados en un espectro continuo. En la modelación analítica y la simulación de procesos, podríamos estar interesados en estudiar el tiempo de espera de un paciente en la sala de urgencias de un hospital, la duración de una llamada en una línea telefónica de atención, o el tiempo exacto que toma el proceso de pintado de un automóvil en una línea de ensamblaje. Este tipo de variable aleatoria, que puede tomar cualquier valor dentro de un intervalo (o unión de intervalos), se denomina *continua*.\n\n::: {.callout-tip icon=false}\n## Objetivos de aprendizaje\n\nAl finalizar este capítulo, el estudiante será capaz de:\n\n- Definir variable aleatoria continua y calcular probabilidades como áreas bajo la función de densidad de probabilidad (pdf).\n- Obtener e interpretar la función de distribución acumulada (cdf) de una variable aleatoria continua, y calcular cuantiles.\n- Calcular el valor esperado, la varianza y otras medidas de resumen para las distribuciones Uniforme, Normal, Exponencial, Gamma y Weibull.\n- Estandarizar variables normales y usar la tabla $Z$ (o R) para obtener probabilidades y percentiles.\n- Describir la distribución conjunta de dos variables aleatorias continuas mediante su pdf conjunta, calcular distribuciones marginales y determinar si son independientes.\n\n:::\n\nEn este capítulo se estudian las variables aleatorias continuas: cómo se describen mediante su función de densidad de probabilidad y su función de probabilidad acumulada, y cómo calcular probabilidades como áreas bajo una curva. Revisaremos las distribuciones continuas más utilizadas en la práctica: la Uniforme continua, la Normal (junto con su versión estandarizada y el uso de tablas) y la Exponencial, incluyendo su propiedad de falta de memoria. Cerraremos con material complementario sobre la distribución Weibull y las distribuciones continuas conjuntas. A lo largo del capítulo se incluyen ejemplos resueltos y ejercicios propuestos para practicar los conceptos.\n\n## Variable aleatoria continua\n\n**Ejemplo:** Consideremos que se tiene la siguiente rueda de la fortuna:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/figura1-1.png)\n:::\n:::\n\n\nSupongamos que el punto de partida, tras girar la rueda, está definido como el punto señalado por la flecha. Ahora bien, ¿cuántos puntos de partida hay?.\n\nLa rueda puede estar, como en este caso, dividida en 10 sectores y el punto de partida puede estar definido como el número más cercano a la flecha. Pero a su vez, cada sector podría ser posteriormente dividido en 10 sectores para dar 100 puntos de partida y así sucesivamente. Es evidente que no hay un número finito de puntos de partida y la variable aleatoria, en este caso la flecha, tiene infinitos valores posibles.\n\nSi se quisiera calcular la probabilidad, desde el enfoque clásico, de que el punto de partida sea el 6, no existiría un número para el denominador, pues el espacio muestral contempla infinitos puntos posibles.\n\nA diferencia de las variables aleatorias discretas, que asumen un número contable de valores, las variables aleatorias continuas pueden asumir los infinitos valores correspondientes a los puntos de un intervalo de la recta real.\n\n**Ejemplo:** Consideremos un experimento donde se registra el tiempo (en minutos) que una pieza metálica permanece en un taller de tornos para su rectificación. Supongamos que, por las características de la maquinaria, el tiempo mínimo es de 1 minuto y el máximo es de 4 minutos. ¿Cuántos posibles tiempos exactos de permanencia hay en el intervalo [1, 4]?\n\nEl tiempo de permanencia podría ser 2.1 minutos, 2.15 minutos, 2.153 minutos, etc. Es evidente que, limitados únicamente por la precisión de nuestros instrumentos de medición, existe una infinidad de valores posibles.\n\nDebido a que hay un número infinito de valores posibles, no podemos asignar una probabilidad positiva a cada uno de ellos y lograr que la suma de las probabilidades sea 1. De hecho, en la teoría formal de la probabilidad, la probabilidad de que una variable aleatoria continua asuma cualquier valor particular es exactamente 0. En símbolos, si $Y$ es una variable aleatoria continua:\n\n$$P(Y=y)=0 \\text{ para todo valor específico de } y$$\n\n> **Definición:** Una variable aleatoria $Y$ se dice que es *continua* si su función de distribución acumulada $F(y)$ es continua para todo $y \\in \\mathbb{R}$. Esto implica que la variable puede tomar cualquier valor en un intervalo y la probabilidad de observar cualquier punto específico es nula.\n\n:::: {.content-visible when-format=\"html\"}\n[📖 Magín Zúñiga Estrada]{.fuente-badge .fuente-magin}\n\n::::\n\n### Definición formal — VA continua y función de densidad\n\n::: {.callout-tip icon=false}\n## Definición — Variable aleatoria continua\nUna v.a. $X$ es **continua** si existe una función $f(x) \\geq 0$, definida para todo $x \\in (-\\infty, \\infty)$, tal que para cualquier conjunto $B \\subseteq \\mathbb{R}$:\n$$P(X \\in B) = \\int_{B} f(x)\\, dx$$\nA $f(x)$ se le llama **función de densidad de probabilidad (pdf)**. En particular:\n$$P(a \\leq X \\leq b) = \\int_{a}^{b} f(x)\\, dx$$\n\n:::\n\nLa pdf satisface siempre:\n\n1. $f(x) \\geq 0$ (no negativa).\n2. $\\displaystyle\\int_{-\\infty}^{\\infty} f(x)\\, dx = 1$.\n\n> **Diferencias clave entre pdf y pmf:** La pdf $f(x)$ **no es una probabilidad** — hay que integrarla para obtener una. Por ello $f(x)$ puede ser mayor que 1. En cambio, la pmf $p(a) = P(X=a)$ sí es directamente una probabilidad.\n\n### Relación entre pdf y cdf\n\nLa **cdf** de una v.a. continua es $F(a) = P(X \\leq a) = \\displaystyle\\int_{-\\infty}^{a} f(x)\\, dx$. Diferenciando ambos lados:\n$$F'(a) = f(a)$$\nEs decir, la función de densidad es la **derivada de la función de distribución acumulada**.\n\n::: {.callout-tip icon=false}\n## Propiedades de la cdf continua\n1. $F(x) = P(X \\leq x)$.\n2. $0 \\leq F(x) \\leq 1$.\n3. $F(x)$ es no decreciente: si $a \\leq b$ entonces $F(a) \\leq F(b)$.\n4. $\\displaystyle\\lim_{x \\to \\infty} F(x) = 1$ y $\\displaystyle\\lim_{x \\to -\\infty} F(x) = 0$.\n5. $P(a \\leq X \\leq b) = F(b) - F(a)$.\n6. $F'(x) = f(x)$.\n\n:::\n\nVisualización de puntos en el intervalo [1,4]:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/comparacion_puntos-1.png)\n:::\n:::\n\n\nDe lo anterior se concluye que en las variables continuas, el interés no recae en calcular la probabilidad de valores aislados, sino en encontrar la probabilidad de que la variable caiga en un rango de valores.\n\n### Función de densidad de probabilidad\n\nDado que para una variable aleatoria continua $Y$, $P(Y=y) = 0$, no es posible utilizar una función de probabilidad puntual como en el caso discreto. En su lugar, se emplea una **función de densidad de probabilidad**, denotada comúnmente como $f(y)$.\n\nLa probabilidad de que $Y$ caiga en el intervalo $[a, b]$ corresponde geométricamente al área bajo la curva de densidad $f(y)$ entre $a$ y $b$:\n\n$$P(a \\le Y \\le b) = \\int_{a}^{b} f(y)dy \\quad (1)$$\n\nPara que una función matemática $f(y)$ sea una función de densidad de probabilidad válida, debe cumplir con dos propiedades teóricas fundamentales:\n\n1.  $f(y) \\ge 0$ para todo $y$ (la función no puede ser negativa).\n2.  $\\int_{-\\infty}^{\\infty} f(y)dy = 1$ (el área total bajo la curva debe ser exactamente igual a 1).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/figura2_area-1.png)\n:::\n:::\n\n\nPara calcular el valor exacto de esta probabilidad en la mayoría de las distribuciones teóricas, se recurre a la integración matemática. Sin embargo, en ciertos casos, el área puede encontrarse usando fórmulas de geometría elemental.\n\n**Ejemplo 1**\n\nSupongamos que en un modelo de simulación en la recepción de un hotel, la variable aleatoria $Y$ representa la proporción de tiempo durante un turno de 8 horas en que el empleado de recepción está ocupado atendiendo huéspedes de forma ininterrumpida. Al ser una proporción, la variable $Y$ solo puede tomar valores entre 0 y 1 ($0 \\le Y \\le 1$).\n\nAsumamos que la función de densidad de probabilidad asociada a $Y$ está dada por:\n\n$$f(y) = 2y \\quad \\text{ para } 0 \\le y \\le 1; \\quad \\text{y } f(y) = 0 \\text{ en cualquier otro lugar.}$$\n\nPrimero, verifiquemos geométricamente que el área total bajo la curva es 1. La figura geométrica formada es un triángulo rectángulo con base 1 y altura $f(1) = 2(1) = 2$.\n\nEl área del triángulo es: $\\frac{\\text{base} \\times \\text{altura}}{2} = \\frac{1 \\times 2}{2} = 1$. Se cumple la segunda propiedad de las funciones de densidad.\n\nAhora, si queremos calcular la probabilidad de que la proporción de tiempo de ocupación en la recepción sea menor o igual a 0.5, es decir $P(Y \\le 0.5)$, debemos calcular el área bajo la curva en el intervalo $[0, 0.5]$:\n\n-   La base del nuevo triángulo es $0.5$.\n-   La altura evaluada en $y=0.5$ es $f(0.5)=2(0.5)=1$.\n-   El área es: $\\frac{0.5 \\times 1}{2} = 0.25$.\n\nPor lo tanto, la probabilidad de que el recepcionista esté ocupado menos de la mitad del tiempo de su turno es del 25%.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/ejemplo_geometria-1.png)\n:::\n:::\n\n\n### Función de probabilidad acumulada\n\nEs una función que acumula probabilidades. Para esto considere que la variable aleatoria $X$ está definida en el intervalo $[a, b]$ y sea $x$ un valor tal que se encuentra entre $a$ y $b$, es decir $a \\le x \\le b$, entonces la función de probabilidad acumulada o también conocida como función de distribución ($F(x)$) se define como:\n\n$$P(X \\le x) = F(x) \\quad (2)$$\n\nLa ecuación 2 se refiere a acumular la probabilidad desde el valor $a$ hasta el valor $x$.\n\nEl miembro izquierdo de la ecuación (2), es solo una notación que indica: la probabilidad de que la variable aleatoria sea menor o igual a $x$.\n\n-   Si $x=a$ el valor de $P(X \\le a) = F(a) = 0$\n-   Si $x=b$ el valor de $P(X \\le b) = F(b) = 1$\n-   Si $x$ está entre $a$ y $b$ pero sin tocar estos dos últimos $P(X \\le x) = F(x)$ oscila entre 0 y 1, sin tocar estos últimos.\n\n*La función de probabilidad acumulada es siempre no decreciente, esto es, crece o se mantiene constante.*\n\nConsiderando la función de densidad: $$\n\\mathbf{f}(x) =\n\\begin{cases}\n\\frac{1}{2} x & \\text{si } 0 \\le x \\le 2\\\\\n0 & \\text{en otro caso}\n\\end{cases}\n$$ La figura 6 ilustra el caso en que debemos calcular $F(X \\le 1/2)$ o equivalentemente $F(X \\le 0.5)$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/figura6-1.png)\n:::\n:::\n\n\nEn este caso el valor de la base es: $\\text{base} = 0.5 - 0 = 0.5$ y el de la altura: $h = \\frac{1}{2} \\cdot 0.5 = 0.25$.\n\n$$P(X \\le 0.5) = F(0.5) = \\frac{0.5 \\cdot 0.25}{2} = 0.0625$$\n\nPara este caso: $\\text{base} = (1 - 0) = 1$ y el de la altura: $h = \\frac{1}{2} \\cdot 1 = 0.5$.\n\n$$P(X \\le 1) = F(1) = \\frac{1 \\cdot 0.5}{2} = 0.25$$\n\nComo se puede ver de los cálculos de probabilidades anteriores $F(X \\le x)$ siempre crece y se mantiene en 1 para $x \\ge 2$, se tiene: $\\text{base} = (2 - 0) = 2$ y la altura: $h = \\frac{1}{2} \\cdot 2 = 1$.\n\n$$F(2) = \\frac{2 \\cdot 1}{2} = 1$$\n\n$$F(2.5) = P(X \\le 2.5) = P(X \\le 2) = \\frac{2 \\cdot 1}{2} = 1$$\n\nPara $P(X \\le 2.5)$ la probabilidad acumulada será 1, ya que contiene al espacio muestral.\n\nAhora bien, si deseamos calcular la probabilidad de que $X$ tome valores entre un valor $a$ y un valor $b$ genéricos, siendo $a < b$, tenemos:\n\n$$P(a \\le X \\le b) \\quad (3)$$\n\nEsta probabilidad puede ser calculada como la diferencia entre la probabilidad acumulada hasta el valor $b$ menos la probabilidad acumulada hasta el valor $a$. Podemos representar gráficamente esta situación como los muestra la figura 7.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/figura7-1.png)\n:::\n:::\n\n\nEntonces, el cálculo de la probabilidad de la ecuación queda establecida de la siguiente manera:\n\n$$P(a \\le X \\le b) = P(X \\le b) - P(X \\le a) = F(b) - F(a) \\quad (4)$$\n\nSi reconsideramos el caso de calcular la probabilidad de que $x$ esté entre 0 y 1, como se muestra en la figura 9, pero ahora empleando la función de probabilidad acumulada, tenemos:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/figura9-1.png)\n:::\n:::\n\n\nProbabilidad de interés: $$P(0 \\le X \\le 1) = F(1) - F(0)$$\n\n$$F(1) = \\frac{1 \\cdot 0.5}{2} = 0.25$$\n\n$$P(X \\le 0) = F(0) = \\frac{0 \\cdot 0}{2} = 0$$\n\nLa variable aleatoria $X$ sólo está definida entre 0 y 2, de modo que, en el caso $X \\le 0$ el valor de la variable aleatoria es cero por la definición de la f.d.p.\n\nEntonces: $$P(0 \\le X \\le 1) = \\frac{1}{4} - 0 = \\frac{1}{4} = 0.25$$\n\nLa esperanza matemática y la varianza de variables aleatorias continuas se obtienen integrando y se definen de la siguiente manera:\n\n$$E[X] = \\int_{S_x} x f(x) dx \\quad (5)$$\n\n$$\\text{Var}(X) = \\int_{S_x} (x - E[X])^2 f(x) dx \\quad (6)$$\n\nDonde $\\int$ es el símbolo de una integral y $S_x$ se conoce con el soporte de la v.a $X$.\n\nTomando en cuenta todo el dominio de los números reales, la función de probabilidad acumulada completa se define a trozos de la siguiente manera:\n\n$$\nF(x) = \n\\begin{cases} \n0 & \\text{si } x < 0 \\\\\n\\frac{1}{4}x^2 & \\text{si } 0 \\le x \\le 2 \\\\\n1 & \\text{si } x > 2 \n\\end{cases}\n$$\n\nA diferencia de la función de densidad (que era una línea recta), la función de probabilidad acumulada en este caso es una curva cuadrática que crece desde 0 hasta 1.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/figura 10 grafica_acumulada-1.png)\n:::\n:::\n\n\nLas variables aleatorias continuas más comúnmente utilizadas son: la variable aleatoria uniforme, variable aleatoria normal, variable aleatoria exponencial, variable aleatoria Ji-cuadrada, variable aleatoria t de Student y la variable aleatoria F de Fisher o de Snedecor.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/figura11-1.png){fig-align='center'}\n:::\n:::\n\n\n<p align=\"center\">\n\n<b>Figura 11. Principales variables aleatorias continuas.</b>\n\n</p>\n\nEn primer lugar, haremos revisión de la variable aleatoria uniforme y luego trataremos de manera especial la variable aleatoria normal. *La variable aleatoria normal tiene alta importancia, debido a que una gran parte de las metodologías de estadísticas inferenciales la emplean como base.*\n\n## Distribución uniforme continua {#sec-uniforme-continua}\n\nUna de las distribuciones continuas más simples e intuitivas es la distribución uniforme continua. Decimos que una variable aleatoria $Y$ tiene una distribución uniforme en el intervalo $[a, b]$ si su probabilidad es constante para cualquier subintervalo de la misma longitud dentro de ese rango. En otras palabras, la función de densidad de probabilidad es plana y constante sobre el intervalo de valores posibles.\n\n**Función de densidad de probabilidad** Si una variable aleatoria $Y$ tiene una distribución de probabilidad uniforme en el intervalo $[a, b]$, entonces la función de densidad de probabilidad se define como:\n\n$$f(y) = \\begin{cases} \\frac{1}{b - a} & \\text{para } a \\le y \\le b \\\\ 0 & \\text{en cualquier otro caso} \\end{cases}$$\n\nDonde: \\* $a$ es el valor mínimo (límite inferior). \\* $b$ es el valor máximo (límite superior). \\* La altura constante $\\frac{1}{b - a}$ asegura que el área total bajo la curva (que forma un rectángulo) sea exactamente 1, cumpliendo con la propiedad de las funciones de densidad.\n\nPara esta distribución continua, la esperanza matemática (media) y la varianza están dadas por las siguientes expresiones:\n\n$$E[Y] = \\frac{a +b}{2}$$ $$\\text{Var}(Y) = \\frac{(b - a)^2}{12}$$\n\n------------------------------------------------------------------------\n\n**Ejemplo 1**\n\nSuponga que el tiempo que un estudiante debe esperar en la parada para que llegue un autobús universitario está distribuido uniformemente entre 0 y 20 minutos. Considere la variable aleatoria $Y$ como el tiempo de espera del estudiante.\n\nEn este caso, $Y \\sim U(0, 20)$, donde los parámetros de la distribución son $a = 0$ y $b = 20$.\n\nLa función de densidad de probabilidad del tiempo de espera es:\n\n$$f(y) = \\begin{cases} \\frac{1}{20} & \\text{si } 0 \\le y \\le 20 \\\\ 0 & \\text{en cualquier otro caso} \\end{cases}$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/figura_uniforme-1.png)\n:::\n:::\n\n\n**Cálculo de la Esperanza y Varianza**\n\n¿Cuál es el tiempo promedio esperado de espera del estudiante? $$E[Y] = \\frac{0 + 20}{2} = 10 \\text{ minutos}$$\n\n¿Y la varianza de dicho tiempo? $$\\text{Var}(Y) = \\frac{(20 - 0)^2}{12} = \\frac{400}{12} \\approx 33.33 \\text{ minutos}^2$$\n\nLa desviación estándar, que mide la dispersión, es $\\sigma = \\sqrt{33.33} \\approx 5.77 \\text{ minutos}$.\n\n**Cálculo de Probabilidad Acumulada**\n\nSupongamos que el estudiante desea calcular la probabilidad de que el autobús llegue en un lapso de entre 5 y 10 minutos.\n\nPodemos calcular esta probabilidad obteniendo geométricamente el área del rectángulo delimitado en el intervalo de $y = 5$ a $y = 10$:\n\n$$P(5 \\le Y \\le 10) = \\int_{5}^{10} f(y) dy = (10 - 5) \\cdot \\frac{1}{20} = 5 \\cdot \\frac{1}{20} = \\frac{1}{4} = 0.25$$\n\nPor lo tanto, existe un 25% de probabilidad de que el tiempo de espera oscile entre los 5 y 10 minutos.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/figura_prob_acumulada-1.png)\n:::\n:::\n\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. El tiempo que tarda un cajero en atender a un cliente se distribuye uniformemente entre 2 y 8 minutos. Calcule $E[X]$, $\\text{Var}(X)$ y la probabilidad de que un cliente sea atendido en menos de 4 minutos.\n2. Una variable aleatoria $Y$ tiene distribución uniforme en el intervalo $[10, 30]$. Calcule $P(15 \\le Y \\le 25)$ y la desviación estándar de $Y$.\n3. Explique, con sus propias palabras, por qué la función de densidad de una variable continua puede tomar valores mayores a 1, mientras que la función de probabilidad de una variable discreta nunca puede superar 1.\n\n:::\n\n## Distribución normal {#sec-normal}\n\nCuando nace un bebé, el médico lo lleva a la balanza y observa que pesa 3.5 kg. Lo primero que dirá, casi con certeza, es que tiene un peso normal. Luego, cuando el niño comienza su vida escolar, es probable que alguna psicopedagoga luego de efectuar un test informe a la maestra que tiene una inteligencia normal. Cuando ya adolescente asista a un colegio secundario y termine el año con 5 amonestaciones, la madre probablemente tratará de justificarlo diciendo que es un chico normal. Si al llegar a adulto se dedica a sembrar papas y dice que ha obtenido un rendimiento de 10000 kg por ha seguramente pensará que eso es lo normal.\n\nAhora bien, ¿Qué queremos expresar cuando decimos que es normal?\n\nLo que queremos decir es que, a la mayoría de las personas, en situaciones similares a las del joven en el ejemplo anterior, les pasa lo mismo. Podemos pensar, por ejemplo, que 95% de los bebés que nacen pesan entre 3 kg y 4 kg, que el mismo porcentaje de niños tienen un coeficiente de inteligencia entre 95 y 105, que 95% de los adolescentes terminan un año escolar con una cantidad de amonestaciones entre 3 y 7. Pero, como toda regla tiene excepciones, siempre habrá un porcentaje mínimo de nacimientos prematuros, de niños superdotados, de adolescentes que son bien portados y no presentan amonestaciones. Un razonamiento lógico nos lleva a concluir que todas estas situaciones tienen una baja probabilidad de ocurrir.\n\nLa ilustración probabilística de los anteriores fenómenos sería como la siguiente:\n\nSi un médico se tomara el trabajo de pesar, por ejemplo, a 500 niños recién nacidos. Registrar estos valores en una base de datos, después construir con ellos intervalos de clase y calcular las frecuencias absolutas en dichos intervalos; por último, graficar los datos por medio de un histograma, es muy probable que obtenga la siguiente distribución.\n\nSi unimos los puntos medios de los rectángulos de este histograma podemos dibujar una línea curva bastante parecida a una campana simétrica como se muestra a continuación:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/figura14_15-1.png)\n:::\n:::\n\n\nEsta curva, obtenida empíricamente, se asemeja a una curva teórica unimodal y perfectamente simétrica que caracteriza a una distribución de probabilidad conocida como distribución normal o también llamada *campana de Gauss*.\n\nLa distribución normal presenta un valor de mayor frecuencia en el centro y, a partir de él, decae hacia ambos lados con una simetría perfecta. Esta simetría hace que, a valores situados a igual distancia del valor central, por izquierda y por derecha de la distribución, les corresponda la misma probabilidad.\n\nConsiderando la situación del médico y el peso de los 500 niños, podemos pensar que existe una gran cantidad de bebés que tienen un peso de 3.5 kg y a partir de este valor las frecuencias disminuyen a ambos lados respetando la perfecta simetría de la distribución normal.\n\nPara una variable aleatoria $X$ su función de densidad de probabilidad es:\n\n$$f(x) = \\frac{1}{\\sigma\\sqrt{2\\pi}} e^{-\\frac{1}{2}\\left(\\frac{x - \\mu}{\\sigma}\\right)^2} \\quad \\text{para } -\\infty < x < \\infty \\quad (14)$$\n\nGeométricamente $f(x)$ se visualiza como la línea en forma de campana.\n\nSiendo $\\mu$ y $\\sigma$, los dos parámetros que caracterizan a una distribución normal donde: \\* $\\mu$: media aritmética \\* $\\sigma$: desviación estándar\n\nAdemás, $\\pi \\approx 3.1416$ y $e \\approx 2.71828$ son dos constantes en matemáticas.\n\nLa función de probabilidad acumulada de la variable aleatoria normal $X$ es la siguiente:\n\n$$F(x) = \\int_{-\\infty}^{x} \\frac{1}{\\sigma\\sqrt{2\\pi}} e^{-\\frac{1}{2}\\left(\\frac{t - \\mu}{\\sigma}\\right)^2} dt \\quad \\text{para } -\\infty < x < \\infty$$\n\nAl evaluar un valor $x$ en $F(x)$ se obtiene el área bajo la curva, desde $-\\infty$ hasta $x$.\n\nEn símbolos matemáticos se dice que la variable aleatoria $X$ tiene distribución normal con media $\\mu$ y desviación estándar $\\sigma$ de la siguiente forma: $$X \\sim N(\\mu, \\sigma)$$\n\nTambién se puede expresar como: $X$ tiene distribución normal con media $\\mu$ y varianza $\\sigma^2$ de la siguiente forma: $$X \\sim N(\\mu, \\sigma^2)$$\n\nPor ser la distribución perfectamente simétrica, la media coincide con la mediana y la moda, estos tres conceptos se encuentran en un mismo punto en el eje de abscisas que divide a la distribución de la variable aleatoria en dos partes iguales. La media es un parámetro de localización, esto le permite desplazarse sobre el eje de las $x$ a la distribución. En la figura 18 se observan tres distribuciones normales con diferentes medias.\n\nLa figura 18 se podría ajustar a un ejemplo hipotético donde se estudia el diámetro promedio de las plantas de agave en tres distintas parcelas de una misma región geográfica. Asumiendo que la variabilidad sea muy parecida en los tres lugares de la experimentación, dado que se encuentran en la misma región y que es el mismo tipo de agave, pero las medias puede que sean diferentes debido a que algunos productores invierten más en el cuidado que otros, obteniéndose distintos rendimientos.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/unnamed-chunk-1-1.png)\n:::\n:::\n\n\n\n\nLa desviación estándar $\\sigma$, medida de variabilidad de la distribución de la variable aleatoria, determina la mayor o menor dispersión de los datos alrededor de $\\mu$. Cuando $\\sigma$ crece, la curva se achata. El parámetro $\\sigma$ es un parámetro de forma.\n\nUn ejemplo de lo expresado en el gráfico 19 podría ser que $\\sigma_1$ fuera la desviación estándar de los pesos de niños de 10 años de edad en escuelas privadas de clase social alta, con similar estado nutricional; $\\sigma_2$ la de los pesos de los niños de 10 años de escuelas públicas y privadas, de clase social media y alta, con estado nutricional más variable; y $\\sigma_3$ la medida de variabilidad correspondiente al peso de niños de 10 años de edad de escuelas públicas en general, donde se observa una gran variabilidad respecto del estado nutricional de los alumnos.\n\nEn síntesis, se observa que un cambio en el valor de $\\mu$, desplaza toda la distribución normal pero no altera su forma. Por el contrario, si analizamos la Figura 19 vemos que un cambio en el valor de $\\sigma$ no desplaza la curva, sino que altera su forma, haciéndola más estrecha a medida que disminuye su valor.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/figura19-1.png)\n:::\n:::\n\n\n\n#### Característica de la distribución normal\n\n-   El área total bajo la curva normal es igual a 1, por ser una función de distribución de probabilidad, es decir: $$P(-\\infty < X < \\infty) = 1$$\n\n-   La normal es simétrica con respecto a $\\mu= \\frac{1}{2}$ de las observaciones se encuentran por debajo de la media $\\mu$ y $\\frac{1}{2}$ por encima de ella. $$P(-\\infty < X < \\mu) = 0.50 \\quad \\text{y} \\quad P(\\mu < X < \\infty) = 0.50$$\n\n-   En el intervalo $(\\mu - \\sigma; \\mu + \\sigma)$ se encuentra aproximadamente el 68.2% de las observaciones. $$P(\\mu - \\sigma < X < \\mu + \\sigma) = 0.682$$\n\n-   En el intervalo $(\\mu - 2\\sigma; \\mu + 2\\sigma)$ se encuentra el 95.4% de las observaciones. $$P(\\mu - 2\\sigma < X < \\mu + 2\\sigma) = 0.954$$\n\n-   En el intervalo $(\\mu - 3\\sigma; \\mu + 3\\sigma)$ se encuentra el 99.8% de las observaciones. $$P(\\mu - 3\\sigma < X < \\mu + 3\\sigma) = 0.998$$\n\nContextualizando las variables, sea la variable continua \"altura de niños\" de una determinada edad en la ciudad de Aguascalientes, Ags. Cuya media ($\\mu = 1.30 \\text{ m}$) y desviación estándar ($\\sigma = 0.12 \\text{ m}$). Si la distribución de la variable \"altura de niños\" proviene de una variable aleatoria normal se podrían aplicar las últimas tres propiedades:\n\n1.  El 68.2% de los niños mide entre $(1.30 - 0.12)$ y $(1.30 + 0.12)$, es decir, 68.2% de estos niños tendrán una altura comprendida en el intervalo: $(1.18; 1.42)$.\n2.  El 95.4% de los niños tiene una altura comprendida en el intervalo $(1.06; 1.54)$.\n3.  El 99.8% de los niños tiene una altura comprendida en el intervalo $(0.94; 1.66)$.\n\nVisualmente tenemos lo siguiente:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/regla_empirica-1.png)\n:::\n:::\n\n\n## Distribución normal estándar\n\nA menudo, calcular las probabilidades asociadas a una distribución normal arbitraria $X \\sim N(\\mu, \\sigma)$ implica resolver una integral compleja. Para simplificar esto, se recurre a un proceso llamado **estandarización**. \n\nUna variable aleatoria normal estandarizada, comúnmente denotada como $Z$, es aquella que tiene una media de cero ($\\mu = 0$) y una varianza de uno ($\\sigma^2 = 1$).\n\nLa función de densidad de probabilidad de una variable aleatoria normal estándar $Z$ es:\n\n$$f(z) = \\frac{1}{\\sqrt{2\\pi}} e^{-\\frac{z^2}{2}} \\quad \\text{para } -\\infty < z < \\infty \\quad (15)$$\n\nLa función de probabilidad acumulada de $Z$ es:\n\n$$P(Z \\le z_0) = F_Z(z_0) = \\int_{-\\infty}^{z_0} \\frac{1}{\\sqrt{2\\pi}} e^{-\\frac{z^2}{2}} dz \\quad (16)$$\n\nVemos que nuevamente aparece el símbolo de integral ($\\int$), que como ya hemos dicho, sirve para calcular el área bajo la curva hasta un cierto valor $z_0$. La representación gráfica de la función de densidad de probabilidad de una variable normal estandarizada es la siguiente:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/figura_normal_estandar-1.png)\n:::\n:::\n\n\n\nComo podemos observar, la función de densidad de probabilidad de una variable estandarizada $Z$ es perfectamente simétrica con respecto al valor $\\mu = 0$.\n\nAl trabajar con una variable normal estandarizada también se cumple la regla empírica de manera directa, ya que las desviaciones estándar equivalen exactamente a los valores de $z$:\n* $P(-1 < Z < 1) = 0.6826 \\approx 0.683$\n* $P(-2 < Z < 2) = 0.9544 \\approx 0.954$\n* $P(-3 < Z < 3) = 0.9974 \\approx 0.998$\n\n---\n\n**Estandarización de una variable normal**\n\nCualquier variable aleatoria normal $X$ con media $\\mu$ y desviación estándar $\\sigma$ puede ser transformada en una variable normal estándar $Z$ mediante la siguiente fórmula de tipificación:\n\n$$Z = \\frac{X - \\mu}{\\sigma}$$\n\nEsta transformación nos dice a cuántas desviaciones estándar ($\\sigma$) se encuentra un valor $X$ por encima o por debajo de la media $\\mu$. Al hacer esto, podemos usar las tablas de la normal estándar (o software estadístico) para calcular probabilidades para **cualquier** distribución normal.\n\n**Ejemplo 1**\n\nSuponga que los puntajes de un examen de aptitud a nivel nacional están distribuidos normalmente con una media $\\mu = 400$ y una desviación estándar $\\sigma = 50$. \n\n**Pregunta 1:** ¿Cuál es la probabilidad de que un estudiante elegido al azar obtenga un puntaje mayor a 450?\n\nQueremos calcular $P(X > 450)$. Primero, estandarizamos el valor $x = 450$:\n\n$$z = \\frac{x - \\mu}{\\sigma} = \\frac{450 - 400}{50} = \\frac{50}{50} = 1$$\n\nPor lo tanto, la probabilidad requerida es equivalente a encontrar la probabilidad en la normal estándar para $Z > 1$:\n$$P(X > 450) = P(Z > 1)$$\n\nSabiendo que la distribución es simétrica y el área total es 1, usando las propiedades o una tabla, determinamos que $P(Z > 1) \\approx 0.1587$. Es decir, hay un 15.87% de probabilidad de que el estudiante obtenga más de 450 puntos.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/ejemplo_wackerly_1-1.png)\n:::\n:::\n\n\n**Pregunta 2:** ¿Cuál es la probabilidad de que un estudiante obtenga un puntaje entre 300 y 450?\n\nQueremos calcular $P(300 < X < 450)$. Estandarizamos ambos límites:\n\nPara $x_1 = 300$:\n$$z_1 = \\frac{300 - 400}{50} = \\frac{-100}{50} = -2$$\n\nPara $x_2 = 450$:\n$$z_2 = \\frac{450 - 400}{50} = \\frac{50}{50} = 1$$\n\nLa probabilidad buscada es:\n$$P(300 < X < 450) = P(-2 < Z < 1)$$\n\nCalculando el área entre $Z = -2$ y $Z = 1$ (que es $F(1) - F(-2)$):\n$$P(-2 < Z < 1) = 0.8413 - 0.0228 = 0.8185$$\n\nEl 81.85% de los estudiantes obtendrán puntajes entre 300 y 450.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/ejemplo_wackerly_2-1.png)\n:::\n:::\n\n\n#### Uso de tablas\n\nPara calcular probabilidades de la variable aleatoria normal deberíamos aplicar la operación integral a la función de densidad, reemplazando los parámetros $\\mu$ y $\\sigma$ por los valores de alguna combinación en particular. Teniendo en cuenta que la expresión matemática de la función de densidad de una variable normalmente distribuida no tiene una antiderivada de forma cerrada (como bien señala la teoría estadística clásica), calcular probabilidades con base en ella mediante integración analítica es imposible, requiriendo métodos numéricos. Por este motivo, se ilustra el uso de tablas estadísticas estandarizadas.\n\nLa tabla de probabilidades normales está construida considerando una distribución normal con media $\\mu = 0$ y desviación estándar $\\sigma = 1$, o lo que es lo mismo, para la variable que hemos denominado variable normal estandarizada $Z$. Esta tabla puede ser usada para obtener probabilidades asociadas con cualquier distribución normal, siempre que la media y la varianza sean conocidas.\n\nPara obtener las probabilidades de una variable aleatoria normal $X$ con el uso de las tablas, primero debemos estandarizar dicha variable mediante el teorema fundamental:\n$$Z = \\frac{X - \\mu}{\\sigma}$$\n\nLa tabla para calcular probabilidades de una distribución normal estandarizada está construida considerando probabilidades acumuladas, en otras palabras:\n$$P(Z \\le z_0) = F(z_0)$$\nEsta es la probabilidad acumulada desde $-\\infty$ hasta $z_0$, donde este último es un valor particular de la variable $Z$.\n\n::: {.callout-note icon=false}\n## Nota\nEn las distribuciones de probabilidad continuas, la probabilidad de que la variable aleatoria asuma exactamente un valor particular es cero ($P(X = x) = 0$). Por lo tanto, los signos de desigualdad estricta ($<$, $>$) o no estricta ($\\le$, $\\ge$) son probabilísticamente equivalentes. Es decir, $P(X \\le x) = P(X < x)$.\n\n:::\n\n::: {.callout-caution icon=false}\n## Errores comunes: variables aleatorias continuas\n\n**Error 1 — Interpretar $P(X = x) = 0$ como \"el evento es imposible\".**  \nPara una variable continua, cada punto tiene probabilidad cero, pero eso no significa que sea imposible observar ese valor — de hecho, siempre se observa algún valor exacto. Lo que es cero es la probabilidad de *un solo punto*; la probabilidad de un intervalo puede ser positiva.\n\n**Error 2 — Confundir el valor de la pdf con una probabilidad.**  \nLa función de densidad $f(x)$ puede tomar valores mayores que 1 (por ejemplo, $U(0, 0.5)$ tiene $f(x) = 2$). Lo que siempre está en $[0,1]$ es el *área* bajo la curva en un intervalo, que es la probabilidad real: $P(a \\leq X \\leq b) = \\int_a^b f(x)\\,dx$.\n\n:::\n\n\n\n**Ejemplo 2**\nEl peso de los niños al nacer en la localidad de Tequila tiene el comportamiento de una variable aleatoria normal con media $\\mu = 3.5 \\text{ kg}$ y desviación estándar $\\sigma = 1 \\text{ kg}$. \n\nCon base en este ejemplo, estudiaremos cómo calcular probabilidades bajo diferentes escenarios usando la estandarización $Z$. $X$ se distribuye normal y se denota como $X \\sim N(3.5, 1^2)$.\n\n---\n\n**Caso 1: Probabilidad de que $X$ sea menor a un valor dado**\\\\\n**¿Cuál es la probabilidad de que un recién nacido tenga un peso menor a 3.9 kg?**\n\nLa probabilidad de interés es $P(X < 3.9)$. Como $X$ es continua, la probabilidad acumulada se calcula indistintamente como $P(X \\le 3.9) = F(3.9)$.\n\nEstandarizando la variable:\n$$P(X < 3.9) = P\\left(\\frac{X - \\mu}{\\sigma} \\le \\frac{3.9 - 3.5}{1}\\right) = P(Z \\le 0.4)$$\n\nEn la tabla de la normal estándar, buscamos el valor $0.4$ en la primera columna (enteros y primer decimal) y $.00$ en la primera fila (segundo decimal). En su intersección encontramos la probabilidad:\n$$F(3.9) = P(X \\le 3.9) = P(Z \\le 0.4) = 0.6554$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/caso1_z04-1.png)\n:::\n:::\n\n\n---\n\n**Caso 2: Probabilidad de que $Z$ exceda un valor positivo**\n**Encontrar la probabilidad de que un niño presente un peso de más de 3.9 kg.**\n\nEsto se traduce en encontrar $P(Z > 0.4)$. La tabla normal acumula desde $-\\infty$, por lo que para buscar la \"cola superior\" o derecha, usamos la propiedad del complemento (toda el área vale 1):\n\n$$P(Z > 0.40) = 1 - P(Z \\le 0.40) = 1 - F(0.40) = 1 - 0.6554 = 0.3446$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/caso2_z04_mayor-1.png)\n:::\n:::\n\n\n---\n\n**Caso 3: Probabilidad menor a un número negativo**\n**El médico quiere conocer la probabilidad de que un niño pese menos de 2.1 kg al nacer.**\n\n$$P(X < 2.1) = P\\left(\\frac{X - 3.5}{1} \\le \\frac{2.1 - 3.5}{1}\\right) = P(Z \\le -1.4) = F(-1.4)$$\n\nAplicando la **propiedad de simetría** de la curva normal (Mendenhall et al.), la cola izquierda en $-1.4$ es exactamente igual a la cola derecha en $+1.4$:\n$$P(Z \\le -1.4) = P(Z \\ge 1.4) = 1 - P(Z \\le 1.4)$$\n\nBuscamos $1.4$ en la tabla: $P(Z \\le 1.4) = 0.9192$.\n$$P(Z \\le -1.4) = 1 - 0.9192 = 0.0808$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/caso3_z14_negativo-1.png)\n:::\n:::\n\n\n---\n\n**Caso 4: Intervalo entre dos valores positivos**\n**Calcular la probabilidad de que un niño pese entre 3.6 kg y 4.0 kg.**\n\nEstandarizamos los dos límites del intervalo:\n$$P(3.6 \\le X \\le 4) = P\\left(\\frac{3.6 - 3.5}{1} \\le Z \\le \\frac{4 - 3.5}{1}\\right) = P(0.1 \\le Z \\le 0.5)$$\n\nPara encontrar el área de este \"corte central\", restamos el área acumulada del límite inferior al área del límite superior:\n$$P(0.1 \\le Z \\le 0.5) = F(0.5) - F(0.1)$$\n$$= 0.6915 - 0.5398 = 0.1517$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/caso4_intervalo_pos-1.png)\n:::\n:::\n\n\n---\n\n**Caso 5: Intervalo entre dos valores negativos**\n**La probabilidad de que un niño al nacer pese entre 2 kg y 2.5 kg.**\n\n$$P(2 \\le X \\le 2.5) = P\\left(\\frac{2 - 3.5}{1} \\le Z \\le \\frac{2.5 - 3.5}{1}\\right) = P(-1.5 \\le Z \\le -1)$$\n\nPor la propiedad de simetría respecto de $\\mu = 0$, este intervalo a la izquierda es idéntico a su contraparte positiva en la derecha:\n$$P(-1.5 \\le Z \\le -1) = P(1 \\le Z \\le 1.5) = F(1.5) - F(1)$$\n$$= 0.9332 - 0.8413 = 0.0919$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/caso5_intervalo_neg-1.png)\n:::\n:::\n\n\n---\n\n**Caso 6: Intervalo que incluye al 0 (media)**\n**La probabilidad de que un niño pese al nacer entre 3 kg y 4 kg.**\n\n$$P(3 \\le X \\le 4) = P\\left(\\frac{3 - 3.5}{1} \\le Z \\le \\frac{4 - 3.5}{1}\\right) = P(-0.5 \\le Z \\le 0.5)$$\n\nCalculamos usando las acumuladas:\n$$P(-0.5 \\le Z \\le 0.5) = F(0.5) - F(-0.5)$$\n\nUsando simetría para resolver $F(-0.5)$, sabemos que $F(-0.5) = 1 - F(0.5)$. Sustituyendo:\n$$= F(0.5) - [1 - F(0.5)]$$\n$$= 2F(0.5) - 1$$\n$$= 2(0.6915) - 1 = 1.3830 - 1 = 0.3830$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/caso6_intervalo_cero-1.png)\n:::\n:::\n\n\n### Ejemplos adicionales: Distribución Normal\n\n::: {.callout-tip icon=false}\n## Ejemplo: Control de calidad — tornillos\n\nLa longitud $X$ de ciertos tornillos (en mm) sigue una distribución $N(\\mu=30, \\sigma^2=0.04)$. Se aceptan como válidos aquellos con $29.5 < X < 30.4$.\n\n**Preguntas:**\n\n1. Proporción de tornillos no aceptables por cortos ($X \\le 29.5$).\n2. Proporción de tornillos no aceptables por largos ($X \\ge 30.4$).\n3. Si se produce un lote de 1,000 tornillos, ¿cuántos se esperan defectuosos?\n\n**Solución:**\n\nEstandarizando: $Z = (X - 30)/0.2 \\sim N(0,1)$.\n\n\n::: {.cell}\n\n```\n#> P(cortos) = P(X <= 29.5) = 0.0062\n#>   Z = (29.5 - 30)/0.2 = -2.5\n#> P(largos) = P(X >= 30.4) = 0.0228\n#>   Z = (30.4 - 30)/0.2 = 2\n#> P(defectuosos total) = 0.029\n#> Esperados en 1,000 piezas: E[Y] = 1000 × 0.029 = 29\n```\n\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/normal-tornillos-1.png)\n:::\n:::\n\n\n:::\n\n::: {.callout-tip icon=false}\n## Ejemplo: Especificación de longitud máxima de clavos\n\nLa longitud $X$ de clavos fabricados por una máquina sigue $N(\\mu=10\\text{ mm},\\, \\sigma^2=4)$. Se desea determinar la longitud máxima $x^*$ tal que el 90% de los clavos cumpla con la especificación.\n\n**Planteamiento:** Se requiere $P(X \\le x^*) = 0.90$.\n\n**Solución:**\n\n$$\\Phi\\!\\left(\\frac{x^* - 10}{2}\\right) = 0.90 \\implies \\frac{x^* - 10}{2} = z_{0.90} = 1.28 \\implies x^* = 12.56 \\text{ mm}$$\n\n\n::: {.cell}\n\n```\n#> z_{0.90} = 1.2816\n#> x* = mu + z * sigma = 10 + 1.2816 * 2 = 12.5631 mm\n#> Verificación: P(X <= x*) = 0.9\n```\n:::\n\n\nLa especificación de longitud máxima debe ser $x^* \\approx 12.56$ mm para que el 90% de los clavos la cumpla.\n\n:::\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. El tiempo de reacción a un estímulo se distribuye $N(0.8, 0.1^2)$ segundos. Calcule la probabilidad de que el tiempo de reacción sea mayor a 1 segundo.\n2. Las calificaciones de un examen siguen una distribución $N(70, 10^2)$. ¿Qué porcentaje de estudiantes obtiene una calificación entre 60 y 80?\n3. Si $X \\sim N(50, 5^2)$, estandarice los valores $x=45$ y $x=60$, y calcule $P(45 \\le X \\le 60)$ usando la tabla de la normal estándar.\n\n:::\n\n## Distribución exponencial {#sec-exponencial}\n\nLa variable aleatoria exponencial surge en la práctica como el modelo para la probabilidad de la cantidad de tiempo u espacio que transcurre hasta que ocurre un evento de interés. Esta ocurrencia se da de manera independiente y a una tasa constante.\n\n**Ejemplos**\n* La cantidad de tiempo (a partir de ahora) hasta que ocurre un terremoto.\n* La cantidad de tiempo (a partir de ahora) hasta que estalla una nueva guerra.\n* La cantidad de tiempo (a partir de ahora) hasta que una llamada telefónica que reciba resulte ser un número equivocado.\n\nTambién es utilizada para determinar el tiempo entre llegadas de clientes a una cola de un supermercado, el tiempo entre fallas de un componente electrónico o el tiempo entre accidentes en una autopista.\n\n::: {.callout-note icon=false}\n## Nota\nEn la literatura estadística existen dos formas comunes de parametrizar la distribución exponencial. En muchos textos aplicados (y en este documento), se utiliza el parámetro de tasa $\\lambda$ (número de ocurrencias por unidad de tiempo). Sin embargo, en algunos textos teóricos utilizan el parámetro de escala $\\beta$, que representa el **tiempo promedio** de espera entre eventos, donde $\\beta = \\frac{1}{\\lambda}$. Ambas formas son equivalentes, pero es crucial identificar cuál se está utilizando al resolver problemas.\n\n:::\n\nUtilizando la parametrización por tasa ($\\lambda$), la función de densidad de probabilidad de una variable exponencial $X$, denotada como $X \\sim \\text{Exp}(\\lambda)$, está dada por:\n\n$$f(x) = \\begin{cases} \\lambda e^{-\\lambda x} & \\text{para } x \\ge 0, \\quad \\lambda > 0 \\\\ 0 & \\text{en otro caso} \\end{cases} \\quad (16)$$\n\nLa forma de la distribución cambia de acuerdo con el valor de $\\lambda$. En la figura 28 se presenta la función de densidad de probabilidad de la variable aleatoria exponencial para tres valores distintos de $\\lambda$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/figura28_exponencial-1.png)\n:::\n:::\n\n\n\n\nLa esperanza matemática (valor esperado) y la varianza de la variable aleatoria exponencial son:\n\n$$E[X] = \\frac{1}{\\lambda}$$\n$$\\text{Var}(X) = \\frac{1}{\\lambda^2}$$\n\nLa función de probabilidad acumulada (que nos da el área a la izquierda de un valor $x$) es:\n\n$$F(x) = P(X \\le x) = 1 - e^{-\\lambda x} \\quad \\text{para } x \\ge 0 \\quad (17)$$\n\n---\n\n**Ejemplo 1: Servicio de asistencia técnica**\n\nUn servicio de asistencia técnica en carretera ha comprobado que en las mañanas de los fines de semana el número de llamadas que recibe es de 3 llamadas cada hora. Un operario comienza su jornada de sábado a las 8 de la mañana. Suponiendo que las llamadas se realizan de manera independiente y con tasa constante:\n\n**¿Cuál es la probabilidad de que reciba la primera llamada antes de las 8:15 am?**\n\nSea $X$ una variable aleatoria que mide el tiempo transcurrido (a partir de las 8:00 am) hasta que ocurre una llamada. $X$ es una variable aleatoria exponencial con un parámetro de tasa $\\lambda = 3$ (llamadas por hora). \n\nLa función de probabilidad acumulada (Ecuación 17) para esta variable es:\n$$F(x) = 1 - e^{-3x} \\quad \\text{para } x \\ge 0$$\n\nComo el operario empieza a las 8:00 am, para las 8:15 am habrán pasado 15 minutos. Dado que la tasa $\\lambda$ está en términos de horas, **es obligatorio** expresar el tiempo en las mismas unidades. Los 15 minutos equivalen a $15/60 = 0.25$ horas.\n\nLa probabilidad de interés es:\n$$P(X \\le 0.25) = F(0.25) = 1 - e^{-3(0.25)} = 1 - e^{-0.75} \\approx 0.5276$$\n\nExiste aproximadamente un 52.8% de probabilidad de recibir la primera llamada en los primeros 15 minutos de la jornada.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/ejemplo1_asistencia-1.png)\n:::\n:::\n\n\n---\n\n**Ejemplo 2: Tiempo de revisión de motores**\n\nEl tiempo de revisión del motor de un avión sigue una distribución exponencial con una media igual a 22 minutos.\n\nPrimero, definimos la variable aleatoria:\n$X$: Tiempo de revisión del motor de un avión (en minutos).\n\nSe nos proporciona la esperanza matemática (media), $E[X] = 22$. Despejando el parámetro $\\lambda$:\n$$E[X] = \\frac{1}{\\lambda} = 22 \\implies \\lambda = \\frac{1}{22}$$\n\nDe modo que la función de densidad y la función acumulada son:\n$$f(x) = \\frac{1}{22} e^{-\\frac{x}{22}} \\quad \\text{y} \\quad F(x) = 1 - e^{-\\frac{x}{22}} \\quad \\text{para } x \\ge 0$$\n\n**Inciso a) Encontrar la probabilidad de que el tiempo de revisión sea menor a 10 minutos.**\n\nBuscamos $P(X \\le 10)$:\n$$P(X \\le 10) = 1 - e^{-\\frac{10}{22}} \\approx 1 - 0.6348 = 0.3652$$\n\n**Inciso b) ¿Cuál es el tiempo de revisión de un motor que ha superado el 10% de los tiempos de revisión más largos?**\n\n::: {.callout-note icon=false}\n## Nota\nEstar en el 10% de los tiempos más largos significa que el tiempo de reparación deja al 90% de los casos por debajo de él o al 10% por encima. A este punto lo denotaremos como $x_{0.10}$.\n\n:::\n\nLa ecuación de interés es:\n$$P(X \\ge x_{0.10}) = 1 - P(X \\le x_{0.10}) = 1 - \\left(1 - e^{-\\frac{x_{0.10}}{22}}\\right) = 0.10$$\n\nSimplificando y despejando $x_{0.10}$:\n$$e^{-\\frac{x_{0.10}}{22}} = 0.10$$\nAplicando logaritmo natural a ambos lados:\n$$-\\frac{x_{0.10}}{22} = \\ln(0.10)$$\n$$x_{0.10} = -22 \\cdot \\ln(0.10) \\approx -22 \\cdot (-2.3025) \\approx 50.66 \\text{ minutos}$$\n\n**Inciso c) El costo de revisión es de 200 unidades monetarias fijas, a lo que se suman 10 unidades por el tiempo que dure la revisión. Encontrar la media del costo.**\n\nSimbolizamos el costo total con $C$:\n$$C = 200 + 10X$$\n\nAplicando las propiedades de la esperanza matemática:\n$$E[C] = E[200 + 10X] = 200 + 10 \\cdot E[X] = 200 + 10(22) = 200 + 220 = 420$$\nLa media del costo de revisión es de 420 unidades monetarias.\n\n---\n\n**Propiedad fundamental: Falta de memoria**\n\nLa distribución exponencial es la **única** distribución de probabilidad continua que carece de memoria. ¿Qué quiere decir esto? Significa que la probabilidad condicional de que un evento ocurra en el futuro depende únicamente del tiempo restante y no del tiempo que ya ha transcurrido. Matemáticamente:\n\n$$P(X > s + t \\mid X > t) = P(X > s) \\quad \\text{para toda } s, t \\ge 0 \\quad (18)$$\n\nEsto significa que si la probabilidad de tener que esperar 10 minutos *adicionales* para una llamada telefónica, **dado que ya hemos esperado 30 minutos sin éxito**, es exactamente la misma que la probabilidad de haber esperado 10 minutos desde el instante inicial cero.\n\n$$P(X > 40 \\mid X > 30) = P(X > 10 + 30 \\mid X > 30) = P(X > 10)$$\n\n*Cuidado:* Esto no significa que los eventos $X > 40$ y $X > 30$ sean estadísticamente independientes. Si lo fueran, se cumpliría que $P(X > 40 \\mid X > 30) = P(X > 40)$, lo cual es falso. Lo que es independiente es el *tiempo adicional*.\n\n**Ejemplo 3**\n\nSi el operario lleva 10 minutos sin recibir una llamada: ¿Cuál es la probabilidad de que reciba una nueva llamada en los **próximos 15 minutos** (es decir, en menos de 25 minutos en total)?\n\nBuscamos: $P(X < 25 \\mid X > 10)$\n\nEmpleando el complemento de la Ecuación 18 de la falta de memoria, el tiempo ya transcurrido ($t=10$) se \"olvida\" y solo nos interesa el intervalo futuro ($s=15$):\n$$P(X < 15 + 10 \\mid X > 10) = P(X < 15)$$\n\nRecordando que $\\lambda = 3$ llamadas/hora y que 15 minutos son $0.25$ horas, calculamos:\n$$P(X < 0.25 \\text{ horas}) = 1 - e^{-3(0.25)} = 1 - e^{-0.75} \\approx 0.528$$\n\nEs exactamente la misma probabilidad calculada en el Ejemplo 1 al inicio del turno. El sistema \"no recuerda\" que el operario ya llevaba 10 minutos esperando.\n\n### Ejemplo adicional: Distribución Exponencial\n\n::: {.callout-tip icon=false}\n## Ejemplo: Tiempo de respuesta de una terminal\n\nEl tiempo de respuesta $X$ (en segundos) de cierta terminal de computadora en línea sigue una distribución exponencial con tiempo esperado de respuesta de 5 segundos, es decir, $E[X] = 1/\\lambda = 5$, por lo que $\\lambda = 0.2$.\n\n**Preguntas:**\n\n1. Probabilidad de que el tiempo de respuesta sea a lo sumo 10 segundos.\n2. Probabilidad de que el tiempo de respuesta esté entre 5 y 10 segundos.\n\n**Solución:**\n\n\n::: {.cell}\n\n```\n#> P(X <= 10) = 1 - e^{-2} = 0.8647\n#> P(5 <= X <= 10) = F(10) - F(5) = 0.2325\n#> Manual: (1 - e^{-2}) - (1 - e^{-1}) = e^{-1} - e^{-2} = 0.2325\n```\n\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/expo-terminal-1.png)\n:::\n:::\n\n\nEl resultado muestra que hay un 86.5% de probabilidad de que la terminal responda en menos de 10 segundos, confirmando que un tiempo esperado de 5 s implica respuestas rápidas la mayor parte del tiempo.\n\n:::\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. El tiempo entre llegadas de clientes a una caja registradora sigue una distribución exponencial con media de 5 minutos. Calcule la probabilidad de que transcurran más de 8 minutos entre dos clientes consecutivos.\n2. La duración de un componente electrónico sigue una distribución exponencial con $\\lambda = 0.02$ fallas por hora. Calcule la probabilidad de que el componente dure más de 100 horas.\n3. Usando la propiedad de falta de memoria, explique por qué la probabilidad de que un componente exponencial dure 50 horas más, dado que ya ha funcionado 200 horas, es la misma que la probabilidad de que dure más de 50 horas desde nuevo.\n\n:::\n\n## Distribución Gamma {#sec-gamma}\n\n::: {.content-visible when-format=\"html\"}\n[📖 Magín Zúñiga Estrada]{.fuente-badge .fuente-magin}\n\n:::\n\n\n::: {.callout-tip icon=false}\n## Fuente: Apuntes del curso (Prof. Magín Zúñiga Estrada)\n\n:::\n\nLa distribución Gamma generaliza la distribución exponencial y es ampliamente utilizada para modelar tiempos de espera acumulados y fenómenos con asimetría positiva.\n\n::: {.callout-note icon=false}\n## Definición: Distribución Gamma\n\nUna variable aleatoria continua $X$ tiene **distribución Gamma** con parámetros $\\alpha > 0$ (forma) y $\\lambda > 0$ (tasa) si su función de densidad es:\n$$f(x) = \\frac{\\lambda\\, e^{-\\lambda x}(\\lambda x)^{\\alpha-1}}{\\Gamma(\\alpha)}, \\quad x \\geq 0,$$\ndonde la **función Gamma** se define como:\n$$\\Gamma(\\alpha) = \\int_0^{\\infty} e^{-x}\\, x^{\\alpha-1}\\, dx.$$\n\nCuando $\\alpha = n$ entero positivo, $\\Gamma(n) = (n-1)!$\n\n**Propiedades:**\n\n- $E[X] = \\alpha/\\lambda$\n- $\\text{Var}(X) = \\alpha/\\lambda^2$\n- La suma de $n$ variables exponenciales independientes $\\text{Exp}(\\lambda)$ sigue una $\\text{Gamma}(n, \\lambda)$.\n- Caso especial: si $\\alpha = 1$, recuperamos la distribución $\\text{Exp}(\\lambda)$.\n\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/gamma-plot-1.png){fig-align='center'}\n:::\n:::\n\n\n\n::: {.callout-tip icon=false}\n## Ejemplo: Tiempo de atención en un banco\n\nEn una sucursal bancaria, el tiempo que tarda un cajero en atender a **un** cliente sigue una distribución $\\text{Exp}(\\lambda = 2)$ (en promedio, 2 clientes por minuto). Usted llega cuando hay **3 personas** en la fila delante de usted. Sea $X$ = tiempo total de espera (en minutos).\n\n**Identificación del modelo:**\n\nComo $X$ es la suma de 3 tiempos exponenciales independientes con la misma tasa $\\lambda = 2$:\n$$X = X_1 + X_2 + X_3, \\quad X_i \\sim \\text{Exp}(2) \\implies X \\sim \\text{Gamma}(\\alpha=3,\\; \\lambda=2)$$\n\n**a) Esperanza y varianza**\n\n$$E[X] = \\frac{\\alpha}{\\lambda} = \\frac{3}{2} = 1.5 \\text{ minutos}$$\n\n$$\\text{Var}(X) = \\frac{\\alpha}{\\lambda^2} = \\frac{3}{4} = 0.75 \\quad \\Rightarrow \\quad \\text{DE} = \\sqrt{0.75} \\approx 0.866 \\text{ min}$$\n\n**b) Probabilidad de esperar más de 2 minutos**\n\n$$P(X > 2) = 1 - F(2) = 1 - \\int_0^{2} \\frac{2\\,e^{-2x}(2x)^{2}}{\\Gamma(3)}\\,dx$$\n\nEn R: `pgamma(2, shape=3, rate=2, lower.tail=FALSE)`\n\n\n::: {.cell}\n\n```\n#> P(X > 2 min) = 0.2381\n#> P(0.5 < X < 1.5 min) = 0.4965\n```\n\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/gamma-banco-1.png)\n:::\n:::\n\n\n**Interpretación:** Hay un $23.8%$ de probabilidad de esperar más de 2 minutos.\n\n:::\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. El tiempo de vida (en años) de cierto tipo de batería sigue una distribución $\\text{Gamma}(3, 0.5)$. Calcule la probabilidad de que la batería dure más de 8 años.\n2. Demuestre que $\\Gamma(1/2) = \\sqrt{\\pi}$.\n3. Sea $X_1, \\ldots, X_n$ iid $\\sim \\text{Exp}(\\lambda)$. Demuestre que $Y = X_1 + \\cdots + X_n \\sim \\text{Gamma}(n, \\lambda)$.\n\n:::\n\n## Distribución Pareto {#sec-pareto}\n\n::: {.content-visible when-format=\"html\"}\n[📖 Magín Zúñiga Estrada]{.fuente-badge .fuente-magin}\n\n:::\n\n\n::: {.callout-tip icon=false}\n## Fuente: Apuntes del curso (Prof. Magín Zúñiga Estrada)\n\n:::\n\nLa distribución Pareto surge del estudio de distribuciones de ingresos: se observó que los ingresos que superaban un umbral $m$ se aproximaban mediante $C/x^{\\alpha}$. Este comportamiento de **cola pesada** también aparece en el tamaño de ciudades, reclamos de seguros y tamaño de empresas.\n\n::: {.callout-note icon=false}\n## Definición: Distribución Pareto\n\nUna variable aleatoria $X$ tiene **distribución Pareto** con parámetros $\\alpha > 0$ (índice de cola) y $m > 0$ (mínimo) si su función de densidad es:\n$$f(x) = \\frac{\\alpha\\, m^{\\alpha}}{x^{\\alpha+1}}, \\quad x > m.$$\n\nLa función de distribución acumulada es:\n$$F(x) = 1 - \\left(\\frac{m}{x}\\right)^{\\alpha}, \\quad x > m.$$\n\n**Propiedades:**\n\n- $E[X] = \\dfrac{\\alpha m}{\\alpha - 1}$ si $\\alpha > 1$.\n- $\\text{Var}(X) = \\dfrac{\\alpha m^2}{(\\alpha-1)^2(\\alpha-2)}$ si $\\alpha > 2$.\n- Cola más pesada que la exponencial: $P(X > x) = (m/x)^{\\alpha}$ decrece como potencia, no exponencialmente.\n\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/pareto-plot-1.png){fig-align='center'}\n:::\n:::\n\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. Los reclamos de un seguro siguen una distribución Pareto con $\\alpha = 3$ y $m = 1000$. Calcule $E[X]$ y la probabilidad de que un reclamo supere \\$5000.\n2. Demuestre que $F(x) = 1 - (m/x)^{\\alpha}$ es efectivamente una función de distribución (verificando que cumple las propiedades de cdf).\n3. Compare la tasa de decaimiento de la cola de una $\\text{Pareto}(2, 1)$ con una $\\text{Exp}(1)$: grafique $P(X > x)$ para ambas.\n\n:::\n\n\n## Distribución Weibull {#sec-weibull}\n\nLa distribución Weibull es una de las herramientas más versátiles en el análisis de confiabilidad y tiempo de falla. Su flexibilidad proviene de un parámetro de forma que le permite modelar tasas de falla crecientes, decrecientes o constantes.\n\n::: {.callout-note icon=false}\n## Definición: Distribución Weibull\n\nUna variable aleatoria $X \\geq 0$ tiene distribución **Weibull** con parámetro de forma $k > 0$ y parámetro de escala $\\lambda > 0$ si su función de densidad es:\n\n$$f(x) = \\frac{k}{\\lambda}\\left(\\frac{x}{\\lambda}\\right)^{k-1} \\exp\\!\\left[-\\left(\\frac{x}{\\lambda}\\right)^k\\right], \\quad x \\geq 0$$\n\nLa función de distribución acumulada tiene forma cerrada:\n\n$$F(x) = 1 - \\exp\\!\\left[-\\left(\\frac{x}{\\lambda}\\right)^k\\right], \\quad x \\geq 0$$\n\n**Propiedades:**\n\n- $E[X] = \\lambda\\,\\Gamma\\!\\left(1 + \\tfrac{1}{k}\\right)$\n- $\\text{Var}(X) = \\lambda^2\\left[\\Gamma\\!\\left(1+\\tfrac{2}{k}\\right) - \\Gamma\\!\\left(1+\\tfrac{1}{k}\\right)^2\\right]$\n- **Función de riesgo (tasa de falla):** $h(x) = \\dfrac{f(x)}{1-F(x)} = \\dfrac{k}{\\lambda}\\left(\\dfrac{x}{\\lambda}\\right)^{k-1}$\n\n**Casos especiales según el parámetro de forma $k$:**\n\n| $k$ | Comportamiento de $h(x)$ | Distribución equivalente |\n|:---:|:------------------------:|:------------------------:|\n| $k < 1$ | Decreciente (fallas tempranas) | — |\n| $k = 1$ | Constante | $\\text{Exp}(1/\\lambda)$ |\n| $k = 2$ | Creciente lineal | Distribución de Rayleigh |\n| $k \\approx 3.6$ | Casi simétrica | Aproxima a la Normal |\n| $k > 1$ | Creciente (desgaste) | — |\n\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/weibull-plot-1.png){fig-align='center'}\n:::\n:::\n\n\n::: {.callout-tip icon=false}\n## Ejemplo: Vida útil de una lámpara LED\n\nEl fabricante de una lámpara LED afirma que su vida útil (en miles de horas) sigue una distribución $\\text{Weibull}(k=2,\\; \\lambda=5)$.\n\n**a) Probabilidad de que la lámpara dure más de 4,000 horas ($x=4$)**\n\n$$P(X > 4) = 1 - F(4) = \\exp\\!\\left[-\\left(\\frac{4}{5}\\right)^2\\right] = e^{-0.64} \\approx 0.5273$$\n\n**b) Vida útil esperada**\n\n$$E[X] = 5\\,\\Gamma\\!\\left(1 + \\frac{1}{2}\\right) = 5\\,\\Gamma(1.5) = 5 \\cdot \\frac{\\sqrt{\\pi}}{2} \\approx 5 \\cdot 0.8862 = 4.431 \\text{ mil horas}$$\n\n**c) Percentil 10% (vida garantizable para el 90% de las lámparas)**\n\n$$F(x_{0.10}) = 0.10 \\implies 1 - e^{-(x/5)^2} = 0.10$$\n$$e^{-(x/5)^2} = 0.90 \\implies \\left(\\frac{x}{5}\\right)^2 = -\\ln(0.90) \\approx 0.1054$$\n$$x_{0.10} = 5\\sqrt{0.1054} \\approx 1.623 \\text{ mil horas}$$\n\n\n::: {.cell}\n\n```\n#> P(X > 4) = 0.5273\n#> E[X] = 4.4311 mil horas\n#> Percentil 10% = 1.623 mil horas\n#> Mediana = 4.1628 mil horas\n```\n:::\n\n\n:::\n\n::: {.callout-note icon=false}\n## Ejercicios propuestos\n\n1. Los rodamientos de una máquina industrial tienen vida útil $\\text{Weibull}(k=3,\\; \\lambda=2000)$ horas. Calcule la probabilidad de que un rodamiento falle antes de las 1500 horas y la vida útil media.\n\n2. Demuestre que cuando $k=1$, la distribución Weibull se reduce a una exponencial con tasa $1/\\lambda$, y que la función de riesgo es constante.\n\n3. Una compañía de seguros modela el tiempo hasta el primer reclamo con una $\\text{Weibull}(k=0.8,\\; \\lambda=3)$ años. ¿Qué implica $k < 1$ sobre la probabilidad de reclamos? Grafique $h(x)$.\n\n4. Sea $X \\sim \\text{Weibull}(k, \\lambda)$. Demuestre que $Y = (X/\\lambda)^k \\sim \\text{Exp}(1)$.\n\n:::\n\n### Resumen: distribuciones continuas básicas\n\n#### Conceptos Fundamentales\n\nA diferencia de las variables discretas, una **variable aleatoria continua** puede tomar infinitos valores dentro de un intervalo en la recta real (ej. tiempo, peso, distancia). \n\n* **Probabilidad puntual:** La probabilidad de que la variable asuma un valor exacto y específico es cero:\n  $$P(X=x) = 0$$\n* **Función de Densidad de Probabilidad (f.d.p.), $f(x)$:** Sustituye a la probabilidad puntual. Geométricamente, la probabilidad de que la variable caiga en un intervalo $[a, b]$ es el área bajo la curva de $f(x)$ en ese intervalo, calculada mediante integración:\n  $$P(a \\le X \\le b) = \\int_{a}^{b} f(x)dx$$\n* **Función de Probabilidad Acumulada, $F(x)$:** Acumula el área bajo la curva desde $-\\infty$ hasta un valor $x$.\n  $$F(x) = P(X \\le x)$$\n\n***\n\n#### Distribución Uniforme Continua\n\nModela fenómenos donde todos los subintervalos de la misma longitud dentro de un rango $[a, b]$ tienen exactamente la misma probabilidad de ocurrir. Su f.d.p. forma un rectángulo. Se denota como $X \\sim U(a, b)$.\n\n* **Función de densidad:** $$f(x) = \\frac{1}{b - a} \\quad \\text{para } a \\le x \\le b$$\n* **Esperanza y Varianza:** $$E[X] = \\frac{a+b}{2} \\quad \\text{y} \\quad \\text{Var}(X) = \\frac{(b-a)^2}{12}$$\n* **Aplicación típica:** Tiempos de espera aleatorios con límites conocidos y equiprobables.\n\n***\n\n#### Distribución Normal\n\nEs la distribución más importante en la estadística inferencial. Su gráfica tiene forma de campana (Campana de Gauss), es asintótica al eje horizontal y perfectamente simétrica. Se denota como $X \\sim N(\\mu, \\sigma^2)$.\n\n* **Parámetros:** Está definida por su **media** ($\\mu$, que determina su centro/localización) y su **desviación estándar** ($\\sigma$, que determina su amplitud/forma).\n* **Regla Empírica:** \n  * Aproximadamente el **68.2%** de los datos cae en el intervalo $\\mu \\pm 1\\sigma$.\n  * El **95.4%** cae en el intervalo $\\mu \\pm 2\\sigma$.\n  * El **99.8%** cae en el intervalo $\\mu \\pm 3\\sigma$.\n\n***\n\n#### Distribución Normal Estándar y Uso de Tablas\n\nDado que la f.d.p. de la distribución normal no tiene una integral analítica sencilla, se utiliza un proceso de **estandarización** para transformar cualquier variable normal $X$ en una variable normal estándar $Z$, la cual tiene media $\\mu=0$ y varianza $\\sigma^2=1$.\n\n* **Fórmula de tipificación:** $$Z = \\frac{X - \\mu}{\\sigma}$$\n  Esta fórmula indica a cuántas desviaciones estándar se encuentra un valor $X$ respecto a la media.\n* **Cálculo de probabilidades:** Se utilizan tablas estandarizadas (o software) que contienen las áreas acumuladas $P(Z \\le z)$. Para intervalos o \"colas derechas\", se aplican propiedades matemáticas de la probabilidad (como el complemento $1 - P(Z \\le z)$) y la **propiedad de simetría** de la campana.\n\n***\n\n#### Distribución Exponencial\n\nSe utiliza para modelar el tiempo o la distancia que transcurre hasta que ocurre un evento de interés (ej. tiempo entre fallas, tiempo hasta recibir una llamada), asumiendo una tasa de ocurrencia constante ($\\lambda$). Se denota como $X \\sim \\text{Exp}(\\lambda)$.\n\n* **Función de densidad:** $$f(x) = \\lambda e^{-\\lambda x} \\quad \\text{para } x \\ge 0$$\n* **Esperanza:** (El tiempo promedio de espera)\n  $$E[X] = \\frac{1}{\\lambda}$$\n* **Propiedad de Falta de Memoria (Memoryless):** Es la única distribución continua con esta propiedad. Establece que la probabilidad condicional de que un evento ocurra en el futuro depende solo del tiempo restante, \"olvidando\" el tiempo que ya ha transcurrido: \n  $$P(X > s+t \\mid X > t) = P(X > s)$$\n\n\n\n## Distribuciones conjuntas {#sec-conjuntas}\n\n:::: {.content-visible when-format=\"html\"}\n[📖 Magín Zúñiga Estrada]{.fuente-badge .fuente-magin}\n\n::::\n\nCuando se estudian **dos o más variables aleatorias simultáneamente**, necesitamos herramientas que describan su comportamiento conjunto. Esta sección presenta la función de distribución acumulada conjunta, las funciones de masa/densidad conjunta, las distribuciones marginales y el concepto de independencia.\n\n### Función de distribución conjunta\n\n::: {.callout-tip icon=false}\n## Definición: CDF conjunta\n\nSean $X$ e $Y$ dos variables aleatorias. La **función de distribución acumulada conjunta** se define como:\n\n$$F_{X,Y}(x,y) = P(X \\leq x,\\; Y \\leq y) \\quad \\text{para todo } (x,y) \\in \\mathbb{R}^2$$\n\n**Propiedades:**\n\n1. $F(x,y)$ es no decreciente en cada argumento.\n2. $\\lim_{x,y \\to -\\infty} F(x,y) = 0$.\n3. $\\lim_{x,y \\to +\\infty} F(x,y) = 1$.\n\nLas **funciones de distribución marginales** se recuperan como:\n\n$$F_X(x) = F_{X,Y}(x, +\\infty), \\qquad F_Y(y) = F_{X,Y}(+\\infty, y)$$\n\n:::\n\n::: {.callout-tip icon=false}\n## Ejemplo: dos tetraedros (Magín Zúñiga)\n\nSe lanzan dos tetraedros de cuatro caras. Sea $X$ la cara invertida del primer tetraedro e $Y$ el **mayor** de los dos valores. Los 16 resultados son equiprobables ($P = 1/16$ cada uno).\n\nCalcular $F_{X,Y}(2,3) = P(X \\leq 2,\\; Y \\leq 3)$: los pares que satisfacen la condición son $(1,1),(1,2),(1,3),(2,1),(2,2),(2,3)$ — un total de 6 puntos, por lo que:\n\n$$F(2,3) = \\frac{6}{16} = 0.375$$\n\nLa tabla completa de la cdf conjunta:\n\n| $x \\backslash y$ | 1 | 2 | 3 | 4 |\n|:-:|:-:|:-:|:-:|:-:|\n| 1 | 1/16 | 2/16 | 3/16 | 4/16 |\n| 2 | 0 | 4/16 | 6/16 | 8/16 |\n| 3 | 0 | 0 | 9/16 | 12/16 |\n| 4 | 0 | 0 | 0 | 16/16 |\n\n:::\n\n### Función de masa de probabilidad conjunta (caso discreto)\n\n::: {.callout-tip icon=false}\n## Definición: PMF conjunta discreta\n\nSi $X$ e $Y$ son discretas con valores $\\{x_1,\\ldots,x_n\\}$ y $\\{y_1,\\ldots,y_m\\}$, la **función masa de probabilidad conjunta** es:\n\n$$p(x_i, y_j) = P(X = x_i,\\; Y = y_j)$$\n\n**Propiedades:**\n\n1. $0 \\leq p(x_i, y_j) \\leq 1$ para toda $i,j$.\n2. $\\displaystyle\\sum_{i}\\sum_{j} p(x_i, y_j) = 1$.\n\nLas **pmf marginales** se obtienen sumando sobre la otra variable:\n\n$$p_X(x) = \\sum_j p(x, y_j), \\qquad p_Y(y) = \\sum_i p(x_i, y)$$\n\n:::\n\n::: {.callout-tip icon=false}\n## Ejemplo: dos dados (Magín Zúñiga)\n\nSea $X$ el valor del primer dado e $Y$ el del segundo. La pmf conjunta es $p(i,j) = 1/36$ para $i,j \\in \\{1,\\ldots,6\\}$.\n\n\n::: {.cell}\n\n```\n#> Marginal X: 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667\n#> Marginal Y: 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667\n#> Suma total: 1\n```\n:::\n\n\nAhora sea $Y$ la **suma** de ambos dados. La distribución marginal de $Y$ (suma de dos dados):\n\n\n::: {.cell}\n\n```\n#> P(Y=k) para k=2,...,12:\n#>   P(Y= 2) = 1/36 ≈ 0.0278\n#>   P(Y= 3) = 2/36 ≈ 0.0556\n#>   P(Y= 4) = 3/36 ≈ 0.0833\n#>   P(Y= 5) = 4/36 ≈ 0.1111\n#>   P(Y= 6) = 5/36 ≈ 0.1389\n#>   P(Y= 7) = 6/36 ≈ 0.1667\n#>   P(Y= 8) = 5/36 ≈ 0.1389\n#>   P(Y= 9) = 4/36 ≈ 0.1111\n#>   P(Y=10) = 3/36 ≈ 0.0833\n#>   P(Y=11) = 2/36 ≈ 0.0556\n#>   P(Y=12) = 1/36 ≈ 0.0278\n```\n:::\n\n\n:::\n\n### Función de densidad de probabilidad conjunta (caso continuo)\n\n::: {.callout-tip icon=false}\n## Definición: PDF conjunta continua\n\nSi $X$ e $Y$ son continuas, la **función de densidad de probabilidad conjunta** $f(x,y)$ satisface:\n\n$$P(X \\leq x,\\; Y \\leq y) = \\int_{-\\infty}^{x}\\int_{-\\infty}^{y} f(u,v)\\,dv\\,du$$\n\n**Propiedades:**\n\n1. $f(x,y) \\geq 0$ para todo $(x,y)$.\n2. $\\displaystyle\\int_{-\\infty}^{\\infty}\\int_{-\\infty}^{\\infty} f(x,y)\\,dy\\,dx = 1$.\n\nLas **densidades marginales** son:\n\n$$f_X(x) = \\int_{-\\infty}^{\\infty} f(x,y)\\,dy, \\qquad f_Y(y) = \\int_{-\\infty}^{\\infty} f(x,y)\\,dx$$\n\n:::\n\n::: {.callout-tip icon=false}\n## Ejemplo: marginales continuas (Magín Zúñiga)\n\nSea $(X,Y)$ con densidad conjunta $f(x,y) = \\frac{8}{3}x^3 y$ en $[0,1]\\times[1,2]$.\n\n**Marginal de $X$:**\n\n$$f_X(x) = \\int_1^2 \\frac{8}{3}x^3 y\\,dy = \\frac{8}{3}x^3\\left[\\frac{y^2}{2}\\right]_1^2 = \\frac{8}{3}x^3 \\cdot \\frac{3}{2} = 4x^3$$\n\n**Marginal de $Y$:**\n\n$$f_Y(y) = \\int_0^1 \\frac{8}{3}x^3 y\\,dx = \\frac{8}{3}y\\left[\\frac{x^4}{4}\\right]_0^1 = \\frac{2}{3}y$$\n\n\n::: {.cell}\n\n```\n#> [1] 0.5\n#> f_X(0.5) = 4*(0.5)^3 = 0.5\n#> f_Y(1.5) = (2/3)*1.5 = 1\n```\n:::\n\n\n:::\n\n::: {.callout-note icon=false}\n## Ejercicio: marginales continuas\n\nSea $(X,Y)$ con densidad conjunta $f(x,y) = \\frac{3}{2}(x^2 + y^2)$ en $[0,1]\\times[0,1]$.\n\na. Encuentra $f_X(x)$ y calcula $P(X < 0.5)$.\nb. ¿Son $X$ e $Y$ independientes? Justifica.\n\n**Solución (a):**\n\n$$f_X(x) = \\int_0^1 \\frac{3}{2}(x^2+y^2)\\,dy = \\frac{3}{2}x^2 + \\frac{1}{2}$$\n\n$$P(X < 0.5) = \\int_0^{0.5}\\left(\\frac{3}{2}x^2 + \\frac{1}{2}\\right)dx = \\frac{5}{16}$$\n\n:::\n\n### Independencia de variables aleatorias\n\n::: {.callout-tip icon=false}\n## Definición: independencia\n\nLas variables aleatorias $X$ e $Y$ son **independientes** si y solo si:\n\n$$F_{X,Y}(x,y) = F_X(x)\\,F_Y(y) \\quad \\text{para todo } (x,y)$$\n\nEquivalentemente:\n\n- **Caso discreto:** $p(x_i, y_j) = p_X(x_i)\\,p_Y(y_j)$ para todo $i,j$.\n- **Caso continuo:** $f(x,y) = f_X(x)\\,f_Y(y)$ para todo $(x,y)$.\n\nPara $n$ variables, son mutuamente independientes si:\n\n$$F(x_1,\\ldots,x_n) = \\prod_{i=1}^n F_{X_i}(x_i)$$\n\n:::\n\n::: {.callout-tip icon=false}\n## Ejemplos de independencia/dependencia (Magín Zúñiga)\n\n- **Independientes:** $f(x,y) = 96x^2 y^3$ en $[0,1/2]\\times[0,1]$ — se factoriza como $f_X(x)\\cdot f_Y(y)$.\n- **Dependientes:** $f(x,y) = 1.5(x^2+y^2)$ en $[0,1]^2$ — no se puede factorizar.\n- **Dependientes:** $F(x,y) = \\frac{1}{2}(x^3 y + x y^3)$ en $[0,1]^2$ — la cdf conjunta no es producto de marginales.\n\n**Interpretación discreta:** en una tabla $p(x_i, y_j)$, independencia significa que cada celda es el producto de su marginal de fila por su marginal de columna.\n\n:::\n\n## Esperanza y varianza de variables aleatorias {#sec-esperanza-varianza}\n\n::: {.callout-tip icon=false}\n## Fuente: Apuntes del curso (Prof. Magín Zúñiga Estrada)\n\nEl desarrollo teórico de esta sección sigue el texto del Dr. Magín\nZúñiga Estrada, que presenta la teoría de esperanza de forma unificada\npara variables discretas y continuas.\n\n:::\n\n### Valor esperado\n\nEl **valor esperado** (o esperanza matemática) de una variable aleatoria\n$X$ es la media ponderada de todos los valores posibles de $X$, donde el\npeso de cada valor es su probabilidad.\n\n- **Caso discreto.** Si $X$ toma valores $x_1, x_2, \\ldots$ con pmf $p(x_i)$:\n$$E[X] = \\sum_i x_i\\, p(x_i).$$\n\n- **Caso continuo.** Si $X$ tiene función de densidad $f_X(x)$:\n$$E[X] = \\int_{-\\infty}^{\\infty} x\\, f_X(x)\\, dx.$$\n\n::: {.callout-note icon=false}\n## Comentarios\n\n- El valor esperado también se llama **media** o **promedio** de $X$ y se denota $\\mu$.\n- No necesariamente coincide con un valor posible de $X$; es un promedio ponderado.\n- Proporciona una medida de **tendencia central** de la distribución.\n\n:::\n\n**Propiedades de la esperanza** (linealidad):\n\n1. $E[X + Y] = E[X] + E[Y]$ para cualquier par de v.a. $X, Y$.\n2. $E[aX + b] = a\\,E[X] + b$ para constantes $a, b$.\n\n**Esperanza de funciones.** Si $h$ es una función, la esperanza de $h(X)$\nes:\n\n- Caso discreto: $E[h(X)] = \\sum_i h(x_i)\\, p(x_i)$.\n- Caso continuo: $E[h(X)] = \\int_{-\\infty}^{\\infty} h(x)\\, f_X(x)\\, dx$.\n\nLa idea se extiende naturalmente a dos variables. Sean $X$ e $Y$ con pmf/pdf conjunta y $g:\\mathbb{R}^2\\to\\mathbb{R}$:\n\n- **Caso discreto:** $E[g(X,Y)] = \\displaystyle\\sum_i\\sum_j g(x_i,y_j)\\,p(x_i,y_j)$.\n- **Caso continuo:** $E[g(X,Y)] = \\displaystyle\\int_{-\\infty}^{\\infty}\\int_{-\\infty}^{\\infty} g(x,y)\\,f(x,y)\\,dy\\,dx$.\n\n::: {.callout-tip icon=false}\n## Ejemplo: función de ganancia en dados (Magín Zúñiga)\n\nSea $X$ la suma de puntos al lanzar dos dados y $Y = X^2 - 6X + 1$ la función de ganancia.\n\n$$E[Y] = \\sum_{x=2}^{12}(x^2 - 6x + 1)\\,p(x)$$\n\n\n::: {.cell}\n\n```\n#> E[Y] = E[X^2 - 6X + 1] = 13.8333\n#> Con E[X] = 7 y E[X^2] = 54.83333\n#> Por linealidad: E[X^2] - 6*E[X] + 1 = 13.83333\n```\n:::\n\n\nSi $E[Y] < 0$, el juego es desfavorable para el jugador.\n\n:::\n\n\n::: {.cell}\n\n```\n#> E[dado] = 3.5\n#> E[Exp(2)] = 1/lambda = 0.5\n#> Verificación numérica: 0.5\n```\n:::\n\n\n**Tabla resumen de esperanzas** de las distribuciones principales:\n\n| Distribución | Parámetros | $E[X]$ | $\\text{Var}(X)$ |\n|:-------------|:-----------|:------:|:---------------:|\n| Bernoulli | $p$ | $p$ | $p(1-p)$ |\n| Binomial | $n, p$ | $np$ | $np(1-p)$ |\n| Geométrica | $p$ | $(1-p)/p$ | $(1-p)/p^2$ |\n| Poisson | $\\lambda$ | $\\lambda$ | $\\lambda$ |\n| Uniforme $[a,b]$ | $a, b$ | $(a+b)/2$ | $(b-a)^2/12$ |\n| Exponencial | $\\lambda$ | $1/\\lambda$ | $1/\\lambda^2$ |\n| Normal | $\\mu, \\sigma^2$ | $\\mu$ | $\\sigma^2$ |\n| Gamma | $\\alpha, \\beta$ | $\\alpha\\beta$ | $\\alpha\\beta^2$ |\n\n### Varianza y desviación estándar\n\nAunque la media proporciona el \"centro\" de la distribución, no es\nsuficiente para caracterizarla. La **varianza** mide cuánto se dispersa\nla probabilidad alrededor de la media.\n\n::: {.callout-note icon=false}\n## Definición: Varianza\n\nSi $X$ es una variable aleatoria con $E[X] = \\mu$, entonces:\n$$\\text{Var}(X) = E[(X-\\mu)^2].$$\n\nLa **desviación estándar** es $\\sigma = \\sqrt{\\text{Var}(X)}$.\n\n:::\n\n**Fórmula computacional** (frecuentemente más práctica):\n$$\\text{Var}(X) = E[X^2] - (E[X])^2.$$\n\n**Propiedades de la varianza:**\n\n1. Si $X$ y $Y$ son **independientes**: $\\text{Var}(X+Y) = \\text{Var}(X) + \\text{Var}(Y)$.\n2. Para constantes $a$ y $b$: $\\text{Var}(aX+b) = a^2\\,\\text{Var}(X)$.\n3. $\\text{Var}(X) = E[X^2] - \\mu^2$.\n\n:::: {.content-visible when-format=\"html\"}\n[📖 Magín Zúñiga Estrada]{.fuente-badge .fuente-magin}\n\n::::\n\n::: {.callout-tip icon=false}\n## Aplicaciones de las propiedades de varianza\n\n**Varianza de Bernoulli($p$).** Sea $X \\sim \\text{Ber}(p)$. Como $X \\in \\{0,1\\}$, tenemos $X^2 = X$, luego $E[X^2] = p$, y:\n\n$$\\text{Var}(X) = E[X^2] - \\mu^2 = p - p^2 = p(1-p)$$\n\n**Varianza de Binomial($n,p$).** Como $X = \\sum_{i=1}^n X_i$ con $X_i \\sim \\text{Ber}(p)$ independientes:\n\n$$\\text{Var}(X) = \\sum_{i=1}^n \\text{Var}(X_i) = n\\,p(1-p)$$\n\n**Varianza de Uniforme($[0,1]$).** Con $\\mu = 1/2$:\n\n$$\\text{Var}(X) = \\int_0^1 \\left(x - \\tfrac{1}{2}\\right)^2 dx = \\left[\\frac{(x-1/2)^3}{3}\\right]_0^1 = \\frac{1}{12}$$\n\n**Varianza de Exponencial($\\lambda$).** Usando $E[X^2] = 2/\\lambda^2$ y $\\mu = 1/\\lambda$:\n\n$$\\text{Var}(X) = \\frac{2}{\\lambda^2} - \\frac{1}{\\lambda^2} = \\frac{1}{\\lambda^2}$$\n\n\n::: {.cell}\n\n```\n#> Var(Ber(0.3)) = 0.21\n#> Var(Bin(10,0.3)) = 2.1\n#> Var(Unif[0,1]) = 0.08333333\n#> Var(Exp(2)) = 1/lambda^2 = 0.25\n#> Monte Carlo Var(Exp(2)): 0.2499\n```\n:::\n\n\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/varianza-ejemplos-1.png){fig-align='center'}\n:::\n:::\n\n\n## Covarianza y correlación {#sec-covarianza}\n\nCuando se trabaja con dos o más variables aleatorias, es natural preguntar\nsi estas se \"mueven juntas\" o de manera independiente.\n\n### Covarianza\n\n::: {.callout-note icon=false}\n## Definición: Covarianza\n\nSean $X$ y $Y$ dos variables aleatorias. La **covarianza** entre $X$ y $Y$\nse define como:\n$$\\text{Cov}(X,Y) = E[(X - E[X])(Y - E[Y])].$$\n\nEquivalentemente: $\\text{Cov}(X,Y) = E[XY] - E[X]\\,E[Y]$.\n\n:::\n\n**Interpretación:**\n\n- $\\text{Cov}(X,Y) > 0$: cuando $X$ supera su media, $Y$ tiende a superar\n  la suya también (correlación positiva).\n- $\\text{Cov}(X,Y) < 0$: cuando $X$ supera su media, $Y$ tiende a estar\n  por debajo (correlación negativa).\n- $\\text{Cov}(X,Y) = 0$: $X$ y $Y$ **no están correlacionadas**\n  (aunque no implica independencia en general).\n\n**Consecuencia para la varianza de la suma:**\n$$\\text{Var}(X+Y) = \\text{Var}(X) + \\text{Var}(Y) + 2\\,\\text{Cov}(X,Y).$$\n\n**Independencia implica no correlación** (pero no al revés): si $X$ e $Y$\nson independientes, entonces $\\text{Cov}(X,Y) = 0$.\n\n### Coeficiente de correlación\n\nLa covarianza tiene unidades (producto de las unidades de $X$ y $Y$), lo\nque dificulta comparaciones. El **coeficiente de correlación de Pearson**\nes una versión estandarizada e **adimensional**:\n\n::: {.callout-note icon=false}\n## Definición: Correlación de Pearson\n\n$$\\rho(X,Y) = \\frac{\\text{Cov}(X,Y)}{\\sqrt{\\text{Var}(X)\\,\\text{Var}(Y)}}.$$\n\nSe cumple que $-1 \\leq \\rho(X,Y) \\leq 1$.\n\n:::\n\n| Valor de $\\rho$ | Interpretación |\n|:----------------|:---------------|\n| $\\rho \\approx 1$ | Relación lineal positiva casi perfecta |\n| $\\rho \\approx -1$ | Relación lineal negativa casi perfecta |\n| $\\rho \\approx 0$ | Sin relación lineal (pueden existir relaciones no lineales) |\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/covarianza-demo-1.png){fig-align='center'}\n:::\n:::\n\n\n## Esperanza y varianza condicional {#sec-esp-condicional}\n\nLa **esperanza condicional** $E[Y \\mid X = x]$ es el valor esperado de\n$Y$ dado que $X$ toma el valor $x$. Es en sí misma una función de $x$,\ny por tanto una nueva variable aleatoria cuando $X$ es aleatoria.\n\n::: {.callout-note icon=false}\n## Ley de la esperanza total (ley de las esperanzas iteradas)\n\nPara cualesquiera variables aleatorias $X$ y $Y$:\n$$E[Y] = E[E[Y \\mid X]].$$\n\nAnálogamente, la **ley de la varianza total**:\n$$\\text{Var}(Y) = E[\\text{Var}(Y \\mid X)] + \\text{Var}(E[Y \\mid X]).$$\n\n:::\n\n**Ejemplo.** Sea $X \\sim \\text{Poisson}(\\lambda)$ el número de accidentes\nen un día, y dado $X=n$, el costo total $Y \\mid X=n \\sim \\text{Binomial}(n, p)$\n(cada accidente es grave con prob. $p$). Entonces $E[Y] = \\lambda p$.\n\n\n::: {.cell}\n\n```\n#> E[Y] teórico  : 1.5\n#> E[Y] simulado : 1.4992\n```\n:::\n\n\n## Función generatriz de momentos {#sec-fgm}\n\nLa **función generatriz de momentos (FGM)** de una variable aleatoria $X$\nes:\n$$M_X(t) = E[e^{tX}], \\quad t \\in \\mathbb{R} \\text{ (en una vecindad del 0)}.$$\n\nSu importancia radica en que:\n\n1. **Genera momentos**: $E[X^k] = M_X^{(k)}(0)$ (la $k$-ésima derivada\n   evaluada en $t=0$).\n2. **Caracteriza la distribución**: si dos v.a. tienen la misma FGM en\n   una vecindad del 0, tienen la misma distribución.\n3. **Facilita el análisis de sumas**: si $X_1, \\ldots, X_n$ son\n   independientes, $M_{X_1+\\cdots+X_n}(t) = \\prod_i M_{X_i}(t)$.\n\n| Distribución | FGM $M_X(t)$ |\n|:-------------|:------------|\n| Bernoulli$(p)$ | $1-p+pe^t$ |\n| Binomial$(n,p)$ | $(1-p+pe^t)^n$ |\n| Poisson$(\\lambda)$ | $e^{\\lambda(e^t-1)}$ |\n| Exponencial$(\\lambda)$ | $\\lambda/(\\lambda-t),\\ t<\\lambda$ |\n| Normal$(\\mu,\\sigma^2)$ | $e^{\\mu t + \\sigma^2 t^2/2}$ |\n\n\n::: {.cell}\n\n```\n#> E[X]   teórico: 2\n#> E[X^2] teórico: 13\n#> E[X]   simulado: 2.0001\n#> E[X^2] simulado: 13.0039\n```\n:::\n\n\n## Importancia en estadística\n\nLa LGN justifica el uso de **promedios muestrales** como estimadores de\nmedias poblacionales: con suficientes datos, el promedio muestral estará\ntan cerca de $\\mu$ como se quiera. Esta es la base filosófica de la\n**estimación puntual** que se estudiará en el capítulo de inferencia.\n\n:::\n\n\n## Estadísticos muestrales {#sec-estadisticos-muestrales}\n\n::: {.content-visible when-format=\"html\"}\n[📖 Magín Zúñiga Estrada]{.fuente-badge .fuente-magin}\n\n:::\n\n\n::: {.callout-tip icon=false}\n## Fuente: Apuntes del curso (Prof. Magín Zúñiga Estrada)\n\n:::\n\nUn investigador estadístico usa información de una muestra $X_1,\\ldots,X_n$\npara obtener conclusiones de la población. Dado que la muestra puede ser una\nlarga lista de números difícil de interpretar, se calculan **estadísticos**\n— funciones de la muestra — que resumen sus características clave.\n\n::: {.callout-note icon=false}\n## Definición: Estadístico\n\nSea $X_1,\\ldots,X_n$ una muestra aleatoria de tamaño $n$ de una población\ny $T(x_1,\\ldots,x_n)$ una función de valor real con dominio en el espacio\nmuestral de $(X_1,\\ldots,X_n)$. Entonces la variable aleatoria\n$Y = T(X_1,\\ldots,X_n)$ se llama **estadístico**. Su distribución de\nprobabilidad se denomina **distribución muestral** de $Y$.\n\n:::\n\nLos tres estadísticos más importantes son:\n\n::: {.callout-note icon=false}\n## Media, varianza y desviación estándar muestrales\n\n**Media muestral:**\n$$\\bar{X} = \\frac{1}{n}\\sum_{i=1}^{n} X_i.$$\n\n**Varianza muestral:**\n$$S^2 = \\frac{1}{n-1}\\sum_{i=1}^{n}(X_i - \\bar{X})^2.$$\n\n**Desviación estándar muestral:** $S = \\sqrt{S^2}$.\n\n:::\n\n::: {.callout-note icon=false}\n## Teorema: Esperanza y varianza de los estadísticos muestrales\n\nSea $X_1,\\ldots,X_n$ una muestra aleatoria de una población con media\n$\\mu$ y varianza $\\sigma^2 < \\infty$. Entonces:\n\n1. $E[\\bar{X}] = \\mu$\n2. $\\text{Var}(\\bar{X}) = \\dfrac{\\sigma^2}{n}$\n3. $E[S^2] = \\sigma^2$\n\nEs decir, $\\bar{X}$ es estimador insesgado de $\\mu$ y $S^2$ es estimador\ninsesgado de $\\sigma^2$.\n\n:::\n\nLa identidad útil $(n-1)S^2 = \\sum X_i^2 - n\\bar{X}^2$ facilita los\ncálculos algebraicos.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/estadisticos-muestrales-sim-1.png){fig-align='center'}\n:::\n:::\n\n\n## Convergencia en probabilidad y TCL {#sec-convergencia-tcl}\n\n::: {.content-visible when-format=\"html\"}\n[📖 Magín Zúñiga Estrada]{.fuente-badge .fuente-magin}\n\n:::\n\n\n::: {.callout-tip icon=false}\n## Fuente: Apuntes del curso (Prof. Magín Zúñiga Estrada)\n\n:::\n\nEsta sección aborda, desde un enfoque teórico, el comportamiento de\nestadísticos muestrales cuando el tamaño de muestra $n \\to \\infty$.\n\n### Convergencia en probabilidad\n\n::: {.callout-note icon=false}\n## Definición: Convergencia en probabilidad\n\nUna secuencia de variables aleatorias $X_1, X_2, \\ldots$ **converge en\nprobabilidad** a una variable aleatoria $X$ (se escribe\n$X_n \\xrightarrow{p} X$) si, para todo $\\varepsilon > 0$:\n$$\\lim_{n \\to \\infty} P(|X_n - X| \\geq \\varepsilon) = 0,$$\no equivalentemente,\n$\\lim_{n \\to \\infty} P(|X_n - X| < \\varepsilon) = 1.$\n\n:::\n\n::: {.callout-note icon=false}\n## Teorema: Ley débil de los grandes números (con prueba)\n\nSea $X_1, X_2, \\ldots$ iid con $E[X_i] = \\mu$ y\n$\\text{Var}(X_i) = \\sigma^2 < \\infty$. Entonces\n$\\bar{X}_n \\xrightarrow{p} \\mu$.\n\n**Prueba** (via desigualdad de Chebyshev): Para todo $\\varepsilon > 0$,\n$$P(|\\bar{X}_n - \\mu| \\geq \\varepsilon) \\leq\n  \\frac{\\text{Var}(\\bar{X}_n)}{\\varepsilon^2} =\n  \\frac{\\sigma^2}{n\\varepsilon^2} \\xrightarrow{n\\to\\infty} 0.$$\n\n:::\n\n::: {.callout-note icon=false}\n## Ejemplo: Consistencia de $S^2$\n\nSi $X_1, X_2, \\ldots$ son iid con $E[X_i] = \\mu$,\n$\\text{Var}(X_i) = \\sigma^2 < \\infty$, entonces por Chebyshev:\n$$P(|S_n^2 - \\sigma^2| \\geq \\varepsilon) \\leq\n  \\frac{\\text{Var}(S_n^2)}{\\varepsilon^2} \\to 0,$$\nya que $\\text{Var}(S_n^2) \\to 0$ cuando $n \\to \\infty$. Por tanto\n$S_n^2 \\xrightarrow{p} \\sigma^2$.\n\n:::\n\n### Teorema Central del Límite\n\n::: {.callout-note icon=false}\n## Teorema Central del Límite (TCL)\n\nSea $X_1, X_2, \\ldots$ iid con $E[X_i] = \\mu$ y\n$\\text{Var}(X_i) = \\sigma^2 > 0$ (ambas finitas). Sea\n$\\bar{X}_n = (1/n)\\sum_{i=1}^n X_i$. Entonces:\n$$\\frac{\\sqrt{n}(\\bar{X}_n - \\mu)}{\\sigma}\n  \\xrightarrow{d} N(0,1) \\quad \\text{cuando } n \\to \\infty,$$\nes decir, para cualquier $x \\in \\mathbb{R}$:\n$$\\lim_{n\\to\\infty} P\\!\\left(\\frac{\\sqrt{n}(\\bar{X}_n-\\mu)}{\\sigma} \\leq x\\right)\n  = \\Phi(x) = \\int_{-\\infty}^x \\frac{1}{\\sqrt{2\\pi}} e^{-y^2/2}\\,dy.$$\n\n:::\n\nEl TCL justifica la aproximación normal para sumas de v.a. con $n$ grande,\nindependientemente de la distribución original de las $X_i$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](cap03-distribucion-conjunta_files/figure-docx/tcl-demo-1.png){fig-align='center'}\n:::\n:::\n\n\n\n## Resumen del capítulo\n\n| Distribución | Parámetros | $E[X]$ | $\\text{Var}(X)$ | Propiedad clave |\n|:-------------|:----------:|:------:|:---------------:|:----------------|\n| Uniforme continua | $a, b$ | $\\frac{a+b}{2}$ | $\\frac{(b-a)^2}{12}$ | Densidad constante en $[a,b]$ |\n| Normal | $\\mu, \\sigma^2$ | $\\mu$ | $\\sigma^2$ | Simétrica, campana de Gauss |\n| Exponencial | $\\lambda$ | $\\frac{1}{\\lambda}$ | $\\frac{1}{\\lambda^2}$ | Falta de memoria |\n| Gamma | $\\alpha, \\lambda$ | $\\frac{\\alpha}{\\lambda}$ | $\\frac{\\alpha}{\\lambda^2}$ | Suma de $\\alpha$ Exp($\\lambda$) |\n| Weibull | $k, \\lambda$ | $\\lambda\\,\\Gamma(1+1/k)$ | $\\lambda^2[\\Gamma(1+2/k)-\\Gamma(1+1/k)^2]$ | Tasa de fallo variable |\n\n::: {.callout-note icon=false}\n## Criterio de selección del modelo continuo\n\n- Valor en un intervalo sin preferencia: **Uniforme** continua.\n- Fenómeno gobernado por muchos factores aditivos: **Normal**.\n- Tiempo hasta el primer evento, sin memoria: **Exponencial**.\n- Suma de $k$ tiempos exponenciales independientes: **Gamma**.\n- Tiempo de vida con tasa de fallo creciente/decreciente: **Weibull**.\n\n:::\n\n::: {.callout-tip icon=false}\n## Ideas clave del capítulo\n\n- Para una VA continua $X$, $P(X = x) = 0$ siempre; las probabilidades son áreas bajo $f(x)$.\n- La **estandarización** $Z = (X - \\mu)/\\sigma$ transforma cualquier $N(\\mu,\\sigma^2)$ en $N(0,1)$.\n- **Distribuciones conjuntas**: $f_{X,Y}(x,y)$ describe el comportamiento simultáneo; las marginales se obtienen integrando sobre la otra variable.\n- **Independencia**: $X$ e $Y$ son independientes si y solo si $f_{X,Y}(x,y) = f_X(x)\\,f_Y(y)$.\n- **TCL**: para muestras grandes, $\\bar{X} \\approx N(\\mu, \\sigma^2/n)$ sin importar la distribución original.\n\n:::\n\n## Ejercicios propuestos {#sec-ejercicios-esp-cov}\n\nLos siguientes ejercicios cubren esperanza, varianza, covarianza, distribuciones conjuntas y el TCL.\n\n1. Sea $X \\sim \\text{Poisson}(\\lambda)$. Use el TCL para aproximar $P(\\bar{X}_n > 5.2)$\n   cuando $\\lambda = 5$ y $n = 100$.\n2. Demuestre que si $X_n \\xrightarrow{p} c$ (constante), entonces $X_n^2 \\xrightarrow{p} c^2$.\n3. ¿Por qué el TCL no aplica directamente cuando $\\text{Var}(X_i) = \\infty$?\n   Dé un ejemplo de distribución con varianza infinita.\n\n1. Sea $X \\sim \\text{Poisson}(3)$. Calcule $E[X]$, $\\text{Var}(X)$ y\n   $E[X(X-1)]$.\n\n2. Sean $X$ y $Y$ v.a. con $E[X]=2$, $E[Y]=5$, $\\text{Var}(X)=4$,\n   $\\text{Var}(Y)=9$ y $\\text{Cov}(X,Y) = -3$. Calcule:\n   a) $E[2X - Y + 1]$.\n   b) $\\text{Var}(X + Y)$ y $\\text{Var}(3X - 2Y)$.\n   c) $\\rho(X,Y)$.\n\n3. Demuestre que si $X$ e $Y$ son independientes, entonces\n   $\\text{Cov}(X,Y) = 0$. ¿Es cierto el recíproco? Construya un\n   contraejemplo.\n\n4. Sea $X \\sim N(\\mu, \\sigma^2)$. Demuestre que $\\text{Cov}(X, X) = \\text{Var}(X)$.\n\n5. Si $X$ e $Y$ son independientes con $E[X]=3$, $E[Y]=4$, $\\text{Var}(X)=2$, $\\text{Var}(Y)=5$, calcule $E[XY]$, $\\text{Cov}(X,Y)$ y $\\text{Var}(2X-3Y+1)$.\n\n## Conexión con el siguiente capítulo\n\nHasta aquí hemos trabajado con distribuciones teóricas conocidas: sabíamos exactamente qué distribución seguía $X$ y cuáles eran sus parámetros. En la práctica, los parámetros $\\mu$, $\\sigma^2$ o $p$ son *desconocidos*: solo tenemos una muestra. En el siguiente capítulo estudiaremos cómo estimarlos a partir de datos y cómo cuantificar la incertidumbre de esas estimaciones mediante distribuciones muestrales — en particular, la $\\chi^2$, la $t$ de Student y la $F$ de Fisher, que son directamente derivadas de la distribución Normal que acabas de aprender.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}